???: lyra::main Class Reference
lyra::main Class Reference final
#include <main.hpp>
Public Member Functions
main (const std::string &text="")
main (const std::string &text="")
template<typename T >
main & add_argument (const T &parser)
template<typename T >
main & add_argument (const T &parser)
template<typename L >
int operator() (const args &argv, L action)
template<typename L >
int operator() (const args &argv, L action)
template<typename V >
main & operator() (const std::string &arg_name, V &&default_value)
template<typename V >
main & operator() (const std::string &arg_name, V &&default_value)
template<typename T >
main & operator() (const T &parser)
template<typename T >
main & operator() (const T &parser)
template<typename L >
int operator() (int argc, const char **argv, L action)
template<typename L >
int operator() (int argc, const char **argv, L action)
template<typename V >
main & operator() (std::initializer_list< std::string > arg_names, V &&default_value)
template<typename V >
main & operator() (std::initializer_list< std::string > arg_names, V &&default_value)
template<typename T >
main & operator|= (const T &parser)
template<typename T >
main & operator|= (const T &parser)
main & style (const option_style &style)
main & style (const option_style &style)
main & style (option_style &&style)
main & style (option_style &&style)
Private Attributes
bool show_help = false
Additional Inherited Members
Protected Types inherited from lyra::arguments
enum evaluation { any = 0 , sequence = 1 , any = 0 , sequence = 1 }
enum evaluation { any = 0 , sequence = 1 , any = 0 , sequence = 1 }
Protected Types inherited from lyra::parser
using help_text = std::vector< help_text_item >
using help_text = std::vector< help_text_item >
Protected Member Functions inherited from lyra::cli
virtual std::string get_usage_text (const option_style &style) const override
virtual std::string get_usage_text (const option_style &style) const override
cli ()=default
cli ()=default
cli (const cli &other)
cli (const cli &other)
cli & add_argument (cli const &other)
cli & add_argument (cli const &other)
cli & add_argument (exe_name const &exe_name)
cli & add_argument (exe_name const &exe_name)
cli & add_argument (group const &p)
cli & add_argument (group const &p)
cli & add_argument (parser const &p)
cli & add_argument (parser const &p)
virtual std::unique_ptr< parser > clone () const override
virtual std::unique_ptr< parser > clone () const override
virtual const parser * get_named (const std::string &n) const override
virtual const parser * get_named (const std::string &n) const override
virtual const parser * get_named (const std::string &n) const override
virtual const parser * get_named (const std::string &n) const override
value_result operator[] (const std::string &n)
value_result operator[] (const std::string &n)
template<typename T >
cli operator| (T const &other) const
template<typename T >
cli operator| (T const &other) const
cli & operator|= (cli const &other)
cli & operator|= (cli const &other)
cli & operator|= (exe_name const &exe_name)
cli & operator|= (exe_name const &exe_name)
cli & operator|= (group const &p)
cli & operator|= (group const &p)
cli & operator|= (parser const &p)
cli & operator|= (parser const &p)
parse_result parse (args const &args) const
parse_result parse (args const &args) const
parse_result parse (args const &args, const option_style &style) const
parse_result parse (args const &args, const option_style &style) const
parse_result parse (args const &args, const parser_customization &customize) const
parse_result parse (args const &args, const parser_customization &customize) const
parse_result parse (detail::token_iterator const &tokens, const option_style &style) const override
parse_result parse (detail::token_iterator const &tokens, const option_style &style) const override
parse_result parse (detail::token_iterator const &tokens, const option_style &style) const override
parse_result parse (detail::token_iterator const &tokens, const option_style &style) const override
cli & style (const option_style &style)
cli & style (const option_style &style)
cli & style (option_style &&style)
cli & style (option_style &&style)
Protected Member Functions inherited from lyra::arguments
option_style get_option_style () const
option_style get_option_style () const
arguments ()=default
arguments ()=default
arguments (const arguments &other)
arguments (const arguments &other)
arguments (evaluation e)
arguments (evaluation e)
arguments & add_argument (arguments const &other)
arguments & add_argument (arguments const &other)
arguments & add_argument (parser const &p)
arguments & add_argument (parser const &p)
virtual detail::parser_cardinality cardinality () const override
virtual detail::parser_cardinality cardinality () const override
virtual std::unique_ptr< parser > clone () const override
virtual std::unique_ptr< parser > clone () const override
template<typename T >
T & get (size_t i)
template<typename T >
T & get (size_t i)
virtual std::string get_description_text (const option_style &style) const override
virtual std::string get_description_text (const option_style &style) const override
virtual help_text get_help_text (const option_style &style) const override
virtual help_text get_help_text (const option_style &style) const override
virtual const parser * get_named (const std::string &n) const override
virtual const parser * get_named (const std::string &n) const override
virtual std::string get_usage_text (const option_style &style) const override
virtual std::string get_usage_text (const option_style &style) const override
arguments & inclusive ()
arguments & inclusive ()
arguments & operator|= (arguments const &other)
arguments & operator|= (arguments const &other)
arguments & operator|= (parser const &p)
arguments & operator|= (parser const &p)
parse_result parse (detail::token_iterator const &tokens, const option_style &style) const override
parse_result parse (detail::token_iterator const &tokens, const option_style &style) const override
parse_result parse_any (detail::token_iterator const &tokens, const option_style &style) const
parse_result parse_any (detail::token_iterator const &tokens, const option_style &style) const
parse_result parse_sequence (detail::token_iterator const &tokens, const option_style &style) const
parse_result parse_sequence (detail::token_iterator const &tokens, const option_style &style) const
template<typename T >
T & print_help (T &os) const
template<typename T >
T & print_help (T &os) const
arguments & sequential ()
arguments & sequential ()
virtual result validate () const override
virtual result validate () const override
Protected Member Functions inherited from lyra::parser
virtual void print_help_text (printer &p, const option_style &style) const
virtual void print_help_text (printer &p, const option_style &style) const
virtual void print_help_text_details (printer &p, const option_style &style) const
virtual void print_help_text_details (printer &p, const option_style &style) const
virtual void print_help_text_summary (printer &p, const option_style &style) const
virtual void print_help_text_summary (printer &p, const option_style &style) const
virtual ~parser ()=default
virtual ~parser ()=default
virtual detail::parser_cardinality cardinality () const
virtual detail::parser_cardinality cardinality () const
virtual std::unique_ptr< parser > clone () const
virtual std::unique_ptr< parser > clone () const
std::string get_description_text () const
std::string get_description_text () const
virtual std::string get_description_text (const option_style &) const
virtual std::string get_description_text (const option_style &) const
help_text get_help_text () const
help_text get_help_text () const
virtual help_text get_help_text (const option_style &) const
virtual help_text get_help_text (const option_style &) const
virtual const parser * get_named (const std::string &n) const
virtual const parser * get_named (const std::string &n) const
std::string get_usage_text () const
std::string get_usage_text () const
virtual std::string get_usage_text (const option_style &) const
virtual std::string get_usage_text (const option_style &) const
virtual std::string get_value (size_t i) const
virtual std::string get_value (size_t i) const
virtual size_t get_value_count () const
virtual size_t get_value_count () const
virtual bool is_group () const
virtual bool is_group () const
virtual bool is_named (const std::string &n) const
virtual bool is_named (const std::string &n) const
bool is_optional () const
bool is_optional () const
virtual parse_result parse (detail::token_iterator const &tokens, const option_style &style) const =0
virtual parse_result parse (detail::token_iterator const &tokens, const option_style &style) const =0
virtual result validate () const
virtual result validate () const
Protected Attributes inherited from lyra::cli
exe_name m_exeName
Protected Attributes inherited from lyra::arguments
evaluation eval_mode = any
std::shared_ptr< option_style > opt_style
std::vector< std::unique_ptr< parser > > parsers
Constructor & Destructor Documentation
main() [1/2]
lyra::main::main (const std::string & text = "") inline explicit
References add_argument(), and show_help.
main() [2/2]
lyra::main::main (const std::string & text = "") explicit
Member Function Documentation
add_argument() [1/2]
template<typename T > main & lyra::main::add_argument (const T & parser)
References lyra::cli::add_argument().
Referenced by main().
add_argument() [2/2]
template<typename T > main & lyra::main::add_argument (const T & parser)
operator()() [1/10]
template<typename L > int lyra::main::operator() (const args & argv, L action)
References lyra::cli::parse(), and show_help.
operator()() [2/10]
template<typename L > int lyra::main::operator() (const args & argv, L action)
operator()() [3/10]
template<typename V > main & lyra::main::operator() (const std::string & arg_name, V && default_value)
operator()() [4/10]
template<typename V > main & lyra::main::operator() (const std::string & arg_name, V && default_value)
operator()() [5/10]
template<typename T > main & lyra::main::operator() (const T & parser)
References lyra::cli::add_argument().
operator()() [6/10]
template<typename T > main & lyra::main::operator() (const T & parser)
operator()() [7/10]
template<typename L > int lyra::main::operator() (int argc, const char ** argv, L action)
operator()() [8/10]
template<typename L > int lyra::main::operator() (int argc, const char ** argv, L action)
operator()() [9/10]
template<typename V > main & lyra::main::operator() (std::initializer_list< std::string > arg_names, V && default_value)
References lyra::cli::add_argument(), lyra::bound_parser< Derived >::help(), lyra::opt::name(), lyra::bound_parser< Derived >::optional(), and lyra::val().
operator()() [10/10]
template<typename V > main & lyra::main::operator() (std::initializer_list< std::string > arg_names, V && default_value)
operator|=() [1/2]
template<typename T > main & lyra::main::operator|= (const T & parser)
References lyra::cli::operator|=().
operator|=() [2/2]
template<typename T > main & lyra::main::operator|= (const T & parser)
style() [1/4]
main & lyra::main::style (const option_style & style) inline
References lyra::cli::style(), and style().
Referenced by style().
style() [2/4]
main & lyra::main::style (const option_style & style) inline
References lyra::cli::style(), and style().
style() [3/4]
main & lyra::main::style (option_style && style) inline
References lyra::cli::style(), and style().
style() [4/4]
main & lyra::main::style (option_style && style) inline
References lyra::cli::style(), and style().
Member Data Documentation
show_help
bool lyra::main::show_help = false private
Referenced by main(), and operator()().
The documentation for this class was generated from the following files:
Lyra/data/single_include/lyra/lyra.hpp
Lyra/include/lyra/main.hpp