???: lyra::command Class Reference
lyra::command Class Reference
#include <command.hpp>
Public Member Functions
command (const std::string &n)
command (const std::string &n)
command (const std::string &n, const std::function< void(const group &)> &f)
command (const std::string &n, const std::function< void(const group &)> &f)
template<typename P >
command & add_argument (P const &p)
template<typename P >
command & add_argument (P const &p)
command & brief_help (bool brief=true)
command & brief_help (bool brief=true)
virtual std::unique_ptr< parser > clone () const override
virtual std::unique_ptr< parser > clone () const override
virtual help_text get_help_text (const option_style &style) const override
virtual help_text get_help_text (const option_style &style) const override
virtual std::string get_usage_text (const option_style &style) const override
virtual std::string get_usage_text (const option_style &style) const override
command & help (const std::string &text)
command & help (const std::string &text)
command & operator() (std::string const &description)
command & operator() (std::string const &description)
template<typename P >
command & operator|= (P const &p)
template<typename P >
command & operator|= (P const &p)
Public Member Functions inherited from lyra::group
group ()
group ()
group (const group &other)
group (const group &other)
group (const std::function< void(const group &)> &f)
group (const std::function< void(const group &)> &f)
detail::parser_cardinality cardinality () const override
detail::parser_cardinality cardinality () const override
group & cardinality (size_t n)
group & cardinality (size_t n)
group & cardinality (size_t n, size_t m)
group & cardinality (size_t n, size_t m)
virtual std::unique_ptr< parser > clone () const override
virtual std::unique_ptr< parser > clone () const override
virtual bool is_group () const override
virtual bool is_group () const override
group & optional ()
group & optional ()
parse_result parse (detail::token_iterator const &tokens, const option_style &style) const override
parse_result parse (detail::token_iterator const &tokens, const option_style &style) const override
group & required (size_t n=1)
group & required (size_t n=1)
Public Member Functions inherited from lyra::arguments
arguments ()=default
arguments ()=default
arguments (const arguments &other)
arguments (const arguments &other)
arguments (evaluation e)
arguments (evaluation e)
arguments & add_argument (arguments const &other)
arguments & add_argument (arguments const &other)
arguments & add_argument (parser const &p)
arguments & add_argument (parser const &p)
virtual detail::parser_cardinality cardinality () const override
virtual detail::parser_cardinality cardinality () const override
virtual std::unique_ptr< parser > clone () const override
virtual std::unique_ptr< parser > clone () const override
template<typename T >
T & get (size_t i)
template<typename T >
T & get (size_t i)
virtual std::string get_description_text (const option_style &style) const override
virtual std::string get_description_text (const option_style &style) const override
virtual help_text get_help_text (const option_style &style) const override
virtual help_text get_help_text (const option_style &style) const override
virtual const parser * get_named (const std::string &n) const override
virtual const parser * get_named (const std::string &n) const override
virtual std::string get_usage_text (const option_style &style) const override
virtual std::string get_usage_text (const option_style &style) const override
arguments & inclusive ()
arguments & inclusive ()
arguments & operator|= (arguments const &other)
arguments & operator|= (arguments const &other)
arguments & operator|= (parser const &p)
arguments & operator|= (parser const &p)
parse_result parse (detail::token_iterator const &tokens, const option_style &style) const override
parse_result parse (detail::token_iterator const &tokens, const option_style &style) const override
parse_result parse_any (detail::token_iterator const &tokens, const option_style &style) const
parse_result parse_any (detail::token_iterator const &tokens, const option_style &style) const
parse_result parse_sequence (detail::token_iterator const &tokens, const option_style &style) const
parse_result parse_sequence (detail::token_iterator const &tokens, const option_style &style) const
template<typename T >
T & print_help (T &os) const
template<typename T >
T & print_help (T &os) const
arguments & sequential ()
arguments & sequential ()
virtual result validate () const override
virtual result validate () const override
Public Member Functions inherited from lyra::parser
virtual ~parser ()=default
virtual ~parser ()=default
virtual detail::parser_cardinality cardinality () const
virtual detail::parser_cardinality cardinality () const
virtual std::unique_ptr< parser > clone () const
virtual std::unique_ptr< parser > clone () const
std::string get_description_text () const
std::string get_description_text () const
virtual std::string get_description_text (const option_style &) const
virtual std::string get_description_text (const option_style &) const
help_text get_help_text () const
help_text get_help_text () const
virtual help_text get_help_text (const option_style &) const
virtual help_text get_help_text (const option_style &) const
virtual const parser * get_named (const std::string &n) const
virtual const parser * get_named (const std::string &n) const
std::string get_usage_text () const
std::string get_usage_text () const
virtual std::string get_usage_text (const option_style &) const
virtual std::string get_usage_text (const option_style &) const
virtual std::string get_value (size_t i) const
virtual std::string get_value (size_t i) const
virtual size_t get_value_count () const
virtual size_t get_value_count () const
virtual bool is_group () const
virtual bool is_group () const
virtual bool is_named (const std::string &n) const
virtual bool is_named (const std::string &n) const
bool is_optional () const
bool is_optional () const
virtual parse_result parse (detail::token_iterator const &tokens, const option_style &style) const =0
virtual parse_result parse (detail::token_iterator const &tokens, const option_style &style) const =0
virtual result validate () const
virtual result validate () const
Protected Member Functions
virtual void print_help_text_details (printer &p, const option_style &style) const override
virtual void print_help_text_details (printer &p, const option_style &style) const override
Protected Member Functions inherited from lyra::arguments
option_style get_option_style () const
option_style get_option_style () const
Protected Member Functions inherited from lyra::parser
virtual void print_help_text (printer &p, const option_style &style) const
virtual void print_help_text (printer &p, const option_style &style) const
virtual void print_help_text_details (printer &p, const option_style &style) const
virtual void print_help_text_details (printer &p, const option_style &style) const
virtual void print_help_text_summary (printer &p, const option_style &style) const
virtual void print_help_text_summary (printer &p, const option_style &style) const
Protected Attributes
bool expanded_help_details = true
Protected Attributes inherited from lyra::arguments
evaluation eval_mode = any
std::shared_ptr< option_style > opt_style
std::vector< std::unique_ptr< parser > > parsers
Additional Inherited Members
Public Types inherited from lyra::arguments
enum evaluation { any = 0 , sequence = 1 , any = 0 , sequence = 1 }
enum evaluation { any = 0 , sequence = 1 , any = 0 , sequence = 1 }
Public Types inherited from lyra::parser
using help_text = std::vector< help_text_item >
using help_text = std::vector< help_text_item >
Constructor & Destructor Documentation
command() [1/4]
lyra::command::command (const std::string & n) inline explicit
References lyra::group::group(), lyra::arguments::add_argument(), lyra::group::required(), and lyra::arguments::sequential().
command() [2/4]
lyra::command::command (const std::string & n, const std::function< void(const group &)> & f) inline
References lyra::group::group(), lyra::arguments::add_argument(), lyra::group::required(), and lyra::arguments::sequential().
command() [3/4]
lyra::command::command (const std::string & n) explicit
command() [4/4]
lyra::command::command (const std::string & n, const std::function< void(const group &)> & f)
Member Function Documentation
add_argument() [1/2]
template<typename P > command & lyra::command::add_argument (P const & p)
References add_argument().
Referenced by add_argument(), main(), and operator|=().
add_argument() [2/2]
template<typename P > command & lyra::command::add_argument (P const & p)
brief_help() [1/2]
command & lyra::command::brief_help (bool brief = true) inline
References expanded_help_details.
brief_help() [2/2]
command & lyra::command::brief_help (bool brief = true)
clone() [1/2]
virtual std::unique_ptr< parser > lyra::command::clone () const inline override virtual
Reimplemented from lyra::group.
clone() [2/2]
virtual std::unique_ptr< parser > lyra::command::clone () const inline override virtual
Reimplemented from lyra::group.
get_help_text() [1/2]
virtual help_text lyra::command::get_help_text (const option_style & style) const inline override virtual
Reimplemented from lyra::arguments.
References expanded_help_details, and lyra::arguments::parsers.
get_help_text() [2/2]
virtual help_text lyra::command::get_help_text (const option_style & style) const inline override virtual
Reimplemented from lyra::arguments.
References expanded_help_details, and lyra::arguments::parsers.
get_usage_text() [1/2]
virtual std::string lyra::command::get_usage_text (const option_style & style) const inline override virtual
Reimplemented from lyra::arguments.
References lyra::arguments::parsers.
get_usage_text() [2/2]
virtual std::string lyra::command::get_usage_text (const option_style & style) const inline override virtual
Reimplemented from lyra::arguments.
References lyra::arguments::parsers.
help() [1/2]
command & lyra::command::help (const std::string & text) inline
References help().
Referenced by help(), and operator()().
help() [2/2]
command & lyra::command::help (const std::string & text)
operator()() [1/2]
command & lyra::command::operator() (std::string const & description) inline
References help().
operator()() [2/2]
command & lyra::command::operator() (std::string const & description)
operator|=() [1/2]
template<typename P > command & lyra::command::operator|= (P const & p)
References add_argument().
operator|=() [2/2]
template<typename P > command & lyra::command::operator|= (P const & p)
print_help_text_details() [1/2]
virtual void lyra::command::print_help_text_details (printer & p, const option_style & style) const inline override protected virtual
Reimplemented from lyra::parser.
References lyra::parser::get_help_text(), lyra::printer::heading(), lyra::printer::option(), and lyra::arguments::parsers.
print_help_text_details() [2/2]
virtual void lyra::command::print_help_text_details (printer & p, const option_style & style) const inline override protected virtual
Reimplemented from lyra::parser.
References lyra::parser::get_help_text(), lyra::printer::heading(), lyra::printer::option(), and lyra::arguments::parsers.
Member Data Documentation
expanded_help_details
bool lyra::command::expanded_help_details = true protected
Referenced by brief_help(), and get_help_text().
The documentation for this class was generated from the following files:
Lyra/data/single_include/lyra/lyra.hpp
Lyra/include/lyra/command.hpp