???: MainNamespace::DH2MatrixWrapper Class Reference
MainNamespace::DH2MatrixWrapper Class Reference
#include <dh2operator.h>
Public Member Functions
DH2MatrixWrapper ()=default
DH2MatrixWrapper (DH2MatrixWrapper &&other) noexcept=default
DH2MatrixWrapper (DH2MatrixWrapper const &other)=delete
void apply (field const scale, avector const *const source, avector *const destination) const
Apply the operator to source * scale, and add the result to destination.
void applyTransposed (field const scale, avector *const source, avector *const destination) const
Apply the transposed of the operator to source * scale, and add the result to destination.
void build (helmholtz3d *const description, dcluster const *const rowCluster, dcluster const *const columnCluster, diradmdata const &admissibilityData)
Take ownership of, the pointer to the bem description and build the matrix and all needed data structures.
size_t columns () const
size_t rows () const
Private Attributes
DumbPointer< helmholtz3d > bemDescription_
BEM descriptions: information on geometry and how to construct the operators depending on the paratemers and the wave number.
DumbPointer< dblock > directionalBlock_
Root of directional block tree.
std::array< DumbPointer< dcluster >, 2 > directionalClusters_ = {nullptr, nullptr}
Roots of directional cluster trees.
DumbPointer< dh2matrix > matrix_
The matrix.
Detailed Description
Wrapper for a Directional H2 matrix and its associated data.
Constructor & Destructor Documentation
DH2MatrixWrapper() [1/3]
MainNamespace::DH2MatrixWrapper::DH2MatrixWrapper () default
DH2MatrixWrapper() [2/3]
MainNamespace::DH2MatrixWrapper::DH2MatrixWrapper (DH2MatrixWrapper const & other) delete
DH2MatrixWrapper() [3/3]
MainNamespace::DH2MatrixWrapper::DH2MatrixWrapper (DH2MatrixWrapper && other) default noexcept
Member Function Documentation
apply()
void MainNamespace::DH2MatrixWrapper::apply (field const scale, avector const *const source, avector *const destination) const
Apply the operator to source * scale, and add the result to destination.
Parameters
scale Scale.
source Input.
[out] destination Vector to add to.
References matrix_.
Referenced by MainNamespace::Surface::makeTmpApply().
applyTransposed()
void MainNamespace::DH2MatrixWrapper::applyTransposed (field const scale, avector *const source, avector *const destination) const
Apply the transposed of the operator to source * scale, and add the result to destination.
Parameters
scale Scale.
source Input. Not const because it needs to be conjugated, but this is reverted before the function returns.
[out] destination Vector to add to.
References matrix_.
Referenced by MainNamespace::Surface::makeTmpApply().
build()
void MainNamespace::DH2MatrixWrapper::build (helmholtz3d *const description, dcluster const *const rowCluster, dcluster const *const columnCluster, diradmdata const & admissibilityData)
Take ownership of, the pointer to the bem description and build the matrix and all needed data structures.
Parameters
description Data structure describing some parameters and the operator to approximate.
rowCluster Row directional cluster.
columnCluster Column directional cluster.
admissibilityData Admissibility and direction parameters.
References bemDescription_, MainNamespace::buildOperator(), MainNamespace::cloneDcluster(), directionalBlock_, directionalClusters_, MainNamespace::Logger::log(), matrix_, MainNamespace::progressBar(), and MainNamespace::Logger::yellow.
Referenced by MainNamespace::Surface::makeTmpApply().
columns()
size_t MainNamespace::DH2MatrixWrapper::columns () const
References directionalClusters_, and matrix_.
Referenced by MainNamespace::Surface::makeTmpApply().
rows()
size_t MainNamespace::DH2MatrixWrapper::rows () const
References directionalClusters_, and matrix_.
Referenced by MainNamespace::Surface::makeTmpApply().
Member Data Documentation
bemDescription_
DumbPointer<helmholtz3d> MainNamespace::DH2MatrixWrapper::bemDescription_ private
BEM descriptions: information on geometry and how to construct the operators depending on the paratemers and the wave number.
Referenced by build().
directionalBlock_
DumbPointer<dblock> MainNamespace::DH2MatrixWrapper::directionalBlock_ private
Root of directional block tree.
Referenced by build().
directionalClusters_
std::array<DumbPointer<dcluster>, 2> MainNamespace::DH2MatrixWrapper::directionalClusters_ = {nullptr, nullptr} private
Roots of directional cluster trees.
Referenced by build(), columns(), and rows().
matrix_
DumbPointer<dh2matrix> MainNamespace::DH2MatrixWrapper::matrix_ private
The matrix.
Referenced by apply(), applyTransposed(), build(), columns(), and rows().
The documentation for this class was generated from the following files:
main/dh2operator.h
main/dh2operator.cpp