???: lyra::detail::result_value_base< T > Class Template Reference
lyra::detail::result_value_base< T > Class Template Reference
#include <result.hpp>
Public Types
using value_type = T
using value_type = T
Public Member Functions
bool has_value () const
bool has_value () const
value_type const & value () const
value_type const & value () const
Public Member Functions inherited from lyra::detail::result_base
result_base const & base () const
result_base const & base () const
std::string errorMessage () const
std::string errorMessage () const
bool is_ok () const
bool is_ok () const
std::string message () const
std::string message () const
operator bool () const
operator bool () const
Protected Member Functions
result_value_base (const result_base &other)
result_value_base (const result_base &other)
result_value_base (result_kind kind, const std::string &message="")
result_value_base (result_kind kind, const std::string &message="")
result_value_base (result_kind kind, const value_type &val, const std::string &message="")
result_value_base (result_kind kind, const value_type &val, const std::string &message="")
result_value_base (result_value_base const &other)
result_value_base (result_value_base const &other)
result_value_base & operator= (result_value_base const &other)
result_value_base & operator= (result_value_base const &other)
Protected Member Functions inherited from lyra::detail::result_base
result_base (const result_base &other)
result_base (const result_base &other)
result_base (result_kind kind, const std::string &message="")
result_base (result_kind kind, const std::string &message="")
virtual ~result_base ()=default
virtual ~result_base ()=default
result_base & operator= (const result_base &)=default
result_base & operator= (const result_base &)=default
Protected Attributes
std::unique_ptr< value_type > value_
Additional Inherited Members
Protected Types inherited from lyra::detail::result_base
enum class result_kind { ok , error , ok , error }
enum class result_kind { ok , error , ok , error }
Member Typedef Documentation
value_type [1/2]
template<typename T > using lyra::detail::result_value_base< T >::value_type = T
value_type [2/2]
template<typename T > using lyra::detail::result_value_base< T >::value_type = T
Constructor & Destructor Documentation
result_value_base() [1/8]
template<typename T > lyra::detail::result_value_base< T >::result_value_base (result_kind kind, const std::string & message = "") inline explicit protected
result_value_base() [2/8]
template<typename T > lyra::detail::result_value_base< T >::result_value_base (result_kind kind, const value_type & val, const std::string & message = "") inline explicit protected
References lyra::val(), and lyra::detail::result_value_base< T >::value_.
result_value_base() [3/8]
template<typename T > lyra::detail::result_value_base< T >::result_value_base (result_value_base< T > const & other) inline explicit protected
References lyra::detail::result_value_base< T >::value_.
result_value_base() [4/8]
template<typename T > lyra::detail::result_value_base< T >::result_value_base (const result_base & other) inline explicit protected
result_value_base() [5/8]
template<typename T > lyra::detail::result_value_base< T >::result_value_base (result_kind kind, const std::string & message = "") inline explicit protected
result_value_base() [6/8]
template<typename T > lyra::detail::result_value_base< T >::result_value_base (result_kind kind, const value_type & val, const std::string & message = "") inline explicit protected
References lyra::val(), and lyra::detail::result_value_base< T >::value_.
result_value_base() [7/8]
template<typename T > lyra::detail::result_value_base< T >::result_value_base (result_value_base< T > const & other) inline explicit protected
References lyra::detail::result_value_base< T >::value_.
result_value_base() [8/8]
template<typename T > lyra::detail::result_value_base< T >::result_value_base (const result_base & other) inline explicit protected
Member Function Documentation
has_value() [1/2]
template<typename T > bool lyra::detail::result_value_base< T >::has_value () const inline
References lyra::detail::result_value_base< T >::value_.
has_value() [2/2]
template<typename T > bool lyra::detail::result_value_base< T >::has_value () const inline
References lyra::detail::result_value_base< T >::value_.
operator=() [1/2]
template<typename T > result_value_base & lyra::detail::result_value_base< T >::operator= (result_value_base< T > const & other) inline protected
References lyra::detail::result_base::operator=(), and lyra::detail::result_value_base< T >::value_.
operator=() [2/2]
template<typename T > result_value_base & lyra::detail::result_value_base< T >::operator= (result_value_base< T > const & other) inline protected
References lyra::detail::result_base::operator=(), and lyra::detail::result_value_base< T >::value_.
value() [1/2]
template<typename T > value_type const & lyra::detail::result_value_base< T >::value () const inline
References lyra::detail::result_value_base< T >::value_.
Referenced by lyra::cli::parse(), and lyra::group::parse().
value() [2/2]
template<typename T > value_type const & lyra::detail::result_value_base< T >::value () const inline
References lyra::detail::result_value_base< T >::value_.
Member Data Documentation
value_
template<typename T > std::unique_ptr< value_type > lyra::detail::result_value_base< T >::value_ protected
Referenced by lyra::detail::result_value_base< T >::result_value_base(), lyra::detail::result_value_base< T >::has_value(), lyra::detail::result_value_base< T >::operator=(), and lyra::detail::result_value_base< T >::value().
The documentation for this class was generated from the following files:
Lyra/data/single_include/lyra/lyra.hpp
Lyra/include/lyra/detail/result.hpp