???: MainNamespace::Surface::SingleSurface Class Reference
MainNamespace::Surface::SingleSurface Class Reference
#include <surface.h>
Public Member Functions
SingleSurface (const SingleSurface &other)=delete
Copy constructor would break a few things. But a copy should never be needed anyway.
SingleSurface (Mesh const &mesh, size_t const surfaceIndex, real const stiffness_p, real const density_p, MeshReader *gmshInterface)
Construct an object to manage data associated to a closed boundary.
SingleSurface (SingleSurface &&other)=default
Move constructor.
void apply (field const scaling, avector const *const source, avector *const destination) const
Apply the (scaled) Calderón operator (previously constructed) to the source vector, and add it to destination.
void buildOperator (diradmdata const &admissibilityData)
Build the operators.
std::pair< real, real > computeDifferenceNorm (avector *const solution, Functions::MeshOffset const &reference, helmholtz3d const *const parameters) const
Compute the energy error norm.
void makeMultiRhs (diradmdata const &admissibilityData, avector *const rhs)
Project the offset on the current mesh, then use it to compute the right-hand side.
void makeOffset (Functions::MeshOffset const &solution, helmholtz3d const *const parameters)
Project the offset on the current mesh.
void makeSingleRhs (avector *const rhs) const
Project the offset on the current mesh, then use it to compute the right-hand side.
void properties () const
Apply the Calderón operator to the "solution" part of source.
void scaleNeumann (avector *const traces) const
Scale the portion of the vector corresponding to the Neumann trace using the stiffness parameter.
field stabilizer () const
Getter.
field stabilizer (field const stabilizer_p)
Setter for waveNumber_ and stabilizer_.
void unscaleNeumann (avector *const traces) const
Undo the scaling of the portion of the vector corresponding to the Neumann trace using the stiffness parameter.
field waveNumber () const
Getter.
field waveNumber (field const waveNumber_p)
Setter for waveNumber_ and stabilizer_.
Private Member Functions
bool check () const
Check that the surface is a boundary.
void cleanData ()
size_t dirichletBasisSize () const
Getter.
size_t fullBasisSize () const
Getter.
surface3d const * geometry () const
Getter.
size_t neumannBasisSize () const
Getter.
void setupCluster ()
Setup cluster trees.
size_t singleSpaceSize () const
Getter.
size_t triangleDofs () const
Getter.
size_t triangles () const
Getter.
size_t vertexDofs () const
Getter.
size_t vertices () const
Getter.
Private Attributes
SlicedSpace< cluster > clusters_ = {}
Roots of nondirectional cluster trees.
real density_
Density (mass per volume) of the enclosed domain.
SlicedSpace< dcluster > directionalClusters_ = {}
Roots of directional cluster trees.
surface3d * geometry_
Reoriented surface3d object.
MeshReader * gmshInterface_ = nullptr
Interface to gmsh, mainly to write solutions.
IndexSpace< uint > indices_ = {}
Indices used in the current surface.
Mesh const & mesh_
Reference to the whole mesh.
DumbPointer< avector > offset_ = nullptr
Offset (which is multi trace hence belongs here).
Operators< DH2MatrixWrapper > operators_ = {}
Boundary operator, sliced to minimize the part to fill.
std::vector< bool > orient_
Indicates where orientation is the same in parent and current surface.
field stabilizer_
Stabilization scaling for the single layer and hypersingular operators: s:=-iκ as in ps²u - AΔu=0.
real stiffness_
Stiffness of the enclosed domain.
field waveNumber_
Wave number κ, as in the Helmholtz-type equation Δu+κ²u=0.
Detailed Description
Manage a closed surface, with its associated operators.
Todo:
expand.
Constructor & Destructor Documentation
SingleSurface() [1/3]
MainNamespace::Surface::SingleSurface::SingleSurface (Mesh const & mesh, size_t const surfaceIndex, real const stiffness_p, real const density_p, MeshReader * gmshInterface)
Construct an object to manage data associated to a closed boundary.
Parameters
mesh Global mesh.
surfaceIndex Indices of the current mesh.
stiffness_p Domain stiffness parameter.
density_p Domain density parameter.
gmshInterface Interface to gmsh, e.g., to print offset or solution.
References MainNamespace::at(), MainNamespace::DirichletData, MainNamespace::DirichletSolution, geometry_, MainNamespace::Logger::green, indices_, MainNamespace::Logger::log(), MainNamespace::Mesh::membership_, MainNamespace::Mesh::mesh_, mesh_, MainNamespace::NeumannData, MainNamespace::NeumannSolution, orient_, MainNamespace::Surface::orientCopy(), setupCluster(), MainNamespace::Mesh::triangleDofs_, MainNamespace::Mesh::triangles(), MainNamespace::Mesh::vertexDofs_, and MainNamespace::Mesh::vertices().
SingleSurface() [2/3]
MainNamespace::Surface::SingleSurface::SingleSurface (const SingleSurface & other) delete
Copy constructor would break a few things. But a copy should never be needed anyway.
SingleSurface() [3/3]
MainNamespace::Surface::SingleSurface::SingleSurface (SingleSurface && other) default
Move constructor.
Member Function Documentation
apply()
void MainNamespace::Surface::SingleSurface::apply (field const scaling, avector const *const source, avector *const destination) const
Apply the (scaled) Calderón operator (previously constructed) to the source vector, and add it to destination.
If is the current discretization of the Calderón operator, compute
Parameters
scaling .
source .
[in,out] destination .
References MainNamespace::constAt(), MainNamespace::Surface::del_const_sub_avector(), MainNamespace::Surface::flipForOrientation(), MainNamespace::Surface::new_const_sub_avector(), operators_, orient_, MainNamespace::SolutionSolutionDouble, MainNamespace::SolutionSolutionHypersingular, MainNamespace::SolutionSolutionSingle, stabilizer(), triangleDofs(), and vertexDofs().
Referenced by MainNamespace::Surface::energyNorm(), and makeSingleRhs().
buildOperator()
void MainNamespace::Surface::SingleSurface::buildOperator (diradmdata const & admissibilityData)
Build the operators.
Parameters
admissibilityData Parameters for constructing clusters.
References MainNamespace::COUNTDof, directionalClusters_, geometry(), MainNamespace::Logger::indent(), MainNamespace::interpolationPoints(), operators_, MainNamespace::operatorSpaces(), MainNamespace::quadraturePoints(), and waveNumber().
Referenced by MainNamespace::Surface::MultiSurface::solve().
check()
bool MainNamespace::Surface::SingleSurface::check () const private
Check that the surface is a boundary.
Returns
true if the geometry is a closed, oriented manifold.
References geometry(), MainNamespace::Logger::green, MainNamespace::Logger::log(), MainNamespace::Logger::red, and MainNamespace::warning().
cleanData()
void MainNamespace::Surface::SingleSurface::cleanData () inline private
< Clear all operators before constructing new ones (e.g, for a different wavenumber).
References clusters_, and directionalClusters_.
computeDifferenceNorm()
std::pair< real, real > MainNamespace::Surface::SingleSurface::computeDifferenceNorm (avector *const solution, Functions::MeshOffset const & reference, helmholtz3d const *const parameters) const
Compute the energy error norm.
Returns
The error norm of the difference between the reference solution and the approximate solution.
Parameters
solution The approximate solution vector.
reference The reference solution.
parameters Object with quadrature parameters.
References MainNamespace::at(), MainNamespace::Surface::del_const_sub_avector(), density_, MainNamespace::DirichletSolution, MainNamespace::Surface::energyNorm(), MainNamespace::MeshReader::error, gmshInterface_, MainNamespace::Logger::green, indices_, MainNamespace::Logger::log(), mesh_, MainNamespace::NeumannSolution, MainNamespace::Surface::new_const_sub_avector(), offset_, MainNamespace::reference(), MainNamespace::MeshReader::saveView(), MainNamespace::MeshReader::solution, stabilizer(), stiffness_, and vertexDofs().
dirichletBasisSize()
size_t MainNamespace::Surface::SingleSurface::dirichletBasisSize () const private
Getter.
Returns
?
References vertices().
Referenced by fullBasisSize(), and singleSpaceSize().
fullBasisSize()
size_t MainNamespace::Surface::SingleSurface::fullBasisSize () const private
Getter.
Deprecated:
References dirichletBasisSize(), and neumannBasisSize().
Referenced by makeOffset().
geometry()
surface3d const * MainNamespace::Surface::SingleSurface::geometry () const private
Getter.
Returns
A pointer to the H2Lib mesh structure.
References geometry_.
Referenced by buildOperator(), check(), makeMultiRhs(), properties(), and setupCluster().
makeMultiRhs()
void MainNamespace::Surface::SingleSurface::makeMultiRhs (diradmdata const & admissibilityData, avector *const rhs)
Project the offset on the current mesh, then use it to compute the right-hand side.
Todo:
Make const (fix orientation flip).
Parameters
admissibilityData Admissibility data
[in,out] rhs Rhs vector to add to. It must be allocated and may contain data.
References MainNamespace::Logger::cyan, directionalClusters_, MainNamespace::Surface::flipForOrientation(), geometry(), MainNamespace::interpolationPoints(), MainNamespace::Logger::log(), MainNamespace::Surface::makeTmpApply(), offset_, orient_, MainNamespace::quadraturePoints(), stabilizer(), triangleDofs(), triangles(), vertexDofs(), vertices(), and waveNumber().
Referenced by MainNamespace::Surface::MultiSurface::solve().
makeOffset()
void MainNamespace::Surface::SingleSurface::makeOffset (Functions::MeshOffset const & solution, helmholtz3d const *const parameters)
Project the offset on the current mesh.
Parameters
solution Offset function.
parameters Paratemers, like quadrature.
References MainNamespace::at(), MainNamespace::Functions::MeshOffset::c0Dirichlet(), density_, MainNamespace::DirichletData, MainNamespace::DirichletSolution, fullBasisSize(), gmshInterface_, indices_, MainNamespace::Functions::MeshOffset::l2Neumann(), mesh_, MainNamespace::NeumannData, MainNamespace::NeumannSolution, MainNamespace::MeshReader::offset, offset_, MainNamespace::MeshReader::saveView(), stabilizer(), and stiffness_.
Referenced by MainNamespace::Surface::MultiSurface::solve().
makeSingleRhs()
void MainNamespace::Surface::SingleSurface::makeSingleRhs (avector *const rhs) const
Project the offset on the current mesh, then use it to compute the right-hand side.
Parameters
[in,out] rhs Rhs vector to add to. It must be allocated and may contain data.
References apply(), MainNamespace::Logger::cyan, MainNamespace::Logger::log(), and offset_.
Referenced by MainNamespace::Surface::MultiSurface::solve().
neumannBasisSize()
size_t MainNamespace::Surface::SingleSurface::neumannBasisSize () const private
Getter.
Returns
?
References triangles().
Referenced by fullBasisSize(), and singleSpaceSize().
properties()
void MainNamespace::Surface::SingleSurface::properties () const
Apply the Calderón operator to the "solution" part of source.
Log the value of some properties in a message. Compute and report mesh properties.
References geometry(), geometry_, and MainNamespace::Logger::log().
scaleNeumann()
void MainNamespace::Surface::SingleSurface::scaleNeumann (avector *const traces) const
Scale the portion of the vector corresponding to the Neumann trace using the stiffness parameter.
Parameters
[in,out] traces The full vector of traces.
setupCluster()
void MainNamespace::Surface::SingleSurface::setupCluster () private
Setup cluster trees.
Todo:
better description
References MainNamespace::at(), MainNamespace::Surface::buildGeometricCluster(), MainNamespace::clusterResolution(), clusters_, directionalClusters_, MainNamespace::DirichletData, MainNamespace::DirichletSolution, MainNamespace::CFunctions::freeCPointer(), geometry(), MainNamespace::Logger::green, indices_, MainNamespace::Logger::log(), MainNamespace::NeumannData, MainNamespace::NeumannSolution, MainNamespace::size(), and MainNamespace::Logger::yellow.
Referenced by SingleSurface().
singleSpaceSize()
size_t MainNamespace::Surface::SingleSurface::singleSpaceSize () const private
Getter.
Returns
the size of the single trace space, including all degrees of freedom on the boundary.
References dirichletBasisSize(), and neumannBasisSize().
stabilizer() [1/2]
field MainNamespace::Surface::SingleSurface::stabilizer () const
Getter.
Returns
The (wave-type) wave number s, as in ps²u - AΔu = 0.
References stabilizer_.
Referenced by apply(), computeDifferenceNorm(), makeMultiRhs(), makeOffset(), and stabilizer().
stabilizer() [2/2]
field MainNamespace::Surface::SingleSurface::stabilizer (field const stabilizer_p)
Setter for waveNumber_ and stabilizer_.
Returns
The new value of s.
Parameters
stabilizer_p New stabilization scaling s.
References density_, stabilizer(), stabilizer_, stiffness_, and waveNumber_.
triangleDofs()
size_t MainNamespace::Surface::SingleSurface::triangleDofs () const private
Getter.
Returns
The number of triangles that are degrees of freedom in the current mesh.
References mesh_, and MainNamespace::Mesh::triangleDofs_.
Referenced by apply(), and makeMultiRhs().
triangles()
size_t MainNamespace::Surface::SingleSurface::triangles () const private
Getter.
Returns
the number of triangles in the full mesh.
References mesh_, and MainNamespace::Mesh::triangles().
Referenced by makeMultiRhs(), and neumannBasisSize().
unscaleNeumann()
void MainNamespace::Surface::SingleSurface::unscaleNeumann (avector *const traces) const
Undo the scaling of the portion of the vector corresponding to the Neumann trace using the stiffness parameter.
Parameters
[in,out] traces The full vector of traces.
vertexDofs()
size_t MainNamespace::Surface::SingleSurface::vertexDofs () const private
Getter.
Returns
The number of vertices that are degrees of freedom in the current mesh.
References mesh_, and MainNamespace::Mesh::vertexDofs_.
Referenced by apply(), computeDifferenceNorm(), and makeMultiRhs().
vertices()
size_t MainNamespace::Surface::SingleSurface::vertices () const private
Getter.
Returns
the number of vertices in the full mesh.
References mesh_, and MainNamespace::Mesh::vertices().
Referenced by dirichletBasisSize(), and makeMultiRhs().
waveNumber() [1/2]
field MainNamespace::Surface::SingleSurface::waveNumber () const
Getter.
Returns
The (Helmholtz-type) wave number κ, as in κ²u + Δu = 0.
References waveNumber_.
Referenced by buildOperator(), makeMultiRhs(), and waveNumber().
waveNumber() [2/2]
field MainNamespace::Surface::SingleSurface::waveNumber (field const waveNumber_p)
Setter for waveNumber_ and stabilizer_.
Returns
The new value of κ.
Parameters
waveNumber_p New wave number κ.
References density_, stabilizer_, stiffness_, waveNumber(), and waveNumber_.
Member Data Documentation
clusters_
SlicedSpace<cluster> MainNamespace::Surface::SingleSurface::clusters_ = {} private
Roots of nondirectional cluster trees.
Referenced by cleanData(), and setupCluster().
density_
real MainNamespace::Surface::SingleSurface::density_ private
Density (mass per volume) of the enclosed domain.
Referenced by computeDifferenceNorm(), makeOffset(), stabilizer(), and waveNumber().
directionalClusters_
SlicedSpace<dcluster> MainNamespace::Surface::SingleSurface::directionalClusters_ = {} private
Roots of directional cluster trees.
Referenced by buildOperator(), cleanData(), makeMultiRhs(), and setupCluster().
geometry_
surface3d* MainNamespace::Surface::SingleSurface::geometry_ private
Reoriented surface3d object.
Todo:
delete.
solve orientation issues first.
Referenced by SingleSurface(), geometry(), and properties().
gmshInterface_
MeshReader* MainNamespace::Surface::SingleSurface::gmshInterface_ = nullptr private
Interface to gmsh, mainly to write solutions.
Referenced by computeDifferenceNorm(), and makeOffset().
indices_
IndexSpace<uint> MainNamespace::Surface::SingleSurface::indices_ = {} private
Indices used in the current surface.
Referenced by SingleSurface(), computeDifferenceNorm(), makeOffset(), and setupCluster().
mesh_
Mesh const& MainNamespace::Surface::SingleSurface::mesh_ private
Reference to the whole mesh.
Referenced by SingleSurface(), computeDifferenceNorm(), makeOffset(), triangleDofs(), triangles(), vertexDofs(), and vertices().
offset_
DumbPointer<avector> MainNamespace::Surface::SingleSurface::offset_ = nullptr private
Offset (which is multi trace hence belongs here).
Referenced by computeDifferenceNorm(), makeMultiRhs(), makeOffset(), and makeSingleRhs().
operators_
Operators<DH2MatrixWrapper> MainNamespace::Surface::SingleSurface::operators_ = {} private
Boundary operator, sliced to minimize the part to fill.
Referenced by apply(), and buildOperator().
orient_
std::vector<bool> MainNamespace::Surface::SingleSurface::orient_ private
Indicates where orientation is the same in parent and current surface.
Referenced by SingleSurface(), apply(), and makeMultiRhs().
stabilizer_
field MainNamespace::Surface::SingleSurface::stabilizer_ private
Stabilization scaling for the single layer and hypersingular operators: s:=-iκ as in ps²u - AΔu=0.
Referenced by stabilizer(), and waveNumber().
stiffness_
real MainNamespace::Surface::SingleSurface::stiffness_ private
Stiffness of the enclosed domain.
Todo:
Should be a matrix.
Referenced by computeDifferenceNorm(), makeOffset(), stabilizer(), and waveNumber().
waveNumber_
field MainNamespace::Surface::SingleSurface::waveNumber_ private
Wave number κ, as in the Helmholtz-type equation Δu+κ²u=0.
Referenced by stabilizer(), and waveNumber().
The documentation for this class was generated from the following files:
main/surface.h
main/surface.cpp