???: lyra::ostream_printer Class Reference
lyra::ostream_printer Class Reference
#include <printer.hpp>
Public Member Functions
ostream_printer (std::ostream &os_)
ostream_printer (std::ostream &os_)
virtual printer & heading (const std::string &txt) override
virtual printer & heading (const std::string &txt) override
virtual printer & option (const std::string &opt, const std::string &description, std::size_t indent=0) override
virtual printer & option (const std::string &opt, const std::string &description, std::size_t indent=0) override
virtual printer & paragraph (const std::string &txt, std::size_t indent=0) override
virtual printer & paragraph (const std::string &txt, std::size_t indent=0) override
Public Member Functions inherited from lyra::printer
virtual ~printer ()=default
virtual ~printer ()=default
virtual printer & heading (const std::string &txt)=0
virtual printer & heading (const std::string &txt)=0
virtual printer & option (const std::string &opt, const std::string &description, std::size_t indent=0)=0
virtual printer & option (const std::string &opt, const std::string &description, std::size_t indent=0)=0
virtual printer & paragraph (const std::string &txt, std::size_t indent=0)=0
virtual printer & paragraph (const std::string &txt, std::size_t indent=0)=0
Protected Attributes
std::ostream & os
Constructor & Destructor Documentation
ostream_printer() [1/2]
lyra::ostream_printer::ostream_printer (std::ostream & os_) inline explicit
ostream_printer() [2/2]
lyra::ostream_printer::ostream_printer (std::ostream & os_) inline explicit
Member Function Documentation
heading() [1/2]
virtual printer & lyra::ostream_printer::heading (const std::string & txt) inline override virtual
Implements lyra::printer.
References os.
heading() [2/2]
virtual printer & lyra::ostream_printer::heading (const std::string & txt) inline override virtual
Implements lyra::printer.
References os.
option() [1/2]
virtual printer & lyra::ostream_printer::option (const std::string & opt, const std::string & description, std::size_t indent = 0) inline override virtual
Implements lyra::printer.
References MainNamespace::Logger::indent(), and os.
option() [2/2]
virtual printer & lyra::ostream_printer::option (const std::string & opt, const std::string & description, std::size_t indent = 0) inline override virtual
Implements lyra::printer.
References MainNamespace::Logger::indent(), and os.
paragraph() [1/2]
virtual printer & lyra::ostream_printer::paragraph (const std::string & txt, std::size_t indent = 0) inline override virtual
Implements lyra::printer.
References MainNamespace::Logger::indent(), and os.
paragraph() [2/2]
virtual printer & lyra::ostream_printer::paragraph (const std::string & txt, std::size_t indent = 0) inline override virtual
Implements lyra::printer.
References MainNamespace::Logger::indent(), and os.
Member Data Documentation
os
std::ostream & lyra::ostream_printer::os protected
Referenced by heading(), option(), and paragraph().
The documentation for this class was generated from the following files:
Lyra/data/single_include/lyra/lyra.hpp
Lyra/include/lyra/printer.hpp