???: lyra::detail::parse_state Class Reference
lyra::detail::parse_state Class Reference
#include <parser.hpp>
Public Member Functions
parse_state (parser_result_type type, token_iterator const &remaining_tokens, size_t parsed_tokens=0)
parse_state (parser_result_type type, token_iterator const &remaining_tokens, size_t parsed_tokens=0)
bool have_tokens () const
bool have_tokens () const
token_iterator remainingTokens () const
token_iterator remainingTokens () const
parser_result_type type () const
parser_result_type type () const
Private Attributes
parser_result_type result_type
token_iterator tokens
Constructor & Destructor Documentation
parse_state() [1/2]
lyra::detail::parse_state::parse_state (parser_result_type type, token_iterator const & remaining_tokens, size_t parsed_tokens = 0) inline
parse_state() [2/2]
lyra::detail::parse_state::parse_state (parser_result_type type, token_iterator const & remaining_tokens, size_t parsed_tokens = 0) inline
Member Function Documentation
have_tokens() [1/2]
bool lyra::detail::parse_state::have_tokens () const inline
References tokens.
Referenced by lyra::cli::parse().
have_tokens() [2/2]
bool lyra::detail::parse_state::have_tokens () const inline
References tokens.
remainingTokens() [1/2]
token_iterator lyra::detail::parse_state::remainingTokens () const inline
References tokens.
Referenced by lyra::cli::parse().
remainingTokens() [2/2]
token_iterator lyra::detail::parse_state::remainingTokens () const inline
References tokens.
type() [1/2]
parser_result_type lyra::detail::parse_state::type () const inline
References result_type.
Referenced by lyra::cli::parse(), and lyra::group::parse().
type() [2/2]
parser_result_type lyra::detail::parse_state::type () const inline
References result_type.
Member Data Documentation
result_type
parser_result_type lyra::detail::parse_state::result_type private
Referenced by type().
tokens
token_iterator lyra::detail::parse_state::tokens private
Referenced by have_tokens(), and remainingTokens().
The documentation for this class was generated from the following files:
Lyra/data/single_include/lyra/lyra.hpp
Lyra/include/lyra/parser.hpp