???: lyra::group Class Reference
lyra::group Class Reference
#include <group.hpp>
Public Member Functions
group ()
group ()
group (const group &other)
group (const group &other)
group (const std::function< void(const group &)> &f)
group (const std::function< void(const group &)> &f)
detail::parser_cardinality cardinality () const override
detail::parser_cardinality cardinality () const override
group & cardinality (size_t n)
group & cardinality (size_t n)
group & cardinality (size_t n, size_t m)
group & cardinality (size_t n, size_t m)
virtual std::unique_ptr< parser > clone () const override
virtual std::unique_ptr< parser > clone () const override
virtual bool is_group () const override
virtual bool is_group () const override
group & optional ()
group & optional ()
parse_result parse (detail::token_iterator const &tokens, const option_style &style) const override
parse_result parse (detail::token_iterator const &tokens, const option_style &style) const override
group & required (size_t n=1)
group & required (size_t n=1)
Public Member Functions inherited from lyra::arguments
arguments ()=default
arguments ()=default
arguments (const arguments &other)
arguments (const arguments &other)
arguments (evaluation e)
arguments (evaluation e)
arguments & add_argument (arguments const &other)
arguments & add_argument (arguments const &other)
arguments & add_argument (parser const &p)
arguments & add_argument (parser const &p)
virtual detail::parser_cardinality cardinality () const override
virtual detail::parser_cardinality cardinality () const override
virtual std::unique_ptr< parser > clone () const override
virtual std::unique_ptr< parser > clone () const override
template<typename T >
T & get (size_t i)
template<typename T >
T & get (size_t i)
virtual std::string get_description_text (const option_style &style) const override
virtual std::string get_description_text (const option_style &style) const override
virtual help_text get_help_text (const option_style &style) const override
virtual help_text get_help_text (const option_style &style) const override
virtual const parser * get_named (const std::string &n) const override
virtual const parser * get_named (const std::string &n) const override
virtual std::string get_usage_text (const option_style &style) const override
virtual std::string get_usage_text (const option_style &style) const override
arguments & inclusive ()
arguments & inclusive ()
arguments & operator|= (arguments const &other)
arguments & operator|= (arguments const &other)
arguments & operator|= (parser const &p)
arguments & operator|= (parser const &p)
parse_result parse (detail::token_iterator const &tokens, const option_style &style) const override
parse_result parse (detail::token_iterator const &tokens, const option_style &style) const override
parse_result parse_any (detail::token_iterator const &tokens, const option_style &style) const
parse_result parse_any (detail::token_iterator const &tokens, const option_style &style) const
parse_result parse_sequence (detail::token_iterator const &tokens, const option_style &style) const
parse_result parse_sequence (detail::token_iterator const &tokens, const option_style &style) const
template<typename T >
T & print_help (T &os) const
template<typename T >
T & print_help (T &os) const
arguments & sequential ()
arguments & sequential ()
virtual result validate () const override
virtual result validate () const override
Public Member Functions inherited from lyra::parser
virtual ~parser ()=default
virtual ~parser ()=default
virtual detail::parser_cardinality cardinality () const
virtual detail::parser_cardinality cardinality () const
virtual std::unique_ptr< parser > clone () const
virtual std::unique_ptr< parser > clone () const
std::string get_description_text () const
std::string get_description_text () const
virtual std::string get_description_text (const option_style &) const
virtual std::string get_description_text (const option_style &) const
help_text get_help_text () const
help_text get_help_text () const
virtual help_text get_help_text (const option_style &) const
virtual help_text get_help_text (const option_style &) const
virtual const parser * get_named (const std::string &n) const
virtual const parser * get_named (const std::string &n) const
std::string get_usage_text () const
std::string get_usage_text () const
virtual std::string get_usage_text (const option_style &) const
virtual std::string get_usage_text (const option_style &) const
virtual std::string get_value (size_t i) const
virtual std::string get_value (size_t i) const
virtual size_t get_value_count () const
virtual size_t get_value_count () const
virtual bool is_group () const
virtual bool is_group () const
virtual bool is_named (const std::string &n) const
virtual bool is_named (const std::string &n) const
bool is_optional () const
bool is_optional () const
virtual parse_result parse (detail::token_iterator const &tokens, const option_style &style) const =0
virtual parse_result parse (detail::token_iterator const &tokens, const option_style &style) const =0
virtual result validate () const
virtual result validate () const
Private Attributes
detail::parser_cardinality m_cardinality = { 0, 1 }
std::function< void(const group &)> success_signal
Additional Inherited Members
Public Types inherited from lyra::arguments
enum evaluation { any = 0 , sequence = 1 , any = 0 , sequence = 1 }
enum evaluation { any = 0 , sequence = 1 , any = 0 , sequence = 1 }
Public Types inherited from lyra::parser
using help_text = std::vector< help_text_item >
using help_text = std::vector< help_text_item >
Protected Member Functions inherited from lyra::arguments
option_style get_option_style () const
option_style get_option_style () const
Protected Member Functions inherited from lyra::parser
virtual void print_help_text (printer &p, const option_style &style) const
virtual void print_help_text (printer &p, const option_style &style) const
virtual void print_help_text_details (printer &p, const option_style &style) const
virtual void print_help_text_details (printer &p, const option_style &style) const
virtual void print_help_text_summary (printer &p, const option_style &style) const
virtual void print_help_text_summary (printer &p, const option_style &style) const
Protected Attributes inherited from lyra::arguments
evaluation eval_mode = any
std::shared_ptr< option_style > opt_style
std::vector< std::unique_ptr< parser > > parsers
Constructor & Destructor Documentation
group() [1/6]
lyra::group::group () inline
Referenced by lyra::command::command().
group() [2/6]
lyra::group::group (const group & other) inline
group() [3/6]
lyra::group::group (const std::function< void(const group &)> & f) inline explicit
group() [4/6]
lyra::group::group ()
group() [5/6]
lyra::group::group (const group & other)
group() [6/6]
lyra::group::group (const std::function< void(const group &)> & f) explicit
Member Function Documentation
cardinality() [1/6]
detail::parser_cardinality lyra::group::cardinality () const inline override virtual
Reimplemented from lyra::arguments.
References m_cardinality.
cardinality() [2/6]
detail::parser_cardinality lyra::group::cardinality () const inline override virtual
Reimplemented from lyra::arguments.
References m_cardinality.
cardinality() [3/6]
group & lyra::group::cardinality (size_t n) inline
References lyra::detail::parser_cardinality::counted(), and m_cardinality.
cardinality() [4/6]
group & lyra::group::cardinality (size_t n)
cardinality() [5/6]
group & lyra::group::cardinality (size_t n, size_t m) inline
References lyra::detail::parser_cardinality::bounded(), and m_cardinality.
cardinality() [6/6]
group & lyra::group::cardinality (size_t n, size_t m)
clone() [1/2]
virtual std::unique_ptr< parser > lyra::group::clone () const inline override virtual
Reimplemented from lyra::arguments.
Reimplemented in lyra::command, and lyra::command.
clone() [2/2]
virtual std::unique_ptr< parser > lyra::group::clone () const inline override virtual
Reimplemented from lyra::arguments.
Reimplemented in lyra::command, and lyra::command.
is_group() [1/2]
virtual bool lyra::group::is_group () const inline override virtual
Reimplemented from lyra::parser.
is_group() [2/2]
virtual bool lyra::group::is_group () const inline override virtual
Reimplemented from lyra::parser.
optional() [1/2]
group & lyra::group::optional () inline
References m_cardinality, and lyra::detail::parser_cardinality::optional().
optional() [2/2]
group & lyra::group::optional ()
parse() [1/2]
parse_result lyra::group::parse (detail::token_iterator const & tokens, const option_style & style) const inline override virtual
Reimplemented from lyra::arguments.
References lyra::detail::token_iterator::argument(), lyra::parser::get_usage_text(), LYRA_PRINT_DEBUG, LYRA_PRINT_SCOPE, lyra::detail::token::name, lyra::no_match, lyra::arguments::parse(), success_signal, lyra::detail::parse_state::type(), and lyra::detail::result_value_base< T >::value().
parse() [2/2]
parse_result lyra::group::parse (detail::token_iterator const & tokens, const option_style & style) const inline override virtual
Reimplemented from lyra::arguments.
References lyra::detail::token_iterator::argument(), lyra::parser::get_usage_text(), LYRA_PRINT_DEBUG, LYRA_PRINT_SCOPE, lyra::detail::token::name, lyra::no_match, lyra::arguments::parse(), success_signal, lyra::detail::parse_state::type(), and lyra::detail::result_value_base< T >::value().
required() [1/2]
group & lyra::group::required (size_t n = 1) inline
References m_cardinality, and lyra::detail::parser_cardinality::required().
Referenced by lyra::command::command().
required() [2/2]
group & lyra::group::required (size_t n = 1)
Member Data Documentation
m_cardinality
detail::parser_cardinality lyra::group::m_cardinality = { 0, 1 } private
Referenced by cardinality(), optional(), and required().
success_signal
std::function< void(const group &)> lyra::group::success_signal private
Referenced by parse().
The documentation for this class was generated from the following files:
Lyra/data/single_include/lyra/lyra.hpp
Lyra/include/lyra/group.hpp