???: MainNamespace::Surface Namespace Reference
MainNamespace::Surface Namespace Reference
Classes
class MultiSurface
Representation of a boundary.
class SingleSurface
Typedefs
using ChildConstFunction = std::function< void(SingleSurface const &)>
using ChildFunction = std::function< void(SingleSurface &)>
using ErrorVector = real
A list of errors, computed in different ways.
typedef helmholtz3d(* helmholtzConstructor) (surface3d const *gr, field kappa, uint nq, uint ni)
using Result = std::pair< size_t, ErrorVector >
The numerically relevant result: number of GMRES iterations, and list of errors.
typedef void(* StepFunction) (field, void const *, avector const *const, avector *const)
Functions
static cluster * buildGeometricCluster (clustergeometry *const geometry, std::vector< uint > &indices)
static surface3d * copySurface (surface3d const *const surface)
static void del_const_sub_avector (avector const *vector)
constexpr uint dirichletOffset (size_t const dim)
static std::pair< size_t, avector * > doGmres (avector const *const rhs, StepFunction const stepFunction, void const *const data)
static real energyNorm (avector const *const vector, SingleSurface const *const operators,field const waveNumber)
static void flipForOrientation (std::vector< bool > const orientation, avector *const vector, size_t const offset=0)
static void forwardChildren (MultiSurface::Children &children, ChildFunction function)
static void forwardChildrenC (MultiSurface::Children const &children, ChildConstFunction function)
static void getFromFile (std::string const filename, MeshReader &meshReader)
static void makeTmpApply (field const scaling, helmholtz3d *const description, dcluster const *const rowCluster, dcluster const *const columnCluster, diradmdata const &admissibilityData, avector *const source, avector *const destination, bool const transpose=false)
constexpr uint neumannOffset (const size_t dim)
static avector const * new_const_sub_avector (avector const *const vector, uint const dim, uint const off)
surface3d * orientCopy (surface3d const *const surface, OrientingInfo const &correct)
Reorient all needed triangles by swapping two vertices.
Variables
static constexpr size_t gmresMaxIterations = 20000
static constexpr real kdensity [] = {1,5}
static constexpr real kstiffness [] = {1,1}
Typedef Documentation
ChildConstFunction
using MainNamespace::Surface::ChildConstFunction = typedef std::function<void(SingleSurface const &)>
ChildFunction
using MainNamespace::Surface::ChildFunction = typedef std::function<void(SingleSurface &)>
ErrorVector
using MainNamespace::Surface::ErrorVector = typedef real
A list of errors, computed in different ways.
helmholtzConstructor
typedef helmholtz3d(* MainNamespace::Surface::helmholtzConstructor) (surface3d const *gr, field kappa, uint nq, uint ni)
Result
using MainNamespace::Surface::Result = typedef std::pair<size_t, ErrorVector>
The numerically relevant result: number of GMRES iterations, and list of errors.
StepFunction
typedef void(* MainNamespace::Surface::StepFunction) (field, void const *, avector const *const, avector *const)
Function Documentation
buildGeometricCluster()
static cluster * MainNamespace::Surface::buildGeometricCluster (clustergeometry *const geometry, std::vector< uint > & indices) inline static
Construct a cluster from options and the given parameters.
Returns
A pointer to the new cluster.
Parameters
geometry Cluster geometry to use for the current cluster.
indices Indices to use for all slices.
References MainNamespace::clusterResolution().
Referenced by MainNamespace::Surface::SingleSurface::setupCluster().
copySurface()
static surface3d * MainNamespace::Surface::copySurface (surface3d const *const surface) static
Copy a surface3d object.
Returns
A copy of surface.
Parameters
surface Surface to copy.
References MainNamespace::copy().
Referenced by orientCopy().
del_const_sub_avector()
static void MainNamespace::Surface::del_const_sub_avector (avector const * vector) inline static
Delete a constant vector, using const_cast.
Warning
This is intended for views only, not for vectors owning their elements.
Todo:
Check that the vector actually doesn't have ownership.
Parameters
vector Consant view to delete.
Referenced by MainNamespace::Surface::SingleSurface::apply(), and MainNamespace::Surface::SingleSurface::computeDifferenceNorm().
dirichletOffset()
constexpr uint MainNamespace::Surface::dirichletOffset (size_t const dim) inline constexpr
doGmres()
static std::pair< size_t, avector * > MainNamespace::Surface::doGmres (avector const *const rhs, StepFunction const stepFunction, void const *const data) static
Solve the linear system with right-hand side rhs and matrix-vector product given by stepFunction.
Returns
Number of iterations and solution.
Parameters
rhs Right-hand side of the linear system.
stepFunction Pointer to a function performing the matrix-vector product.
data Additional input to stepFunction holding data needed for the evaluation (currently a pointer to MultiSurface).
References MainNamespace::dimKrylov(), MainNamespace::epsKrylov(), gmresMaxIterations, MainNamespace::Logger::green, MainNamespace::Logger::log(), MainNamespace::Logger::red, MainNamespace::startTiming(), MainNamespace::stopTiming(), and MainNamespace::warning().
Referenced by MainNamespace::Surface::MultiSurface::solve().
energyNorm()
static real MainNamespace::Surface::energyNorm (avector const *const vector, SingleSurface const *const operators, field const waveNumber) static
Approximate the energy norm of vector.
Parameters
vector Solution vector. Only the first component, corresponding to single trace degrees of freedom, are considered.
operators Object capable of applying the Calderón operator.
waveNumber Wave number.
References MainNamespace::Surface::SingleSurface::apply(), MainNamespace::Logger::blue, and MainNamespace::Logger::log().
Referenced by MainNamespace::Surface::SingleSurface::computeDifferenceNorm().
flipForOrientation()
static void MainNamespace::Surface::flipForOrientation (std::vector< bool > const orientation, avector *const vector, size_t const offset = 0) static
Flip the coefficients of some "Neumann data" to change the orientation between global and local.
Parameters
orientation Orientation of all triangles; true if correct.
vector Vector of coefficients to reorient.
offset Only start to flip from the index offset.
Referenced by MainNamespace::Surface::SingleSurface::apply(), and MainNamespace::Surface::SingleSurface::makeMultiRhs().
forwardChildren()
static void MainNamespace::Surface::forwardChildren (MultiSurface::Children & children, ChildFunction function) static
Apply the function to all children.
Parameters
children Children list.
function Function to apply to all children.
Referenced by MainNamespace::Surface::MultiSurface::solve().
forwardChildrenC()
static void MainNamespace::Surface::forwardChildrenC (MultiSurface::Children const & children, ChildConstFunction function) static
Apply the (constant) function to all children.
Parameters
children Children (constant) list.
function Function to apply to all (constant) children.
Referenced by MainNamespace::Surface::MultiSurface::solve().
getFromFile()
static void MainNamespace::Surface::getFromFile (std::string const filename, MeshReader & meshReader) static
Load the mesh from a given file.
Parameters
filename Name of the mesh file.
[out] meshReader Gmsh interface object. Is modified, as it saves the elements permutations.
References MainNamespace::Logger::deindent(), MainNamespace::Logger::green, MainNamespace::Logger::indent(), MainNamespace::Logger::log(), MainNamespace::MeshReader::mesh(), MainNamespace::Mesh::mesh_, MainNamespace::MeshReader::parseMesh(), MainNamespace::Logger::red, MainNamespace::Mesh::triangleDofs_, MainNamespace::Mesh::triangles(), MainNamespace::Mesh::vertexDofs_, MainNamespace::Mesh::vertices(), and MainNamespace::warning().
Referenced by MainNamespace::Surface::MultiSurface::MultiSurface().
makeTmpApply()
static void MainNamespace::Surface::makeTmpApply (field const scaling, helmholtz3d *const description, dcluster const *const rowCluster, dcluster const *const columnCluster, diradmdata const & admissibilityData, avector *const source, avector *const destination, bool const transpose = false) static
Costruct a disposable directional matrix and apply it.
Parameters
scaling Scaling for the operator.
description Data structure describing some parameters and the operator to approximate.
rowCluster Row directional cluster.
columnCluster Column directional cluster.
admissibilityData Admissibility and direction parameters.
source Input.
[in,out] destination output, but add to it instead of replacing.
transpose Whether to transpose the operator before applying it.
References MainNamespace::DH2MatrixWrapper::apply(), MainNamespace::DH2MatrixWrapper::applyTransposed(), MainNamespace::DH2MatrixWrapper::build(), MainNamespace::DH2MatrixWrapper::columns(), MainNamespace::Logger::green, MainNamespace::Logger::log(), and MainNamespace::DH2MatrixWrapper::rows().
Referenced by MainNamespace::Surface::SingleSurface::makeMultiRhs().
neumannOffset()
constexpr uint MainNamespace::Surface::neumannOffset (const size_t dim) inline constexpr
new_const_sub_avector()
static avector const * MainNamespace::Surface::new_const_sub_avector (avector const *const vector, uint const dim, uint const off) inline static
Take a view of a constant avector.
Returns
Constant view.
Parameters
vector Owner vector.
dim Dimension of the view.
off Offset to start the view.
Referenced by MainNamespace::Surface::SingleSurface::apply(), and MainNamespace::Surface::SingleSurface::computeDifferenceNorm().
orientCopy()
surface3d * MainNamespace::Surface::orientCopy (surface3d const *const surface, OrientingInfo const & correct)
Reorient all needed triangles by swapping two vertices.
Returns
A correctly oriented copy of surface.
Parameters
surface Surface to orient.
correct Orientation of all triangles (positive if correct).
References MainNamespace::copy(), and copySurface().
Referenced by MainNamespace::Surface::SingleSurface::SingleSurface().
Variable Documentation
gmresMaxIterations
constexpr size_t MainNamespace::Surface::gmresMaxIterations = 20000 static constexpr
Referenced by doGmres().
kdensity
constexpr real MainNamespace::Surface::kdensity[] = {1,5} static
Referenced by MainNamespace::Surface::MultiSurface::MultiSurface().
kstiffness
constexpr real MainNamespace::Surface::kstiffness[] = {1,1} static constexpr
Referenced by MainNamespace::Surface::MultiSurface::MultiSurface().