???: lyra::detail Namespace Reference
lyra::detail Namespace Reference
Classes
class basic_result
class basic_result< void >
class basic_token_name
struct BoundFlagLambda
struct BoundFlagRef
struct BoundFlagRefBase
struct BoundLambda
struct BoundRef
struct BoundVal
struct BoundValueRef
struct BoundValueRef< std::vector< T > >
struct BoundValueRefBase
struct choices_base
struct choices_check
struct choices_set
struct choices_set< const char * >
struct is_callable
struct is_convertible_from_string
struct is_convertible_from_string< T, typename std::enable_if< std::is_arithmetic< T >::value >::type >
struct is_convertible_from_string< T, typename std::enable_if< std::is_same< T, bool >::value >::type >
struct is_invocable
struct is_specialization_of
struct is_specialization_of< Primary< Args... >, Primary >
struct LambdaInvoker
struct LambdaInvoker< void >
struct make_void
struct NonCopyable
class parse_state
struct parser_cardinality
struct remove_cvref
class result_base
class result_value_base
class result_value_base< void >
struct token
class token_iterator
struct unary_lambda_traits
struct unary_lambda_traits< ReturnT(ClassT::*)(Args...) const >
struct unary_lambda_traits< ReturnT(ClassT::*)(ArgT) const >
struct validate_from_string
struct validate_from_string< T, typename std::enable_if< std::is_integral< typename detail::remove_cvref< T >::type >::value &&std::is_signed< typename detail::remove_cvref< T >::type >::value >::type >
struct validate_from_string< T, typename std::enable_if< std::is_unsigned< typename detail::remove_cvref< T >::type >::value >::type >
Typedefs
using token_name = std::string
template<typename... Ts>
using valid_t = typename make_void< Ts... >::type
Enumerations
enum class token_type {
unknown , option , argument , unknown ,
option , argument
}
enum class token_type {
unknown , option , argument , unknown ,
option , argument
}
Functions
template<typename S >
bool from_string (S const &source, bool &target)
template<typename S , typename... C>
bool from_string (S const &source, std::basic_string< C... > &target)
template<typename S , typename T >
bool from_string (S const &source, T &target)
template<typename ArgType , typename L >
parser_result invokeLambda (L const &lambda, std::string const &arg)
template<typename S , typename T >
parser_result parse_string (S const &source, T &target)
bool to_string (bool source, std::string &target)
bool to_string (const char *source, std::string &target)
bool to_string (const std::string &source, std::string &target)
template<typename T >
bool to_string (const T &source, std::string &target)
template<typename T >
std::string to_string (T &&t)
Variables
constexpr bool is_debug = LYRA_DEBUG
Typedef Documentation
token_name
typedef std::string lyra::detail::token_name
valid_t
template<typename... Ts> using lyra::detail::valid_t = typedef typename make_void<Ts...>::type
Enumeration Type Documentation
token_type [1/2]
enum class lyra::detail::token_type strong
Enumerator
unknown
option
argument
unknown
option
argument
token_type [2/2]
enum class lyra::detail::token_type strong
Enumerator
unknown
option
argument
unknown
option
argument
Function Documentation
from_string() [1/3]
template<typename S > bool lyra::detail::from_string (S const & source, bool & target) inline
References to_string().
from_string() [2/3]
template<typename S , typename... C> bool lyra::detail::from_string (S const & source, std::basic_string< C... > & target) inline
References to_string().
from_string() [3/3]
template<typename S , typename T > bool lyra::detail::from_string (S const & source, T & target) inline
Referenced by lyra::cli::value_result::operator std::vector< T >(), lyra::cli::value_result::operator T(), and parse_string().
invokeLambda()
template<typename ArgType , typename L > parser_result lyra::detail::invokeLambda (L const & lambda, std::string const & arg) inline
References parse_string().
parse_string()
template<typename S , typename T > parser_result lyra::detail::parse_string (S const & source, T & target)
References lyra::detail::basic_result< T >::error(), from_string(), lyra::matched, lyra::no_match, and lyra::detail::basic_result< T >::ok().
Referenced by lyra::detail::choices_set< T >::contains_value(), lyra::detail::choices_check< Lambda >::contains_value(), invokeLambda(), lyra::detail::BoundValueRef< T >::setValue(), and lyra::detail::BoundValueRef< std::vector< T > >::setValue().
to_string() [1/5]
bool lyra::detail::to_string (bool source, std::string & target) inline
to_string() [2/5]
bool lyra::detail::to_string (const char * source, std::string & target) inline
to_string() [3/5]
bool lyra::detail::to_string (const std::string & source, std::string & target) inline
to_string() [4/5]
template<typename T > bool lyra::detail::to_string (const T & source, std::string & target)
to_string() [5/5]
template<typename T > std::string lyra::detail::to_string (T && t)
Referenced by from_string(), lyra::detail::BoundValueRef< T >::get_value(), lyra::detail::BoundValueRef< std::vector< T > >::get_value(), MainNamespace::info(), MainNamespace::Clocks::readAll(), bfg::mini_test::test_main(), test_val(), and lyra::detail::choices_set< T >::to_string().
Variable Documentation
is_debug
constexpr bool lyra::detail::is_debug = LYRA_DEBUG constexpr