???: MainNamespace Namespace Reference
MainNamespace Namespace Reference
Namespaces
namespace anonymous_namespace{options.cpp}
namespace CFunctions
namespace Functions
namespace Logger
namespace ReporterHelper
namespace Surface
Classes
struct AdmissibilityParameters
class BaseTimer
class BoermTimer
class Clocks
class CpuTimer
class DH2MatrixWrapper
class DumbPointer
struct Mesh
class MeshReader
struct Options
class PointerArray
Concepts
concept Enum
Typedefs
template<class Type >
using constPointer = std::conditional_t< std::is_pointer_v< Type >, std::add_const_t< std::add_pointer_t< std::add_const_t< std::remove_pointer_t< Type > > > >, std::add_const_t< Type > >
template<class Objects >
using IndexSpace = std::array< std::vector< Objects >, size< SpaceSlices >()>
Type for an array with indices information.
template<class Objects >
using Operators = std::array< Objects, size< OperatorSlices >()>
Type for an array with all slices of some operator-related object.
template<class Type >
using pointerOrReference = std::conditional_t< std::is_pointer_v< Type >, Type, std::conditional< std::is_reference_v< Type >, Type, std::add_lvalue_reference_t< Type > > >
template<class Objects >
using SlicedOperator = PointerArray< Objects, size< OperatorSlices >()>
Type for an array with pointers to all slices of some operator-related object.
template<class Objects >
using SlicedSpace = PointerArray< Objects, size< SpaceSlices >()>
Type for an array with pointers to all slices of some space-related object.
template<typename Field >
using SpaceVector = std::array< Field, spaceDimension >
Vectors on spaceDimension dimensional vector space on the field Field.
using SurfaceList = std::map< std::string, Mesh::MembershipVector >
List of surfaces (as pairs (name, membership)).
Enumerations
enum class DataOperator {
DataSolutionSingle = 0 , DataSolutionDouble , SolutionDataDouble , DataSolutionHypersingular ,
COUNT
}
enum class DataSpaces { Dirichlet = 0 , Neumann , COUNT }
enum class OperatorSlices {
SolutionSolutionSingle = 0 , SolutionSolutionDouble , SolutionSolutionHypersingular , DataSolutionSingle ,
COUNTDof = DataSolutionSingle , DataSolutionDouble , SolutionDataDouble , DataSolutionHypersingular ,
COUNT
}
enum class SpaceSlices {
DirichletSolution = 0 , DirichletData , NeumannSolution , NeumannData ,
COUNT
}
enum Type { edgesIdx = 0 , trianglesIdx , nodesIdx }
Functions
template<class Enumerator , class BaseValues , size_t length>
BaseValues & at (std::array< BaseValues, length > &array, Enumerator const idx)
template<class BaseValues , size_t length>
BaseValues & at (std::array< BaseValues, length > *const array, size_t const idx)
template<class Enumerator , class BaseValues , size_t length>
BaseValues at (std::array< BaseValues, length > const &array, Enumerator const idx)
template<class BaseValues , size_t length>
BaseValues at (std::array< BaseValues, length > const *const array, size_t const idx)
template<class BaseValues , size_t length, class ConstValues = std::add_const_t<BaseValues>>
BaseValues at (std::array< ConstValues, length > const *const array, size_t const idx)
static dclusteroperator * buildImplicitClusterBasis (helmholtz3d *const bm, dcluster const *const root, leaf_func_t leaf, size_t const dofs)
dh2matrix * buildOperator (std::array< DumbPointer< dcluster >, 2 > &directionalClusters, DumbPointer< dblock > &directionalBlock, diradmdata const &directions, helmholtz3d *const bemDescription)
Build a dh2matrix for the operator described by bemDescription, using the given clusters.
static surface3d * buildSurface (std::vector< size_t > const &reordering, std::vector< double > const &nodes, std::vector< size_t > const &edgesInTriangle, std::vector< size_t > const &edgeTags, std::vector< size_t > const &triangles, std::vector< size_t > const &nodeTags)
double bytes2KB (size_t const bytes)
double bytes2MB (size_t const bytes)
static dcluster * cloneDcluster (dcluster const *const other)
size_t clusterResolution ()
bool compression ()
static dh2matrix * compressRowColumnFar (dblock const *const root, helmholtz3d *const bemDescription, dclusteroperator const *const rowCluster, dclusteroperator const *const columnCluster, truncmode const *const trMode)
template<class Enumerator , class BaseValues , size_t length, class ConstValues = std::add_const_t<BaseValues>>
ConstValues & constAt (std::array< BaseValues, length > const &array, Enumerator const idx)
template<class BaseValues , size_t length, class ConstValues = std::add_const_t<BaseValues>>
ConstValues & constAt (std::array< BaseValues, length > const *const array, size_t const idx)
static void copy (diradmdata const &data, diradmdata &destination)
std::string copyrightNotice ()
Library copyright notice.
template<Enum Enumerator>
constexpr std::underlying_type_t< Enumerator > count ()
reporter * createFakeProgressBar ()
reporter * createProgressBar ()
stopwatch * createStopWatch ()
Options * delOptions ()
size_t dimKrylov ()
real eps ()
real epsKrylov ()
static void getElements (std::array< std::vector< size_t >, 3 > &tags, std::vector< double > &nodes, std::vector< size_t > &edgesInTriangle, std::vector< size_t > &edgeTags, std::vector< size_t > &triangles)
template<Enum Enumerator>
constexpr std::underlying_type_t< Enumerator > getUnderlying (Enumerator e)
Options * globalOptions ()
Options * globalOptions (Options *newOpts)
std::string info ()
Library short info.
static void init (diradmdata &destination)
bool interactive ()
size_t interpolationPoints ()
double kBRatio (size_t const bytes, size_t const pieces)
template<typename Field >
constexpr SpaceVector< std::add_const_t< Field > > makeConst (SpaceVector< Field > const vector)
static void makeDirections (std::array< DumbPointer< dcluster >, 2 > &directionalClusters, diradmdata const &directions, DumbPointer< dblock > &directionalBlock)
Options * makeOptions (bool const deferInit)
template<Enum Enumerator>
constexpr Enumerator max ()
template<typename T >
void maybeFree (T *object)
std::string meshFile ()
template<typename Field1 , typename Field2 >
SpaceVector< std::remove_const_t< Field2 > > operator* (SpaceVector< Field1 > const vector, Field2 const scale)
template<typename Field >
SpaceVector< std::remove_const_t< Field > > operator+ (SpaceVector< Field > const v1, SpaceVector< Field > const v2)
template<typename Field >
SpaceVector< Field > & operator+= (SpaceVector< Field > &v1, SpaceVector< Field > const v2)
template<typename Field >
SpaceVector< std::remove_const_t< Field > > operator- (SpaceVector< Field > const v1, SpaceVector< Field > const v2)
template<typename Field >
SpaceVector< Field > & operator-= (SpaceVector< Field > &v1, SpaceVector< Field > const v2)
template<typename Field >
SpaceVector< std::remove_const_t< Field > > operator/ (SpaceVector< Field > const vector, Field const scale)
constexpr std::pair< SpaceSlices, SpaceSlices > operatorSpaces (OperatorSlices const slice)
constexpr std::pair< SpaceSlices, SpaceSlices > operatorSpaces (size_t const slice)
std::string outputDirectory ()
FILE * outputFile (std::string const name, bool const replace)
Open a file for writing.
static SurfaceList parseNodesPhysical (size_t const dofs)
static void parsePhysicalName (std::string const name, int const tag, int const dimension, SurfaceList &surfaces)
double percentRatio (size_t const up, size_t const down)
template<typename Field >
constexpr SpaceVector< Field > pointer2constVector (std::add_const_t< Field > const coordinate[3])
template<typename Field >
constexpr SpaceVector< std::remove_const_t< Field > > pointer2vector (std::add_const_t< Field > const coordinate[3])
reporter * progressBar ()
size_t quadraturePoints ()
bool reference ()
static std::vector< size_t > reorderElements (Mesh::MembershipVector const &dirichletBoundary, Mesh::MembershipVector const &neumannBoundary, size_t const nodesCount, Mesh &meshData)
static void reportClusterCompression (dclusterbasis const *const basis, dclusteroperator const *const clOperator, size_t const dof, std::string const timingReport)
void reportParallelization ()
bool saveError ()
bool saveMesh ()
bool saveOffset ()
bool saveRhs ()
bool saveSolution ()
template<Enum Enumerator>
constexpr size_t size ()
static void splitTriangles (std::vector< size_t > const &triangles, size_t const nodesCount, SurfaceList &surfaces)
auto startTiming ()
std::string stopTiming ()
template<class Return , class... Args>
std::enable_if_t< std::negation_v< std::is_void< Return > >, Return > timeExecution (Return(*function)(Args...), std::function< void(std::string const, pointerOrReference< constPointer< Return > >)> logger, Args... args)
template<class Return , class... Args>
std::enable_if_t< std::negation_v< std::is_void< Return > >, Return > timeExecution (std::function< Return(Args...)> function, std::function< void(std::string const, pointerOrReference< constPointer< Return > >)> logger, Args... args)
template<class Return , class... Args>
std::enable_if_t< std::is_void_v< Return >, void > timeExecution (std::function< void(Args...)> function, std::function< void(std::string const)> logger, Args... args)
template<class Return , class... Args>
std::enable_if_t< std::is_void_v< Return >, void > timeExecution (void(*function)(Args...), std::function< void(std::string const)> logger, Args... args)
std::string warning ()
Distribution warning (about h2lib and gmsh).
Variables
constexpr double bytesInKB = 1024
Bytes in a kB.
constexpr double bytesInMB = bytesInKB * bytesInKB
Bytes in a MB.
static std::string const currentName = cmake_LIBNAME
Library name, supplied through CMake.
static constexpr size_t dimKrylov_K = 20
static std::string const dirichletName = "d"
Dirichlet boundary conditions identifier.
template<class spaceFunction >
constexpr field(*)(pcreal, pcreal, void *) dirichletPointer ()
static std::string const names [size< MeshReader::View >()] = {"solution", "rhs", "offset","error"}
static std::string const neumannName = "n"
Neumann boundary conditions identifier.
template<class spaceFunction >
constexpr field(*)(pcreal, pcreal, void *) neumannPointer ()
std::string const projectName = cmake_NAME
Project name, supplied through CMake.
constexpr size_t spaceDimension = 3
Number of space dimensions.
constexpr bool timingEnabled = true
constexpr size_t versionMajor = cmake_MAJOR
Major version, supplied through CMake.
constexpr size_t versionMinor = cmake_MINOR
Minor version, supplied through CMake.
Typedef Documentation
constPointer
template<class Type > using MainNamespace::constPointer = typedef std::conditional_t<std::is_pointer_v<Type>, std::add_const_t<std::add_pointer_t<std::add_const_t<std::remove_pointer_t<Type> >> >, std::add_const_t<Type> >
IndexSpace
template<class Objects > using MainNamespace::IndexSpace = typedef std::array<std::vector<Objects>, size<SpaceSlices>()>
Type for an array with indices information.
Operators
template<class Objects > using MainNamespace::Operators = typedef std::array<Objects, size<OperatorSlices>()>
Type for an array with all slices of some operator-related object.
pointerOrReference
template<class Type > using MainNamespace::pointerOrReference = typedef std::conditional_t<std::is_pointer_v<Type>, Type, std::conditional<std::is_reference_v<Type>, Type, std::add_lvalue_reference_t<Type> >>
SlicedOperator
template<class Objects > using MainNamespace::SlicedOperator = typedef PointerArray<Objects, size<OperatorSlices>()>
Type for an array with pointers to all slices of some operator-related object.
SlicedSpace
template<class Objects > using MainNamespace::SlicedSpace = typedef PointerArray<Objects, size<SpaceSlices>()>
Type for an array with pointers to all slices of some space-related object.
SpaceVector
template<typename Field > using MainNamespace::SpaceVector = typedef std::array<Field, spaceDimension>
Vectors on spaceDimension dimensional vector space on the field Field.
SurfaceList
using MainNamespace::SurfaceList = typedef std::map<std::string, Mesh::MembershipVector>
List of surfaces (as pairs (name, membership)).
Enumeration Type Documentation
DataOperator
enum class MainNamespace::DataOperator strong
Enumerator
DataSolutionSingle
Enum to manage arrays of differend boundary operator or associated auxiliary elements.
Object associated to the single layer operator, with input an element with given boundary data, output an element with unknown (solution) data.
DataSolutionDouble
Object associated to the double layer operator, with input an element with given boundary data, output an element with unknown (solution) data.
SolutionDataDouble
Object associated to the double layer operator, with input output an element with unknown (solution) data, an element with given boundary data (for K').
DataSolutionHypersingular
Object associated to the hypersingular operator, with input an element with given boundary data, output an element with unknown (solution) data.
COUNT
Counting the number of elements in the enumerator.
DataSpaces
enum class MainNamespace::DataSpaces strong
Enumerator
Dirichlet
Enum to manage arrays of differend boundary operator or associated auxiliary elements.
Element with unknown (solution) data, in the Dirichlet trace.
Neumann
Element with unknown (solution) data, in the Neumann trace.
COUNT
Counting the number of elements in the enumerator.
OperatorSlices
enum class MainNamespace::OperatorSlices strong
Enumerator
SolutionSolutionSingle
Enum to manage arrays of differend boundary operator or associated auxiliary elements.
Object associated to the sigle layer operator, with input and output elements with given boundary data.
SolutionSolutionDouble
Object associated to the double layer operator, with input and output elements with given boundary data.
SolutionSolutionHypersingular
Object associated to the hypersingular operator, with input and output elements with given boundary data.
DataSolutionSingle
Object associated to the single layer operator, with input an element with given boundary data, output an element with unknown (solution) data.
COUNTDof
Count of the slices that only operate on degrees of freedom.
DataSolutionDouble
Object associated to the double layer operator, with input an element with given boundary data, output an element with unknown (solution) data.
SolutionDataDouble
Object associated to the double layer operator, with input output an element with unknown (solution) data, an element with given boundary data (for K').
DataSolutionHypersingular
Object associated to the hypersingular operator, with input an element with given boundary data, output an element with unknown (solution) data.
COUNT
Counting the number of elements in the enumerator.
SpaceSlices
enum class MainNamespace::SpaceSlices strong
Enumerator
DirichletSolution
Enum to manage arrays of differend boundary operator or associated auxiliary elements.
Elements with given boundary data, in the Dirichlet trace.
DirichletData
Element with unknown (solution) data, in the Dirichlet trace.
NeumannSolution
Elements with given boundary data, in the Neumann trace.
NeumannData
Element with unknown (solution) data, in the Neumann trace.
COUNT
Counting the number of elements in the enumerator.
Type
enum MainNamespace::Type
Enumerator
edgesIdx
Ordering of lines, triangle, nodes in an array containing definitions for more than one dimension.
trianglesIdx
nodesIdx
Function Documentation
at() [1/5]
template<class Enumerator , class BaseValues , size_t length> BaseValues & MainNamespace::at (std::array< BaseValues, length > & array, Enumerator const idx)
References getUnderlying().
at() [2/5]
template<class BaseValues , size_t length> BaseValues & MainNamespace::at (std::array< BaseValues, length > *const array, size_t const idx)
at() [3/5]
template<class Enumerator , class BaseValues , size_t length> BaseValues MainNamespace::at (std::array< BaseValues, length > const & array, Enumerator const idx)
References getUnderlying().
Referenced by MainNamespace::Surface::SingleSurface::SingleSurface(), MainNamespace::Surface::SingleSurface::computeDifferenceNorm(), MainNamespace::Surface::SingleSurface::makeOffset(), and MainNamespace::Surface::SingleSurface::setupCluster().
at() [4/5]
template<class BaseValues , size_t length> BaseValues MainNamespace::at (std::array< BaseValues, length > const *const array, size_t const idx)
at() [5/5]
template<class BaseValues , size_t length, class ConstValues = std::add_const_t<BaseValues>> BaseValues MainNamespace::at (std::array< ConstValues, length > const *const array, size_t const idx)
buildImplicitClusterBasis()
static dclusteroperator * MainNamespace::buildImplicitClusterBasis (helmholtz3d *const bm, dcluster const *const root, leaf_func_t leaf, size_t const dofs) inline static
Build a cluster basis.
Todo:
why implicit?
Returns
directional cluster operater.
Parameters
bm Pointer to the helmoltz object.
Todo:
why? what?
Parameters
root Root of the directional cluster.
leaf idk
Todo:
idk.
Parameters
dofs Number of degrees of freedom (to report the memory per degee of freedom).
References bytes2MB(), kBRatio(), MainNamespace::Logger::log(), progressBar(), and timeExecution().
Referenced by buildOperator().
buildOperator()
dh2matrix * MainNamespace::buildOperator (std::array< DumbPointer< dcluster >, 2 > & directionalClusters, DumbPointer< dblock > & directionalBlock, diradmdata const & directions, helmholtz3d *const bemDescription)
Build a dh2matrix for the operator described by bemDescription, using the given clusters.
Returns
A boundary operator in dh2 compressed form.
Parameters
directionalClusters Row and column directional clusters.
directionalBlock Root of the directional block tree.
directions Directional admissibility data.
bemDescription Bem description object.
References buildImplicitClusterBasis(), bytes2MB(), compressRowColumnFar(), MainNamespace::Logger::green, kBRatio(), MainNamespace::Logger::log(), makeDirections(), percentRatio(), reference(), and timeExecution().
Referenced by MainNamespace::DH2MatrixWrapper::build().
buildSurface()
static surface3d * MainNamespace::buildSurface (std::vector< size_t > const & reordering, std::vector< double > const & nodes, std::vector< size_t > const & edgesInTriangle, std::vector< size_t > const & edgeTags, std::vector< size_t > const & triangles, std::vector< size_t > const & nodeTags) static
Consturct a surface in H2Lib format.
Returns
The new surface.
Parameters
reordering Reverse reordering map. See reorderElements.
nodes Coordinates for nodes, flattened.
[out] edgesInTriangle Edges of all triangles, as pairs of node tags. Triangle t has 6 indices starting at 6t.
[out] edgeTags Edges of all triangles, as edge tags. Triangle t has 3 indices starting at 3t.
triangles Triangles, as list of nodes (flattened).
nodeTags Tags of the nodes, in the same order as nodes.
References MainNamespace::Logger::log(), MainNamespace::Logger::magenta, and computemeshsize::triangles.
Referenced by MainNamespace::MeshReader::parseMesh().
bytes2KB()
double MainNamespace::bytes2KB (size_t const bytes) inline
Convert a quantity in B to kB.
Returns
The same quantity in kB (floating point)
Parameters
bytes Bytes (integer).
References bytesInKB.
Referenced by kBRatio(), and reportClusterCompression().
bytes2MB()
double MainNamespace::bytes2MB (size_t const bytes) inline
Convert a quantity in B to MB.
Returns
The same quantity in MB (floating point)
Parameters
bytes Bytes (integer).
References bytesInMB.
Referenced by buildImplicitClusterBasis(), buildOperator(), and reportClusterCompression().
cloneDcluster()
static dcluster * MainNamespace::cloneDcluster (dcluster const *const other) inline static
Clone a directional cluster.
Returns
Copy of other.
Parameters
other Directional cluster to copy.
References cloneDcluster().
Referenced by MainNamespace::DH2MatrixWrapper::build(), and cloneDcluster().
clusterResolution()
size_t MainNamespace::clusterResolution () inline
References MainNamespace::Options::clusterResolution_, and globalOptions().
Referenced by MainNamespace::Surface::buildGeometricCluster(), and MainNamespace::Surface::SingleSurface::setupCluster().
compression()
bool MainNamespace::compression () inline
References MainNamespace::Options::compression(), and globalOptions().
compressRowColumnFar()
static dh2matrix * MainNamespace::compressRowColumnFar (dblock const *const root, helmholtz3d *const bemDescription, dclusteroperator const *const rowCluster, dclusteroperator const *const columnCluster, truncmode const *const trMode) inline static
References eps(), MainNamespace::Logger::green, MainNamespace::Logger::log(), progressBar(), reportClusterCompression(), startTiming(), and stopTiming().
Referenced by buildOperator().
constAt() [1/2]
template<class Enumerator , class BaseValues , size_t length, class ConstValues = std::add_const_t<BaseValues>> ConstValues & MainNamespace::constAt (std::array< BaseValues, length > const & array, Enumerator const idx)
References getUnderlying().
Referenced by MainNamespace::Surface::SingleSurface::apply().
constAt() [2/2]
template<class BaseValues , size_t length, class ConstValues = std::add_const_t<BaseValues>> ConstValues & MainNamespace::constAt (std::array< BaseValues, length > const *const array, size_t const idx)
copy()
static void MainNamespace::copy (diradmdata const & data, diradmdata & destination) inline static
The field xy is (re)allocated, ld is cleared and left as a null pointer. Parameters are copied.Copy a diradmdata stuct.
Parameters
data Directional admissibility data source.
[out] destination Destination.
References maybeFree().
Referenced by MainNamespace::Surface::copySurface(), makeDirections(), and MainNamespace::Surface::orientCopy().
copyrightNotice()
std::string MainNamespace::copyrightNotice ()
Library copyright notice.
References info(), and projectName.
count()
template<Enum Enumerator> constexpr std::underlying_type_t< Enumerator > MainNamespace::count () inline constexpr
Referenced by main(), lyra::arguments::parse_any(), and lyra::arguments::parse_sequence().
createFakeProgressBar()
reporter * MainNamespace::createFakeProgressBar () inline
References MainNamespace::ReporterHelper::fakeBegin(), MainNamespace::ReporterHelper::fakeEnd(), MainNamespace::ReporterHelper::fakeStep(), and MainNamespace::ReporterHelper::fakeUninit().
createProgressBar()
reporter * MainNamespace::createProgressBar () inline
Referenced by MainNamespace::Options::Options().
createStopWatch()
stopwatch * MainNamespace::createStopWatch () inline
delOptions()
Options * MainNamespace::delOptions ()
References globalOptions().
dimKrylov()
size_t MainNamespace::dimKrylov () inline
References dimKrylov_K.
Referenced by MainNamespace::Surface::doGmres().
eps()
real MainNamespace::eps () inline
References MainNamespace::Options::eps(), and globalOptions().
Referenced by compressRowColumnFar().
epsKrylov()
real MainNamespace::epsKrylov () inline
References MainNamespace::Options::epsKrylov(), and globalOptions().
Referenced by MainNamespace::Surface::doGmres().
getElements()
static void MainNamespace::getElements (std::array< std::vector< size_t >, 3 > & tags, std::vector< double > & nodes, std::vector< size_t > & edgesInTriangle, std::vector< size_t > & edgeTags, std::vector< size_t > & triangles) inline static
Parse and fill all element tags, and their definition.
Parameters
[out] tags Tags for all elements (nodes, triangles, lines).
[out] nodes Nodes coordinates.
[out] edgesInTriangle Edges of all triangles, as pairs of node tags. Triangle t has 6 indices starting at 6t.
[out] edgeTags Edges of all triangles, as edge tags. Triangle t has 3 indices starting at 3t.
[out] triangles List of tags identifying triangles.
References getElements(), MainNamespace::Logger::log(), MainNamespace::Logger::magenta, nodesIdx, computemeshsize::triangles, and trianglesIdx.
Referenced by getElements(), and MainNamespace::MeshReader::parseMesh().
getUnderlying()
template<Enum Enumerator> constexpr std::underlying_type_t< Enumerator > MainNamespace::getUnderlying (Enumerator e) inline constexpr
Referenced by MainNamespace::MeshReader::MeshReader(), at(), MainNamespace::Logger::colorString(), constAt(), MainNamespace::PointerArray< BaseValues, length, ActualValue >::operator[](), and MainNamespace::MeshReader::saveView().
globalOptions() [1/2]
Options * MainNamespace::globalOptions ()
References MainNamespace::anonymous_namespace{options.cpp}::globalOptions_.
Referenced by MainNamespace::Options::Options(), MainNamespace::Options::~Options(), clusterResolution(), compression(), delOptions(), eps(), epsKrylov(), interactive(), interpolationPoints(), makeOptions(), meshFile(), outputDirectory(), progressBar(), quadraturePoints(), reference(), saveError(), saveMesh(), saveOffset(), saveRhs(), saveSolution(), startTiming(), and stopTiming().
globalOptions() [2/2]
Options * MainNamespace::globalOptions (Options * newOpts)
References MainNamespace::anonymous_namespace{options.cpp}::globalOptions_.
info()
std::string MainNamespace::info ()
Library short info.
References currentName, projectName, lyra::detail::to_string(), versionMajor, and versionMinor.
Referenced by copyrightNotice().
init()
static void MainNamespace::init (diradmdata & destination) inline static
Set pointers to null to prevent deallocation of non-allocated memory.
Parameters
[out] destination Object to initialize.
Referenced by makeDirections().
interactive()
bool MainNamespace::interactive () inline
References globalOptions(), and MainNamespace::Options::interactive().
interpolationPoints()
size_t MainNamespace::interpolationPoints () inline
References globalOptions(), and MainNamespace::Options::interpolationPoints().
Referenced by MainNamespace::Surface::MultiSurface::MultiSurface(), MainNamespace::Surface::SingleSurface::buildOperator(), and MainNamespace::Surface::SingleSurface::makeMultiRhs().
kBRatio()
double MainNamespace::kBRatio (size_t const bytes, size_t const pieces) inline
Compute the ratio "kB per piece", given the numbers of bytes and pieces.
Returns
Ratio.
Parameters
bytes Bytes
pieces Pieces
References bytes2KB().
Referenced by buildImplicitClusterBasis(), and buildOperator().
makeConst()
template<typename Field > constexpr SpaceVector< std::add_const_t< Field > > MainNamespace::makeConst (SpaceVector< Field > const vector) inline constexpr
makeDirections()
static void MainNamespace::makeDirections (std::array< DumbPointer< dcluster >, 2 > & directionalClusters, diradmdata const & directions, DumbPointer< dblock > & directionalBlock) static
References copy(), MainNamespace::Logger::green, init(), MainNamespace::Logger::log(), and MainNamespace::Logger::yellow.
Referenced by buildOperator().
makeOptions()
Options * MainNamespace::makeOptions (bool const deferInit)
References globalOptions().
max()
template<Enum Enumerator> constexpr Enumerator MainNamespace::max () inline constexpr
maybeFree()
template<typename T > void MainNamespace::maybeFree (T * object) inline
References MainNamespace::CFunctions::freeCPointer().
Referenced by MainNamespace::BoermTimer::~BoermTimer(), MainNamespace::DumbPointer< BaseData >::~DumbPointer(), MainNamespace::Surface::MultiSurface::~MultiSurface(), MainNamespace::Options::~Options(), MainNamespace::PointerArray< BaseValues, length, ActualValue >::clear(), copy(), del_diradmdata(), and MainNamespace::DumbPointer< BaseData >::operator=().
meshFile()
std::string MainNamespace::meshFile () inline
References globalOptions(), and MainNamespace::Options::meshFile().
Referenced by MainNamespace::Mesh::writeMesh().
operator*()
template<typename Field1 , typename Field2 > SpaceVector< std::remove_const_t< Field2 > > MainNamespace::operator* (SpaceVector< Field1 > const vector, Field2 const scale) inline
References spaceDimension.
operator+()
template<typename Field > SpaceVector< std::remove_const_t< Field > > MainNamespace::operator+ (SpaceVector< Field > const v1, SpaceVector< Field > const v2) inline
References spaceDimension.
operator+=()
template<typename Field > SpaceVector< Field > & MainNamespace::operator+= (SpaceVector< Field > & v1, SpaceVector< Field > const v2) inline
References spaceDimension.
operator-()
template<typename Field > SpaceVector< std::remove_const_t< Field > > MainNamespace::operator- (SpaceVector< Field > const v1, SpaceVector< Field > const v2) inline
References spaceDimension.
operator-=()
template<typename Field > SpaceVector< Field > & MainNamespace::operator-= (SpaceVector< Field > & v1, SpaceVector< Field > const v2) inline
References spaceDimension.
operator/()
template<typename Field > SpaceVector< std::remove_const_t< Field > > MainNamespace::operator/ (SpaceVector< Field > const vector, Field const scale) inline
References spaceDimension.
operatorSpaces() [1/2]
constexpr std::pair< SpaceSlices, SpaceSlices > MainNamespace::operatorSpaces (OperatorSlices const slice) inline constexpr
References COUNT, DataSolutionDouble, DataSolutionHypersingular, DataSolutionSingle, DirichletData, DirichletSolution, MainNamespace::Logger::log(), NeumannData, NeumannSolution, MainNamespace::Logger::red, SolutionDataDouble, SolutionSolutionDouble, SolutionSolutionHypersingular, and SolutionSolutionSingle.
Referenced by MainNamespace::Surface::SingleSurface::buildOperator(), and operatorSpaces().
operatorSpaces() [2/2]
constexpr std::pair< SpaceSlices, SpaceSlices > MainNamespace::operatorSpaces (size_t const slice) inline constexpr
References operatorSpaces().
outputDirectory()
std::string MainNamespace::outputDirectory () inline
References globalOptions(), and MainNamespace::Options::outputDirectory().
Referenced by MainNamespace::MeshReader::~MeshReader(), and testProblem().
outputFile()
FILE * MainNamespace::outputFile (std::string const name, bool const replace)
Open a file for writing.
Returns
the stream on success, nullptr on failure.
Parameters
name File name.
replace True for write mode, false for append.
References MainNamespace::Logger::green, MainNamespace::Logger::log(), MainNamespace::Logger::red, and warning().
Referenced by testProblem().
parseNodesPhysical()
static SurfaceList MainNamespace::parseNodesPhysical (size_t const dofs) static
Parse which nodes belong to which surface. See parsePhysical for the format.
Returns
For each surface, for every dof, true/false depending whether it belongs to the surface.
Parameters
dofs Number of total dofs in the mesh (at least the nodes).
References dirichletName, MainNamespace::Logger::green, MainNamespace::Logger::log(), neumannName, and parsePhysicalName().
Referenced by MainNamespace::MeshReader::parseMesh().
parsePhysicalName()
static void MainNamespace::parsePhysicalName (std::string const name, int const tag, int const dimension, SurfaceList & surfaces) inline static
Parse which nodes belong to which surface.
Parse a string into a list of strings, separated by any number of whitespaces. These are interpreted as the names of the surfaces which share the nodes in the physical group, or as boundary conditions in the given point.
For all surface names (or boundary condition):
if this surface was not parsed before, add it to the surfaces structure, as a vector of zeros of the same length as the boundary conditions (always considered as initialized with the right length).
add the nodes to the surface, by setting to 1 (correct orientation) or -1 (reverse orientation) the element with index (nodetag-1), for all nodetag that GMSH considers in the physical group.
Naming conventions:
Dirichlet boundary: "d";
Neumann boundary: "n";
Names are case-insensitive, instead any capital letter in the name means that the group has the wrong orientation.
Parameters
name Name to process.
tag Tag of the physical group.
dimension Dimension of the physical group.
[out] surfaces For each surface, for every node, 0 if the node does not belong to the surface. The sign specify the orientation.
References MainNamespace::Logger::cyan, dirichletName, MainNamespace::Logger::green, MainNamespace::Logger::log(), MainNamespace::Logger::reset, size(), and MainNamespace::Logger::yellow.
Referenced by parseNodesPhysical().
percentRatio()
double MainNamespace::percentRatio (size_t const up, size_t const down) inline
Write a ratio as percent.
Returns
100 * up / down.
Parameters
up a in a/b.
down b in a/b
Referenced by buildOperator().
pointer2constVector()
template<typename Field > constexpr SpaceVector< Field > MainNamespace::pointer2constVector (std::add_const_t< Field > const coordinate[3]) inline constexpr
pointer2vector()
template<typename Field > constexpr SpaceVector< std::remove_const_t< Field > > MainNamespace::pointer2vector (std::add_const_t< Field > const coordinate[3]) inline constexpr
progressBar()
reporter * MainNamespace::progressBar () inline
References globalOptions(), and MainNamespace::Options::progressBar_.
Referenced by MainNamespace::DH2MatrixWrapper::build(), buildImplicitClusterBasis(), and compressRowColumnFar().
quadraturePoints()
size_t MainNamespace::quadraturePoints () inline
References globalOptions(), and MainNamespace::Options::quadraturePoints().
Referenced by MainNamespace::Surface::MultiSurface::MultiSurface(), MainNamespace::Surface::SingleSurface::buildOperator(), and MainNamespace::Surface::SingleSurface::makeMultiRhs().
reference()
bool MainNamespace::reference () inline
References globalOptions(), and MainNamespace::Options::reference().
Referenced by buildOperator(), MainNamespace::Surface::SingleSurface::computeDifferenceNorm(), and MainNamespace::Surface::MultiSurface::error().
reorderElements()
static std::vector< size_t > MainNamespace::reorderElements (Mesh::MembershipVector const & dirichletBoundary, Mesh::MembershipVector const & neumannBoundary, size_t const nodesCount, Mesh & meshData) static
Reorder the vertices and triangles so that the unknowns are the beginning of their vector section.
Returns
Reverse order map: index j (of the appropriate array segment) stores the position of the element with tag j+1.
Parameters
dirichletBoundary Membership to the dirichlet boundary.
neumannBoundary Membership to the neumann boundary.
nodesCount Total number of nodes.
[out] meshData triangleDofs and vertexDofs, the number of triangle and vertex degrees of freedom are filled. The membership data is reordered.
References MainNamespace::Logger::green, MainNamespace::Logger::log(), MainNamespace::Mesh::membership_, MainNamespace::Mesh::triangleDofs_, and MainNamespace::Mesh::vertexDofs_.
Referenced by MainNamespace::MeshReader::parseMesh().
reportClusterCompression()
static void MainNamespace::reportClusterCompression (dclusterbasis const *const basis, dclusteroperator const *const clOperator, size_t const dof, std::string const timingReport) inline static
Log a message reporting the compression of the given cluster.
Parameters
basis Cluster basis.
Todo:
Why?
Parameters
clOperator Cluster operator.
Todo:
Why?
Parameters
dof Degrees of freedom, to report the memory used per degree of freedom.
timingReport List of the times to build the ??, as reported by varius timers.
Todo:
build what?
References bytes2KB(), bytes2MB(), and MainNamespace::Logger::log().
Referenced by compressRowColumnFar().
reportParallelization()
void MainNamespace::reportParallelization ()
References MainNamespace::Logger::green, MainNamespace::Logger::log(), MainNamespace::Logger::red, and warning().
Referenced by main().
saveError()
bool MainNamespace::saveError () inline
References globalOptions(), and MainNamespace::Options::saveError().
Referenced by MainNamespace::MeshReader::MeshReader().
saveMesh()
bool MainNamespace::saveMesh () inline
References globalOptions(), and MainNamespace::Options::saveMesh().
Referenced by MainNamespace::Mesh::writeMesh().
saveOffset()
bool MainNamespace::saveOffset () inline
References globalOptions(), and MainNamespace::Options::saveOffset().
Referenced by MainNamespace::MeshReader::MeshReader().
saveRhs()
bool MainNamespace::saveRhs () inline
References globalOptions(), and MainNamespace::Options::saveRhs().
Referenced by MainNamespace::MeshReader::MeshReader().
saveSolution()
bool MainNamespace::saveSolution () inline
References globalOptions(), and MainNamespace::Options::saveSolution().
Referenced by MainNamespace::MeshReader::MeshReader().
size()
template<Enum Enumerator> constexpr size_t MainNamespace::size () inline constexpr
Referenced by lyra::detail::token_iterator::is_prefix_char(), lyra::detail::token_iterator::is_prefixed(), MainNamespace::MeshReader::parseMesh(), parsePhysicalName(), lyra::detail::token_iterator::prefix_value(), and MainNamespace::Surface::SingleSurface::setupCluster().
splitTriangles()
static void MainNamespace::splitTriangles (std::vector< size_t > const & triangles, size_t const nodesCount, SurfaceList & surfaces) inline static
Fill information about which triangle is part of wich surface.
Parameters
triangles Triangles description.
nodesCount Number of nodes (offset for the triangles).
[in,out] surfaces For each surface, for every mesh degree of freedom, true if it belongs to the surface.
References MainNamespace::Logger::green, MainNamespace::Logger::log(), computemeshsize::triangles, and MainNamespace::Logger::yellow.
Referenced by MainNamespace::MeshReader::parseMesh().
startTiming()
auto MainNamespace::startTiming () inline
References globalOptions(), MainNamespace::Clocks::start(), and MainNamespace::Options::timer_.
Referenced by compressRowColumnFar(), MainNamespace::Surface::doGmres(), and timeExecution().
stopTiming()
std::string MainNamespace::stopTiming () inline
References globalOptions(), MainNamespace::Clocks::readAll(), and MainNamespace::Options::timer_.
Referenced by compressRowColumnFar(), MainNamespace::Surface::doGmres(), and timeExecution().
timeExecution() [1/4]
template<class Return , class... Args> std::enable_if_t< std::negation_v< std::is_void< Return > >, Return > MainNamespace::timeExecution (Return(*)(Args...) function, std::function< void(std::string const, pointerOrReference< constPointer< Return > >)> logger, Args... args)
References timeExecution().
timeExecution() [2/4]
template<class Return , class... Args> std::enable_if_t< std::negation_v< std::is_void< Return > >, Return > MainNamespace::timeExecution (std::function< Return(Args...)> function, std::function< void(std::string const, pointerOrReference< constPointer< Return > >)> logger, Args... args)
Execute function with args... as arguments, log the elapsed time and possibly some other message, according to logger. This version is called when function returns someting other than void.
Returns
The value returned by function.
Parameters
function Function whose running time should be measured.
logger Function which is called with the elapsed time and the return value as arguments. The intended use is logging messages.
args Arguments to pass to function.
References startTiming(), and stopTiming().
Referenced by buildImplicitClusterBasis(), buildOperator(), and timeExecution().
timeExecution() [3/4]
template<class Return , class... Args> std::enable_if_t< std::is_void_v< Return >, void > MainNamespace::timeExecution (std::function< void(Args...)> function, std::function< void(std::string const)> logger, Args... args)
Execute function with args... as arguments, log the elapsed time and possibly some other message, according to logger. This version is called when function returns void.
Parameters
function Function whose running time should be measured.
logger Function which is called with the elapsed time. The intended use is logging messages.
args Arguments to pass to function.
References startTiming(), and stopTiming().
timeExecution() [4/4]
template<class Return , class... Args> std::enable_if_t< std::is_void_v< Return >, void > MainNamespace::timeExecution (void(*)(Args...) function, std::function< void(std::string const)> logger, Args... args)
References timeExecution().
warning()
std::string MainNamespace::warning ()
Distribution warning (about h2lib and gmsh).
References projectName.
Referenced by MainNamespace::Options::Options(), MainNamespace::Options::~Options(), MainNamespace::Surface::SingleSurface::check(), MainNamespace::Surface::doGmres(), MainNamespace::Surface::getFromFile(), MainNamespace::Logger::log(), outputFile(), reportParallelization(), and MainNamespace::Mesh::writeMesh().
Variable Documentation
bytesInKB
constexpr double MainNamespace::bytesInKB = 1024 constexpr
Bytes in a kB.
Referenced by bytes2KB().
bytesInMB
constexpr double MainNamespace::bytesInMB = bytesInKB * bytesInKB constexpr
Bytes in a MB.
Referenced by bytes2MB().
currentName
std::string const MainNamespace::currentName = cmake_LIBNAME static
Library name, supplied through CMake.
Referenced by info().
dimKrylov_K
constexpr size_t MainNamespace::dimKrylov_K = 20 static constexpr
Referenced by dimKrylov().
dirichletName
std::string const MainNamespace::dirichletName = "d" static
Dirichlet boundary conditions identifier.
Referenced by MainNamespace::MeshReader::parseMesh(), parseNodesPhysical(), and parsePhysicalName().
dirichletPointer
template<class spaceFunction > constexpr field(*)(pcreal, pcreal, void *) MainNamespace::dirichletPointer() () constexpr
names
std::string const MainNamespace::names[size< MeshReader::View >()] = {"solution", "rhs", "offset","error"} static
Referenced by MainNamespace::MeshReader::MeshReader(), and MainNamespace::MeshReader::~MeshReader().
neumannName
std::string const MainNamespace::neumannName = "n" static
Neumann boundary conditions identifier.
Referenced by MainNamespace::MeshReader::parseMesh(), and parseNodesPhysical().
neumannPointer
template<class spaceFunction > constexpr field(*)(pcreal, pcreal, void *) MainNamespace::neumannPointer() () constexpr
projectName
std::string const MainNamespace::projectName = cmake_NAME
Project name, supplied through CMake.
Referenced by copyrightNotice(), info(), and warning().
spaceDimension
constexpr size_t MainNamespace::spaceDimension = 3 constexpr
Number of space dimensions.
Referenced by MainNamespace::Functions::PlaneWave::PlaneWave(), MainNamespace::Functions::PlaneWave::dirichlet(), MainNamespace::Functions::PlaneWave::neumann(), operator*(), operator+(), operator+=(), operator-(), operator-=(), and operator/().
timingEnabled
constexpr bool MainNamespace::timingEnabled = true constexpr
versionMajor
constexpr size_t MainNamespace::versionMajor = cmake_MAJOR constexpr
Major version, supplied through CMake.
Referenced by info().
versionMinor
constexpr size_t MainNamespace::versionMinor = cmake_MINOR constexpr
Minor version, supplied through CMake.
Referenced by info().