Skeletal: lyra::args Class Reference
lyra::args Class Reference
#include <args.hpp>
Public Member Functions
template<typename It >
args (const It &start, const It &end)
template<typename It >
args (const It &start, const It &end)
args (int argc, char const *const *argv)
args (int argc, char const *const *argv)
args (std::initializer_list< std::string > args_list)
args (std::initializer_list< std::string > args_list)
std::vector< std::string >::const_iterator begin () const
std::vector< std::string >::const_iterator begin () const
std::vector< std::string >::const_iterator end () const
std::vector< std::string >::const_iterator end () const
std::string exe_name () const
std::string exe_name () const
Private Attributes
std::vector< std::string > m_args
std::string m_exeName
Constructor & Destructor Documentation
args() [1/6]
lyra::args::args (int argc, char const *const * argv) inline
Referenced by gen_single_include.GenSingleInclude::resolve_include(), and gen_single_include.GenSingleInclude::run().
args() [2/6]
lyra::args::args (std::initializer_list< std::string > args_list) inline
Referenced by gen_single_include.GenSingleInclude::resolve_include(), and gen_single_include.GenSingleInclude::run().
args() [3/6]
template<typename It > lyra::args::args (const It & start, const It & end) inline
Referenced by gen_single_include.GenSingleInclude::resolve_include(), and gen_single_include.GenSingleInclude::run().
args() [4/6]
lyra::args::args (int argc, char const *const * argv) inline
Referenced by gen_single_include.GenSingleInclude::resolve_include(), and gen_single_include.GenSingleInclude::run().
args() [5/6]
lyra::args::args (std::initializer_list< std::string > args_list) inline
Referenced by gen_single_include.GenSingleInclude::resolve_include(), and gen_single_include.GenSingleInclude::run().
args() [6/6]
template<typename It > lyra::args::args (const It & start, const It & end) inline
Referenced by gen_single_include.GenSingleInclude::resolve_include(), and gen_single_include.GenSingleInclude::run().
Member Function Documentation
begin() [1/2]
std::vector< std::string >::const_iterator lyra::args::begin () const inline
References m_args.
begin() [2/2]
std::vector< std::string >::const_iterator lyra::args::begin () const inline
References m_args.
end() [1/2]
std::vector< std::string >::const_iterator lyra::args::end () const inline
References m_args.
end() [2/2]
std::vector< std::string >::const_iterator lyra::args::end () const inline
References m_args.
exe_name() [1/2]
std::string lyra::args::exe_name () const inline
References m_exeName.
Referenced by lyra::cli::parse().
exe_name() [2/2]
std::string lyra::args::exe_name () const inline
References m_exeName.
Member Data Documentation
m_args
std::vector< std::string > lyra::args::m_args private
Referenced by begin(), and end().
m_exeName
std::string lyra::args::m_exeName private
Referenced by exe_name().
The documentation for this class was generated from the following files:
Lyra/data/single_include/lyra/lyra.hpp
Lyra/include/lyra/args.hpp