Skeletal: MainNamespace::BaseTimer Class Reference
MainNamespace::BaseTimer Class Reference abstract
#include <timing.h>
Public Member Functions
virtual ~BaseTimer ()
Destructor. One is needed to be inherited.
virtual float read ()
Read the elapsed time at the last stop().
virtual void reset ()
Reset the timer.
virtual void resume ()=0
Resume the timer.
virtual void start ()
Reset and start the timer.
virtual void stop ()=0
Store the current time in the timer.
Protected Attributes
std::clock_t total_ = 0
Sum all measured times since reset.
Detailed Description
Get elapsed time info (either with monotonic wall clock or cpu time)
Constructor & Destructor Documentation
~BaseTimer()
virtual MainNamespace::BaseTimer::~BaseTimer () inline virtual
Destructor. One is needed to be inherited.
Member Function Documentation
read()
float MainNamespace::BaseTimer::read () virtual
Read the elapsed time at the last stop().
Reimplemented in MainNamespace::CpuTimer.
References total_.
Referenced by testProblem().
reset()
void MainNamespace::BaseTimer::reset () virtual
Reset the timer.
References total_.
Referenced by start().
resume()
virtual void MainNamespace::BaseTimer::resume () pure virtual
Resume the timer.
Implemented in MainNamespace::BoermTimer, and MainNamespace::CpuTimer.
Referenced by start().
start()
void MainNamespace::BaseTimer::start () virtual
Reset and start the timer.
References reset(), and resume().
Referenced by testProblem().
stop()
virtual void MainNamespace::BaseTimer::stop () pure virtual
Store the current time in the timer.
Implemented in MainNamespace::BoermTimer, and MainNamespace::CpuTimer.
Member Data Documentation
total_
std::clock_t MainNamespace::BaseTimer::total_ = 0 protected
Sum all measured times since reset.
Referenced by read(), MainNamespace::CpuTimer::read(), reset(), MainNamespace::BoermTimer::stop(), and MainNamespace::CpuTimer::stop().
The documentation for this class was generated from the following files:
main/timing.h
main/timing.cpp