???: lyra::bound_parser< Derived > Class Template Reference
lyra::bound_parser< Derived > Class Template Reference
#include <parser.hpp>
Public Types
enum class ctor_lambda_e { val , val }
enum class ctor_lambda_e { val , val }
Public Types inherited from lyra::parser
using help_text = std::vector< help_text_item >
using help_text = std::vector< help_text_item >
Public Member Functions
template<typename T >
bound_parser (detail::BoundVal< T > &&val)
template<typename T >
bound_parser (detail::BoundVal< T > &&val)
template<typename T >
bound_parser (detail::BoundVal< T > &&val, std::string const &hint)
template<typename T >
bound_parser (detail::BoundVal< T > &&val, std::string const &hint)
template<typename Lambda >
bound_parser (Lambda const &ref, std::string const &hint, typename std::enable_if< detail::is_invocable< Lambda >::value, ctor_lambda_e >::type=ctor_lambda_e::val)
template<typename Lambda >
bound_parser (Lambda const &ref, std::string const &hint, typename std::enable_if< detail::is_invocable< Lambda >::value, ctor_lambda_e >::type=ctor_lambda_e::val)
template<typename Reference >
bound_parser (Reference &ref, std::string const &hint)
template<typename Reference >
bound_parser (Reference &ref, std::string const &hint)
detail::parser_cardinality cardinality () const override
detail::parser_cardinality cardinality () const override
Derived & cardinality (size_t n)
Derived & cardinality (size_t n)
Derived & cardinality (size_t n, size_t m)
Derived & cardinality (size_t n, size_t m)
template<typename T , std::size_t N>
Derived & choices (const T(&choice_values)[N])
template<typename T , std::size_t N>
Derived & choices (const T(&choice_values)[N])
template<typename Lambda , typename std::enable_if< detail::is_invocable< Lambda >::value, int >::type = 1>
Derived & choices (Lambda const &check_choice)
template<typename Lambda , typename std::enable_if< detail::is_invocable< Lambda >::value, int >::type = 1>
Derived & choices (Lambda const &check_choice)
template<typename T , typename... Rest, typename std::enable_if<!detail::is_invocable< T >::value, int >::type = 0>
Derived & choices (T val0, Rest... rest)
template<typename T , typename... Rest, typename std::enable_if<!detail::is_invocable< T >::value, int >::type = 0>
Derived & choices (T val0, Rest... rest)
virtual std::unique_ptr< parser > clone () const override
virtual std::unique_ptr< parser > clone () const override
virtual std::string get_value (size_t i) const override
virtual std::string get_value (size_t i) const override
virtual size_t get_value_count () const override
virtual size_t get_value_count () const override
Derived & help (const std::string &text)
Derived & help (const std::string &text)
std::string hint () const
std::string hint () const
Derived & hint (std::string const &hint)
Derived & hint (std::string const &hint)
virtual bool is_named (const std::string &n) const override
virtual bool is_named (const std::string &n) const override
Derived & operator() (std::string const &description)
Derived & operator() (std::string const &description)
Derived & optional ()
Derived & optional ()
Derived & required (size_t n=1)
Derived & required (size_t n=1)
Public Member Functions inherited from lyra::parser
virtual ~parser ()=default
virtual ~parser ()=default
virtual detail::parser_cardinality cardinality () const
virtual detail::parser_cardinality cardinality () const
virtual std::unique_ptr< parser > clone () const
virtual std::unique_ptr< parser > clone () const
std::string get_description_text () const
std::string get_description_text () const
virtual std::string get_description_text (const option_style &) const
virtual std::string get_description_text (const option_style &) const
help_text get_help_text () const
help_text get_help_text () const
virtual help_text get_help_text (const option_style &) const
virtual help_text get_help_text (const option_style &) const
virtual const parser * get_named (const std::string &n) const
virtual const parser * get_named (const std::string &n) const
std::string get_usage_text () const
std::string get_usage_text () const
virtual std::string get_usage_text (const option_style &) const
virtual std::string get_usage_text (const option_style &) const
virtual std::string get_value (size_t i) const
virtual std::string get_value (size_t i) const
virtual size_t get_value_count () const
virtual size_t get_value_count () const
virtual bool is_group () const
virtual bool is_group () const
virtual bool is_named (const std::string &n) const
virtual bool is_named (const std::string &n) const
bool is_optional () const
bool is_optional () const
virtual parse_result parse (detail::token_iterator const &tokens, const option_style &style) const =0
virtual parse_result parse (detail::token_iterator const &tokens, const option_style &style) const =0
virtual result validate () const
virtual result validate () const
Protected Member Functions
bound_parser (std::shared_ptr< detail::BoundRef > const &ref)
bound_parser (std::shared_ptr< detail::BoundRef > const &ref)
bound_parser (std::shared_ptr< detail::BoundRef > const &ref, std::string const &hint)
bound_parser (std::shared_ptr< detail::BoundRef > const &ref, std::string const &hint)
Protected Member Functions inherited from lyra::parser
virtual void print_help_text (printer &p, const option_style &style) const
virtual void print_help_text (printer &p, const option_style &style) const
virtual void print_help_text_details (printer &p, const option_style &style) const
virtual void print_help_text_details (printer &p, const option_style &style) const
virtual void print_help_text_summary (printer &p, const option_style &style) const
virtual void print_help_text_summary (printer &p, const option_style &style) const
Protected Attributes
detail::parser_cardinality m_cardinality
std::string m_description
std::string m_hint
std::shared_ptr< detail::BoundRef > m_ref
std::shared_ptr< detail::choices_base > value_choices
Member Enumeration Documentation
ctor_lambda_e [1/2]
template<typename Derived > enum class lyra::bound_parser::ctor_lambda_e strong
Enumerator
val
val
ctor_lambda_e [2/2]
template<typename Derived > enum class lyra::bound_parser::ctor_lambda_e strong
Enumerator
val
val
Constructor & Destructor Documentation
bound_parser() [1/12]
template<typename Derived > lyra::bound_parser< Derived >::bound_parser (std::shared_ptr< detail::BoundRef > const & ref) inline explicit protected
References lyra::bound_parser< Derived >::m_cardinality, and lyra::bound_parser< Derived >::m_ref.
bound_parser() [2/12]
template<typename Derived > lyra::bound_parser< Derived >::bound_parser (std::shared_ptr< detail::BoundRef > const & ref, std::string const & hint) inline protected
References lyra::bound_parser< Derived >::m_cardinality, and lyra::bound_parser< Derived >::m_ref.
bound_parser() [3/12]
template<typename Derived > template<typename Reference > lyra::bound_parser< Derived >::bound_parser (Reference & ref, std::string const & hint)
bound_parser() [4/12]
template<typename Derived > template<typename Lambda > lyra::bound_parser< Derived >::bound_parser (Lambda const & ref, std::string const & hint, typename std::enable_if< detail::is_invocable< Lambda >::value, ctor_lambda_e >::type = ctor_lambda_e::val)
bound_parser() [5/12]
template<typename Derived > template<typename T > lyra::bound_parser< Derived >::bound_parser (detail::BoundVal< T > && val) inline explicit
References lyra::val().
bound_parser() [6/12]
template<typename Derived > template<typename T > lyra::bound_parser< Derived >::bound_parser (detail::BoundVal< T > && val, std::string const & hint) inline
References lyra::val().
bound_parser() [7/12]
template<typename Derived > lyra::bound_parser< Derived >::bound_parser (std::shared_ptr< detail::BoundRef > const & ref) inline explicit protected
References lyra::bound_parser< Derived >::m_cardinality, and lyra::bound_parser< Derived >::m_ref.
bound_parser() [8/12]
template<typename Derived > lyra::bound_parser< Derived >::bound_parser (std::shared_ptr< detail::BoundRef > const & ref, std::string const & hint) inline protected
References lyra::bound_parser< Derived >::m_cardinality, and lyra::bound_parser< Derived >::m_ref.
bound_parser() [9/12]
template<typename Derived > template<typename Reference > lyra::bound_parser< Derived >::bound_parser (Reference & ref, std::string const & hint)
bound_parser() [10/12]
template<typename Derived > template<typename Lambda > lyra::bound_parser< Derived >::bound_parser (Lambda const & ref, std::string const & hint, typename std::enable_if< detail::is_invocable< Lambda >::value, ctor_lambda_e >::type = ctor_lambda_e::val)
bound_parser() [11/12]
template<typename Derived > template<typename T > lyra::bound_parser< Derived >::bound_parser (detail::BoundVal< T > && val) inline explicit
References lyra::val().
bound_parser() [12/12]
template<typename Derived > template<typename T > lyra::bound_parser< Derived >::bound_parser (detail::BoundVal< T > && val, std::string const & hint) inline
References lyra::val().
Member Function Documentation
cardinality() [1/6]
template<typename Derived > detail::parser_cardinality lyra::bound_parser< Derived >::cardinality () const inline override virtual
Reimplemented from lyra::parser.
References lyra::bound_parser< Derived >::m_cardinality.
cardinality() [2/6]
template<typename Derived > detail::parser_cardinality lyra::bound_parser< Derived >::cardinality () const inline override virtual
Reimplemented from lyra::parser.
References lyra::bound_parser< Derived >::m_cardinality.
cardinality() [3/6]
template<typename Derived > Derived & lyra::bound_parser< Derived >::cardinality (size_t n)
Referenced by main().
cardinality() [4/6]
template<typename Derived > Derived & lyra::bound_parser< Derived >::cardinality (size_t n)
cardinality() [5/6]
template<typename Derived > Derived & lyra::bound_parser< Derived >::cardinality (size_t n, size_t m)
cardinality() [6/6]
template<typename Derived > Derived & lyra::bound_parser< Derived >::cardinality (size_t n, size_t m)
choices() [1/6]
template<typename Derived > template<typename T , std::size_t N> Derived & lyra::bound_parser< Derived >::choices (const T(&) choice_values[N])
choices() [2/6]
template<typename Derived > template<typename T , std::size_t N> Derived & lyra::bound_parser< Derived >::choices (const T(&) choice_values[N])
choices() [3/6]
template<typename Derived > template<typename Lambda , typename std::enable_if< detail::is_invocable< Lambda >::value, int >::type > Derived & lyra::bound_parser< Derived >::choices (Lambda const & check_choice)
choices() [4/6]
template<typename Derived > template<typename Lambda , typename std::enable_if< detail::is_invocable< Lambda >::value, int >::type = 1> Derived & lyra::bound_parser< Derived >::choices (Lambda const & check_choice)
choices() [5/6]
template<typename Derived > template<typename T , typename... Rest, typename std::enable_if<!detail::is_invocable< T >::value, int >::type > Derived & lyra::bound_parser< Derived >::choices (T val0, Rest... rest)
Referenced by main().
choices() [6/6]
template<typename Derived > template<typename T , typename... Rest, typename std::enable_if<!detail::is_invocable< T >::value, int >::type = 0> Derived & lyra::bound_parser< Derived >::choices (T val0, Rest... rest)
clone() [1/2]
template<typename Derived > virtual std::unique_ptr< parser > lyra::bound_parser< Derived >::clone () const inline override virtual
Reimplemented from lyra::parser.
Reimplemented in lyra::opt, lyra::help, lyra::help, and lyra::opt.
clone() [2/2]
template<typename Derived > virtual std::unique_ptr< parser > lyra::bound_parser< Derived >::clone () const inline override virtual
Reimplemented from lyra::parser.
Reimplemented in lyra::opt, lyra::help, lyra::help, and lyra::opt.
get_value() [1/2]
template<typename Derived > virtual std::string lyra::bound_parser< Derived >::get_value (size_t i) const inline override virtual
Reimplemented from lyra::parser.
References lyra::bound_parser< Derived >::m_ref.
get_value() [2/2]
template<typename Derived > virtual std::string lyra::bound_parser< Derived >::get_value (size_t i) const inline override virtual
Reimplemented from lyra::parser.
References lyra::bound_parser< Derived >::m_ref.
get_value_count() [1/2]
template<typename Derived > virtual size_t lyra::bound_parser< Derived >::get_value_count () const inline override virtual
Reimplemented from lyra::parser.
References lyra::bound_parser< Derived >::m_ref.
get_value_count() [2/2]
template<typename Derived > virtual size_t lyra::bound_parser< Derived >::get_value_count () const inline override virtual
Reimplemented from lyra::parser.
References lyra::bound_parser< Derived >::m_ref.
help() [1/2]
template<typename Derived > Derived & lyra::bound_parser< Derived >::help (const std::string & text)
Referenced by main(), and lyra::main::operator()().
help() [2/2]
template<typename Derived > Derived & lyra::bound_parser< Derived >::help (const std::string & text)
hint() [1/4]
template<typename Derived > std::string lyra::bound_parser< Derived >::hint
hint() [2/4]
template<typename Derived > std::string lyra::bound_parser< Derived >::hint () const
hint() [3/4]
template<typename Derived > Derived & lyra::bound_parser< Derived >::hint (std::string const & hint)
hint() [4/4]
template<typename Derived > Derived & lyra::bound_parser< Derived >::hint (std::string const & hint)
is_named() [1/2]
template<typename Derived > virtual bool lyra::bound_parser< Derived >::is_named (const std::string & n) const inline override virtual
Reimplemented from lyra::parser.
Reimplemented in lyra::opt, and lyra::opt.
References lyra::bound_parser< Derived >::m_hint.
Referenced by lyra::opt::is_named().
is_named() [2/2]
template<typename Derived > virtual bool lyra::bound_parser< Derived >::is_named (const std::string & n) const inline override virtual
Reimplemented from lyra::parser.
Reimplemented in lyra::opt, and lyra::opt.
References lyra::bound_parser< Derived >::m_hint.
operator()() [1/2]
template<typename Derived > Derived & lyra::bound_parser< Derived >::operator() (std::string const & description)
operator()() [2/2]
template<typename Derived > Derived & lyra::bound_parser< Derived >::operator() (std::string const & description)
optional() [1/2]
template<typename Derived > Derived & lyra::bound_parser< Derived >::optional
Referenced by main(), and lyra::main::operator()().
optional() [2/2]
template<typename Derived > Derived & lyra::bound_parser< Derived >::optional ()
required() [1/2]
template<typename Derived > Derived & lyra::bound_parser< Derived >::required (size_t n = 1)
Referenced by main().
required() [2/2]
template<typename Derived > Derived & lyra::bound_parser< Derived >::required (size_t n = 1)
Member Data Documentation
m_cardinality
template<typename Derived > detail::parser_cardinality lyra::bound_parser< Derived >::m_cardinality protected
Referenced by lyra::bound_parser< Derived >::bound_parser(), and lyra::bound_parser< Derived >::cardinality().
m_description
template<typename Derived > std::string lyra::bound_parser< Derived >::m_description protected
m_hint
template<typename Derived > std::string lyra::bound_parser< Derived >::m_hint protected
Referenced by lyra::bound_parser< Derived >::is_named().
m_ref
template<typename Derived > std::shared_ptr< detail::BoundRef > lyra::bound_parser< Derived >::m_ref protected
Referenced by lyra::bound_parser< Derived >::bound_parser(), lyra::bound_parser< Derived >::get_value(), and lyra::bound_parser< Derived >::get_value_count().
value_choices
template<typename Derived > std::shared_ptr< detail::choices_base > lyra::bound_parser< Derived >::value_choices protected
The documentation for this class was generated from the following files:
Lyra/data/single_include/lyra/lyra.hpp
Lyra/include/lyra/parser.hpp