???: MainNamespace::PointerArray< BaseValues, length, ActualValue > Class Template Reference
MainNamespace::PointerArray< BaseValues, length, ActualValue > Class Template Reference
#include <arrays.h>
Public Member Functions
PointerArray ()
PointerArray (PointerArray &&other)
~PointerArray ()
void clear ()
template<class Enumerator >
ActualValue & operator[] (Enumerator const idx)
template<class Enumerator >
ActualValue operator[] (Enumerator const idx) const
ActualValue & operator[] (size_t const idx)
ActualValue operator[] (size_t const idx) const
Constructor & Destructor Documentation
PointerArray() [1/2]
template<class BaseValues , size_t length, class ActualValue = std::add_pointer_t<BaseValues>> MainNamespace::PointerArray< BaseValues, length, ActualValue >::PointerArray () inline
PointerArray() [2/2]
template<class BaseValues , size_t length, class ActualValue = std::add_pointer_t<BaseValues>> MainNamespace::PointerArray< BaseValues, length, ActualValue >::PointerArray (PointerArray< BaseValues, length, ActualValue > && other) inline
~PointerArray()
template<class BaseValues , size_t length, class ActualValue = std::add_pointer_t<BaseValues>> MainNamespace::PointerArray< BaseValues, length, ActualValue >::~PointerArray () inline
References MainNamespace::PointerArray< BaseValues, length, ActualValue >::clear().
Member Function Documentation
clear()
template<class BaseValues , size_t length, class ActualValue = std::add_pointer_t<BaseValues>> void MainNamespace::PointerArray< BaseValues, length, ActualValue >::clear () inline
References MainNamespace::maybeFree().
Referenced by MainNamespace::PointerArray< BaseValues, length, ActualValue >::~PointerArray().
operator[]() [1/4]
template<class BaseValues , size_t length, class ActualValue = std::add_pointer_t<BaseValues>> template<class Enumerator > ActualValue & MainNamespace::PointerArray< BaseValues, length, ActualValue >::operator[] (Enumerator const idx) inline
References MainNamespace::getUnderlying(), and MainNamespace::PointerArray< BaseValues, length, ActualValue >::operator[]().
operator[]() [2/4]
template<class BaseValues , size_t length, class ActualValue = std::add_pointer_t<BaseValues>> template<class Enumerator > ActualValue MainNamespace::PointerArray< BaseValues, length, ActualValue >::operator[] (Enumerator const idx) const inline
References MainNamespace::getUnderlying(), and MainNamespace::PointerArray< BaseValues, length, ActualValue >::operator[]().
operator[]() [3/4]
template<class BaseValues , size_t length, class ActualValue = std::add_pointer_t<BaseValues>> ActualValue & MainNamespace::PointerArray< BaseValues, length, ActualValue >::operator[] (size_t const idx) inline
operator[]() [4/4]
template<class BaseValues , size_t length, class ActualValue = std::add_pointer_t<BaseValues>> ActualValue MainNamespace::PointerArray< BaseValues, length, ActualValue >::operator[] (size_t const idx) const inline
Referenced by MainNamespace::PointerArray< BaseValues, length, ActualValue >::operator[]().
The documentation for this class was generated from the following file:
utils/arrays.h