Skeletal: lyra::printer Class Reference
lyra::printer Class Reference abstract
#include <printer.hpp>
Public Member Functions
virtual ~printer ()=default
virtual ~printer ()=default
virtual printer & heading (const std::string &txt)=0
virtual printer & heading (const std::string &txt)=0
virtual printer & option (const std::string &opt, const std::string &description, std::size_t indent=0)=0
virtual printer & option (const std::string &opt, const std::string &description, std::size_t indent=0)=0
virtual printer & paragraph (const std::string &txt, std::size_t indent=0)=0
virtual printer & paragraph (const std::string &txt, std::size_t indent=0)=0
Constructor & Destructor Documentation
~printer() [1/2]
virtual lyra::printer::~printer () virtual default
~printer() [2/2]
virtual lyra::printer::~printer () virtual default
Member Function Documentation
heading() [1/2]
virtual printer & lyra::printer::heading (const std::string & txt) pure virtual
Implemented in lyra::ostream_printer, and lyra::ostream_printer.
Referenced by lyra::parser::print_help_text_details(), lyra::command::print_help_text_details(), and lyra::parser::print_help_text_summary().
heading() [2/2]
virtual printer & lyra::printer::heading (const std::string & txt) pure virtual
Implemented in lyra::ostream_printer, and lyra::ostream_printer.
option() [1/2]
virtual printer & lyra::printer::option (const std::string & opt, const std::string & description, std::size_t indent = 0) pure virtual
Implemented in lyra::ostream_printer, and lyra::ostream_printer.
Referenced by lyra::parser::print_help_text_details(), and lyra::command::print_help_text_details().
option() [2/2]
virtual printer & lyra::printer::option (const std::string & opt, const std::string & description, std::size_t indent = 0) pure virtual
Implemented in lyra::ostream_printer, and lyra::ostream_printer.
paragraph() [1/2]
virtual printer & lyra::printer::paragraph (const std::string & txt, std::size_t indent = 0) pure virtual
Implemented in lyra::ostream_printer, and lyra::ostream_printer.
Referenced by lyra::parser::print_help_text_summary().
paragraph() [2/2]
virtual printer & lyra::printer::paragraph (const std::string & txt, std::size_t indent = 0) pure virtual
Implemented in lyra::ostream_printer, and lyra::ostream_printer.
The documentation for this class was generated from the following files:
Lyra/data/single_include/lyra/lyra.hpp
Lyra/include/lyra/printer.hpp