Skeletal: lyra::help Class Reference
lyra::help Class Reference
#include <help.hpp>
Public Member Functions
help (bool &showHelpFlag)
help (bool &showHelpFlag)
virtual std::unique_ptr< parser > clone () const override
virtual std::unique_ptr< parser > clone () const override
help & description (const std::string &text)
help & description (const std::string &text)
virtual std::string get_description_text (const option_style &) const override
virtual std::string get_description_text (const option_style &) const override
Public Member Functions inherited from lyra::opt
opt (bool &ref)
opt (bool &ref)
template<typename T >
opt (detail::BoundVal< T > &&val)
template<typename T >
opt (detail::BoundVal< T > &&val)
template<typename T >
opt (detail::BoundVal< T > &&val, std::string const &hint)
template<typename T >
opt (detail::BoundVal< T > &&val, std::string const &hint)
template<typename L >
opt (L const &ref, std::string const &hint, typename std::enable_if< detail::is_invocable< L >::value, ctor_lambda_e >::type=ctor_lambda_e::val)
template<typename L >
opt (L const &ref, std::string const &hint, typename std::enable_if< detail::is_invocable< L >::value, ctor_lambda_e >::type=ctor_lambda_e::val)
template<typename L >
opt (L const &ref, std::string const &hint, typename std::enable_if< detail::is_invocable< L >::value, opt::ctor_lambda_e >::type)
template<typename L >
opt (L const &ref, typename std::enable_if< detail::is_invocable< L >::value, ctor_lambda_e >::type=ctor_lambda_e::val)
template<typename L >
opt (L const &ref, typename std::enable_if< detail::is_invocable< L >::value, ctor_lambda_e >::type=ctor_lambda_e::val)
template<typename L >
opt (L const &ref, typename std::enable_if< detail::is_invocable< L >::value, opt::ctor_lambda_e >::type)
template<typename T >
opt (T &ref, std::string const &hint, typename std::enable_if<!detail::is_invocable< T >::value, ctor_ref_e >::type=ctor_ref_e::val)
template<typename T >
opt (T &ref, std::string const &hint, typename std::enable_if<!detail::is_invocable< T >::value, ctor_ref_e >::type=ctor_ref_e::val)
template<typename T >
opt (T &ref, std::string const &hint, typename std::enable_if<!detail::is_invocable< T >::value, opt::ctor_ref_e >::type)
virtual std::unique_ptr< parser > clone () const override
virtual std::unique_ptr< parser > clone () const override
virtual help_text get_help_text (const option_style &style) const override
virtual help_text get_help_text (const option_style &style) const override
virtual std::string get_usage_text (const option_style &style) const override
virtual std::string get_usage_text (const option_style &style) const override
virtual bool is_named (const std::string &n) const override
virtual bool is_named (const std::string &n) const override
opt & name (const std::string &opt_name)
opt & name (const std::string &opt_name)
opt & operator[] (std::string const &opt_name)
opt & operator[] (std::string const &opt_name)
parse_result parse (detail::token_iterator const &tokens, const option_style &style) const override
parse_result parse (detail::token_iterator const &tokens, const option_style &style) const override
virtual parse_result parse (detail::token_iterator const &tokens, const option_style &style) const=0
virtual parse_result parse (detail::token_iterator const &tokens, const option_style &style) const=0
virtual parse_result parse (detail::token_iterator const &tokens, const option_style &style) const=0
virtual parse_result parse (detail::token_iterator const &tokens, const option_style &style) const=0
result validate () const override
result validate () const override
Public Member Functions inherited from lyra::bound_parser< opt >
bound_parser (detail::BoundVal< T > &&val)
bound_parser (detail::BoundVal< T > &&val)
bound_parser (detail::BoundVal< T > &&val, std::string const &hint)
bound_parser (detail::BoundVal< T > &&val, std::string const &hint)
bound_parser (Lambda const &ref, std::string const &hint, typename std::enable_if< detail::is_invocable< Lambda >::value, ctor_lambda_e >::type=ctor_lambda_e::val)
bound_parser (Lambda const &ref, std::string const &hint, typename std::enable_if< detail::is_invocable< Lambda >::value, ctor_lambda_e >::type=ctor_lambda_e::val)
bound_parser (Reference &ref, std::string const &hint)
bound_parser (Reference &ref, std::string const &hint)
detail::parser_cardinality cardinality () const override
detail::parser_cardinality cardinality () const override
opt & cardinality (size_t n)
opt & cardinality (size_t n)
opt & cardinality (size_t n, size_t m)
opt & cardinality (size_t n, size_t m)
opt & choices (const T(&choice_values)[N])
opt & choices (const T(&choice_values)[N])
opt & choices (Lambda const &check_choice)
opt & choices (Lambda const &check_choice)
opt & choices (T val0, Rest... rest)
opt & choices (T val0, Rest... rest)
virtual std::unique_ptr< parser > clone () const override
virtual std::unique_ptr< parser > clone () const override
virtual std::string get_value (size_t i) const override
virtual std::string get_value (size_t i) const override
virtual size_t get_value_count () const override
virtual size_t get_value_count () const override
opt & help (const std::string &text)
opt & help (const std::string &text)
std::string hint () const
std::string hint () const
opt & hint (std::string const &hint)
opt & hint (std::string const &hint)
virtual bool is_named (const std::string &n) const override
virtual bool is_named (const std::string &n) const override
opt & operator() (std::string const &description)
opt & operator() (std::string const &description)
opt & optional ()
opt & optional ()
opt & required (size_t n=1)
opt & required (size_t n=1)
Public Member Functions inherited from lyra::parser
virtual ~parser ()=default
virtual ~parser ()=default
virtual detail::parser_cardinality cardinality () const
virtual detail::parser_cardinality cardinality () const
virtual std::unique_ptr< parser > clone () const
virtual std::unique_ptr< parser > clone () const
std::string get_description_text () const
std::string get_description_text () const
virtual std::string get_description_text (const option_style &) const
virtual std::string get_description_text (const option_style &) const
help_text get_help_text () const
help_text get_help_text () const
virtual help_text get_help_text (const option_style &) const
virtual help_text get_help_text (const option_style &) const
virtual const parser * get_named (const std::string &n) const
virtual const parser * get_named (const std::string &n) const
std::string get_usage_text () const
std::string get_usage_text () const
virtual std::string get_usage_text (const option_style &) const
virtual std::string get_usage_text (const option_style &) const
virtual std::string get_value (size_t i) const
virtual std::string get_value (size_t i) const
virtual size_t get_value_count () const
virtual size_t get_value_count () const
virtual bool is_group () const
virtual bool is_group () const
virtual bool is_named (const std::string &n) const
virtual bool is_named (const std::string &n) const
bool is_optional () const
bool is_optional () const
virtual parse_result parse (detail::token_iterator const &tokens, const option_style &style) const =0
virtual parse_result parse (detail::token_iterator const &tokens, const option_style &style) const =0
virtual result validate () const
virtual result validate () const
Private Attributes
std::string description_text
Additional Inherited Members
Public Types inherited from lyra::opt
enum class ctor_lambda_e { val , val }
enum class ctor_lambda_e { val , val }
enum class ctor_ref_e { val , val }
enum class ctor_ref_e { val , val }
Public Types inherited from lyra::bound_parser< opt >
enum ctor_lambda_e
enum ctor_lambda_e
Public Types inherited from lyra::parser
using help_text = std::vector< help_text_item >
using help_text = std::vector< help_text_item >
Protected Member Functions inherited from lyra::opt
std::string format_opt (std::string const &opt_name, const option_style &style) const
std::string format_opt (std::string const &opt_name, const option_style &style) const
bool is_match (std::string const &opt_name, const option_style &style) const
bool is_match (std::string const &opt_name, const option_style &style) const
std::string normalise_opt (std::string const &opt_name, const option_style &style) const
std::string normalise_opt (std::string const &opt_name, const option_style &style) const
Protected Member Functions inherited from lyra::bound_parser< opt >
bound_parser (std::shared_ptr< detail::BoundRef > const &ref)
bound_parser (std::shared_ptr< detail::BoundRef > const &ref)
bound_parser (std::shared_ptr< detail::BoundRef > const &ref, std::string const &hint)
bound_parser (std::shared_ptr< detail::BoundRef > const &ref, std::string const &hint)
Protected Member Functions inherited from lyra::parser
virtual void print_help_text (printer &p, const option_style &style) const
virtual void print_help_text (printer &p, const option_style &style) const
virtual void print_help_text_details (printer &p, const option_style &style) const
virtual void print_help_text_details (printer &p, const option_style &style) const
virtual void print_help_text_summary (printer &p, const option_style &style) const
virtual void print_help_text_summary (printer &p, const option_style &style) const
Protected Attributes inherited from lyra::opt
std::vector< std::string > opt_names
Protected Attributes inherited from lyra::bound_parser< opt >
detail::parser_cardinality m_cardinality
std::string m_description
std::string m_hint
std::shared_ptr< detail::BoundRef > m_ref
std::shared_ptr< detail::choices_base > value_choices
Constructor & Destructor Documentation
help() [1/2]
lyra::help::help (bool & showHelpFlag) inline
References lyra::detail::basic_result< T >::ok(), and lyra::short_circuit_all.
help() [2/2]
lyra::help::help (bool & showHelpFlag) inline
References lyra::detail::basic_result< T >::ok(), and lyra::short_circuit_all.
Member Function Documentation
clone() [1/2]
virtual std::unique_ptr< parser > lyra::help::clone () const inline override virtual
Reimplemented from lyra::opt.
clone() [2/2]
virtual std::unique_ptr< parser > lyra::help::clone () const inline override virtual
Reimplemented from lyra::opt.
description() [1/2]
help & lyra::help::description (const std::string & text) inline
References description_text.
Referenced by main().
description() [2/2]
help & lyra::help::description (const std::string & text)
get_description_text() [1/2]
virtual std::string lyra::help::get_description_text (const option_style &) const inline override virtual
Reimplemented from lyra::parser.
References description_text.
get_description_text() [2/2]
virtual std::string lyra::help::get_description_text (const option_style &) const inline override virtual
Reimplemented from lyra::parser.
References description_text.
Member Data Documentation
description_text
std::string lyra::help::description_text private
Referenced by description(), and get_description_text().
The documentation for this class was generated from the following files:
Lyra/data/single_include/lyra/lyra.hpp
Lyra/include/lyra/help.hpp