???: MainNamespace::MeshReader Class Reference
MainNamespace::MeshReader Class Reference
#include <meshreader.h>
Public Types
enum class View : size_t {
solution , rhs , offset , error ,
COUNT
}
Public Member Functions
MeshReader ()
~MeshReader ()
Mesh & mesh ()
Mesh const & mesh () const
void parseMesh (std::string const filename)
Parse a gmsh mesh file into a surface3d structure. The mesh_ object is filled in the appropriate way.
void saveView (View const type, avector const *const data)
Save the Cauchy data associated to the mesh, with the given name.
Private Member Functions
void fromGmshIndices ()
Decrease all indices by 1 to make them 0-based.
void readData ()
void toGmshIndices ()
Increase all indices by 1 to make them 1-based, as per GMSH conventions.
Private Attributes
std::vector< size_t > elementTag_
Reordering of the triangle () tags (forward map: index j stores the tag of the element in that position). It belongs here since it is only useful when interacting with gmsh.
std::array< bool, size< View >()> enabled_
Enabled views.
std::string fileName_ = ""
File name for the mesh.
Mesh mesh_
Mesh object.
std::string modelName_ = ""
Model name (as seen by gmsh).
std::vector< size_t > nodeTag_
Reordering of the vertex (node) tags (forward map: index j stores the tag of the element in that position). It belongs here since it is only useful when interacting with gmsh.
std::vector< size_t > reordering_
Reordering of the triangles and vertices tags (reverse map: index j stores the position of the element with tag j+1). It belongs here since it is only useful when interacting with gmsh.
std::array< size_t, size< View >()> step_ = {0,0,0,0}
std::array< int, 2 *size< View >()> viewTags_
Mapping view tags from type to tags.
Member Enumeration Documentation
View
enum class MainNamespace::MeshReader::View : size_t strong
Enumerator
solution
rhs
offset
error
COUNT
Constructor & Destructor Documentation
MeshReader()
MainNamespace::MeshReader::MeshReader ()
References enabled_, error, MainNamespace::getUnderlying(), MainNamespace::names, offset, rhs, MainNamespace::saveError(), MainNamespace::saveOffset(), MainNamespace::saveRhs(), MainNamespace::saveSolution(), solution, and viewTags_.
~MeshReader()
MainNamespace::MeshReader::~MeshReader ()
References MainNamespace::Logger::blue, enabled_, fileName_, MainNamespace::Logger::log(), MainNamespace::names, MainNamespace::outputDirectory(), and viewTags_.
Member Function Documentation
fromGmshIndices()
void MainNamespace::MeshReader::fromGmshIndices () private
Decrease all indices by 1 to make them 0-based.
mesh() [1/2]
Mesh & MainNamespace::MeshReader::mesh () inline
References mesh_.
Referenced by MainNamespace::Surface::getFromFile(), and MainNamespace::Surface::MultiSurface::mesh().
mesh() [2/2]
Mesh const & MainNamespace::MeshReader::mesh () const inline
References mesh_.
parseMesh()
void MainNamespace::MeshReader::parseMesh (std::string const filename)
Parse a gmsh mesh file into a surface3d structure. The mesh_ object is filled in the appropriate way.
Parameters
filename Name of the meshfile to parse.
References MainNamespace::buildSurface(), MainNamespace::dirichletName, elementTag_, fileName_, MainNamespace::getElements(), MainNamespace::Logger::green, MainNamespace::Logger::log(), MainNamespace::Logger::magenta, MainNamespace::Mesh::membership_, MainNamespace::Mesh::mesh_, mesh_, modelName_, MainNamespace::neumannName, MainNamespace::nodesIdx, nodeTag_, MainNamespace::parseNodesPhysical(), MainNamespace::reorderElements(), reordering_, MainNamespace::size(), MainNamespace::splitTriangles(), MainNamespace::Mesh::triangles(), computemeshsize::triangles, MainNamespace::trianglesIdx, and MainNamespace::Mesh::vertices().
Referenced by MainNamespace::Surface::getFromFile().
readData()
void MainNamespace::MeshReader::readData () private
saveView()
void MainNamespace::MeshReader::saveView (View const type, avector const *const data)
Save the Cauchy data associated to the mesh, with the given name.
Parameters
type Name for the view.
data Data to represent.
References MainNamespace::Logger::cyan, elementTag_, enabled_, MainNamespace::getUnderlying(), MainNamespace::Logger::log(), mesh_, modelName_, nodeTag_, step_, MainNamespace::Mesh::triangleDofs_, MainNamespace::Mesh::triangles(), MainNamespace::Mesh::vertexDofs_, MainNamespace::Mesh::vertices(), and viewTags_.
Referenced by MainNamespace::Surface::SingleSurface::computeDifferenceNorm(), MainNamespace::Surface::MultiSurface::error(), MainNamespace::Surface::SingleSurface::makeOffset(), and MainNamespace::Surface::MultiSurface::solve().
toGmshIndices()
void MainNamespace::MeshReader::toGmshIndices () private
Increase all indices by 1 to make them 1-based, as per GMSH conventions.
Member Data Documentation
elementTag_
std::vector<size_t> MainNamespace::MeshReader::elementTag_ private
Reordering of the triangle () tags (forward map: index j stores the tag of the element in that position). It belongs here since it is only useful when interacting with gmsh.
Referenced by parseMesh(), and saveView().
enabled_
std::array<bool,size<View>()> MainNamespace::MeshReader::enabled_ private
Enabled views.
Referenced by MeshReader(), ~MeshReader(), and saveView().
fileName_
std::string MainNamespace::MeshReader::fileName_ = "" private
File name for the mesh.
Referenced by ~MeshReader(), and parseMesh().
mesh_
Mesh MainNamespace::MeshReader::mesh_ private
Mesh object.
Referenced by mesh(), parseMesh(), and saveView().
modelName_
std::string MainNamespace::MeshReader::modelName_ = "" private
Model name (as seen by gmsh).
Referenced by parseMesh(), and saveView().
nodeTag_
std::vector<size_t> MainNamespace::MeshReader::nodeTag_ private
Reordering of the vertex (node) tags (forward map: index j stores the tag of the element in that position). It belongs here since it is only useful when interacting with gmsh.
Referenced by parseMesh(), and saveView().
reordering_
std::vector<size_t> MainNamespace::MeshReader::reordering_ private
Reordering of the triangles and vertices tags (reverse map: index j stores the position of the element with tag j+1). It belongs here since it is only useful when interacting with gmsh.
Referenced by parseMesh().
step_
std::array<size_t, size<View>()> MainNamespace::MeshReader::step_ = {0,0,0,0} private
Referenced by saveView().
viewTags_
std::array<int,2*size<View>()> MainNamespace::MeshReader::viewTags_ private
Mapping view tags from type to tags.
Referenced by MeshReader(), ~MeshReader(), and saveView().
The documentation for this class was generated from the following files:
main/meshreader.h
main/meshreader.cpp