???: lyra::literal Class Reference
lyra::literal Class Reference
#include <literal.hpp>
Public Member Functions
literal (std::string const &n)
literal (std::string const &n)
virtual detail::parser_cardinality cardinality () const override
virtual detail::parser_cardinality cardinality () const override
virtual std::unique_ptr< parser > clone () const override
virtual std::unique_ptr< parser > clone () const override
virtual std::string get_description_text (const option_style &) const override
virtual std::string get_description_text (const option_style &) const override
virtual help_text get_help_text (const option_style &) const override
virtual help_text get_help_text (const option_style &) const override
virtual std::string get_usage_text (const option_style &) const override
virtual std::string get_usage_text (const option_style &) const override
literal & help (const std::string &help_description_text)
literal & help (const std::string &help_description_text)
literal & operator() (std::string const &help_description_text)
literal & operator() (std::string const &help_description_text)
virtual parse_result parse (detail::token_iterator const &tokens, const option_style &) const override
virtual parse_result parse (detail::token_iterator const &tokens, const option_style &) const override
virtual parse_result parse (detail::token_iterator const &tokens, const option_style &style) const=0
virtual parse_result parse (detail::token_iterator const &tokens, const option_style &style) const=0
virtual parse_result parse (detail::token_iterator const &tokens, const option_style &style) const=0
virtual parse_result parse (detail::token_iterator const &tokens, const option_style &style) const=0
Public Member Functions inherited from lyra::parser
virtual ~parser ()=default
virtual ~parser ()=default
virtual detail::parser_cardinality cardinality () const
virtual detail::parser_cardinality cardinality () const
virtual std::unique_ptr< parser > clone () const
virtual std::unique_ptr< parser > clone () const
std::string get_description_text () const
std::string get_description_text () const
virtual std::string get_description_text (const option_style &) const
virtual std::string get_description_text (const option_style &) const
help_text get_help_text () const
help_text get_help_text () const
virtual help_text get_help_text (const option_style &) const
virtual help_text get_help_text (const option_style &) const
virtual const parser * get_named (const std::string &n) const
virtual const parser * get_named (const std::string &n) const
std::string get_usage_text () const
std::string get_usage_text () const
virtual std::string get_usage_text (const option_style &) const
virtual std::string get_usage_text (const option_style &) const
virtual std::string get_value (size_t i) const
virtual std::string get_value (size_t i) const
virtual size_t get_value_count () const
virtual size_t get_value_count () const
virtual bool is_group () const
virtual bool is_group () const
virtual bool is_named (const std::string &n) const
virtual bool is_named (const std::string &n) const
bool is_optional () const
bool is_optional () const
virtual parse_result parse (detail::token_iterator const &tokens, const option_style &style) const =0
virtual parse_result parse (detail::token_iterator const &tokens, const option_style &style) const =0
virtual result validate () const
virtual result validate () const
Protected Attributes
std::string description
std::string name
Additional Inherited Members
Public Types inherited from lyra::parser
using help_text = std::vector< help_text_item >
using help_text = std::vector< help_text_item >
Protected Member Functions inherited from lyra::parser
virtual void print_help_text (printer &p, const option_style &style) const
virtual void print_help_text (printer &p, const option_style &style) const
virtual void print_help_text_details (printer &p, const option_style &style) const
virtual void print_help_text_details (printer &p, const option_style &style) const
virtual void print_help_text_summary (printer &p, const option_style &style) const
virtual void print_help_text_summary (printer &p, const option_style &style) const
Constructor & Destructor Documentation
literal() [1/2]
lyra::literal::literal (std::string const & n) inline
literal() [2/2]
lyra::literal::literal (std::string const & n)
Member Function Documentation
cardinality() [1/2]
virtual detail::parser_cardinality lyra::literal::cardinality () const inline override virtual
Reimplemented from lyra::parser.
cardinality() [2/2]
virtual detail::parser_cardinality lyra::literal::cardinality () const inline override virtual
Reimplemented from lyra::parser.
clone() [1/2]
virtual std::unique_ptr< parser > lyra::literal::clone () const inline override virtual
Reimplemented from lyra::parser.
clone() [2/2]
virtual std::unique_ptr< parser > lyra::literal::clone () const inline override virtual
Reimplemented from lyra::parser.
get_description_text() [1/2]
virtual std::string lyra::literal::get_description_text (const option_style &) const inline override virtual
Reimplemented from lyra::parser.
References description.
get_description_text() [2/2]
virtual std::string lyra::literal::get_description_text (const option_style &) const inline override virtual
Reimplemented from lyra::parser.
References description.
get_help_text() [1/2]
virtual help_text lyra::literal::get_help_text (const option_style &) const inline override virtual
Reimplemented from lyra::parser.
References description, and name.
get_help_text() [2/2]
virtual help_text lyra::literal::get_help_text (const option_style &) const inline override virtual
Reimplemented from lyra::parser.
References description, and name.
get_usage_text() [1/2]
virtual std::string lyra::literal::get_usage_text (const option_style &) const inline override virtual
Reimplemented from lyra::parser.
References name.
get_usage_text() [2/2]
virtual std::string lyra::literal::get_usage_text (const option_style &) const inline override virtual
Reimplemented from lyra::parser.
References name.
help() [1/2]
literal & lyra::literal::help (const std::string & help_description_text) inline
References description.
Referenced by operator()().
help() [2/2]
literal & lyra::literal::help (const std::string & help_description_text)
operator()() [1/2]
literal & lyra::literal::operator() (std::string const & help_description_text) inline
References help().
operator()() [2/2]
literal & lyra::literal::operator() (std::string const & help_description_text)
parse() [1/6]
virtual parse_result lyra::literal::parse (detail::token_iterator const & tokens, const option_style &) const inline override virtual
Implements lyra::parser.
References lyra::detail::token_iterator::argument(), lyra::detail::basic_result< T >::error(), lyra::matched, name, lyra::no_match, lyra::detail::basic_result< detail::parse_state >::ok(), lyra::detail::token_iterator::pop(), and lyra::parser::validate().
parse() [2/6]
virtual parse_result lyra::literal::parse (detail::token_iterator const & tokens, const option_style &) const inline override virtual
Implements lyra::parser.
References lyra::detail::token_iterator::argument(), lyra::detail::basic_result< T >::error(), lyra::matched, name, lyra::no_match, lyra::detail::basic_result< detail::parse_state >::ok(), lyra::detail::token_iterator::pop(), and lyra::parser::validate().
parse() [3/6]
virtual parse_result lyra::parser::parse (detail::token_iterator const & tokens, const option_style & style) const virtual
Implements lyra::parser.
parse() [4/6]
virtual parse_result lyra::parser::parse (detail::token_iterator const & tokens, const option_style & style) const virtual
Implements lyra::parser.
parse() [5/6]
virtual parse_result lyra::parser::parse (detail::token_iterator const & tokens, const option_style & style) const virtual
Implements lyra::parser.
parse() [6/6]
virtual parse_result lyra::parser::parse (detail::token_iterator const & tokens, const option_style & style) const virtual
Implements lyra::parser.
Member Data Documentation
description
std::string lyra::literal::description protected
Referenced by get_description_text(), get_help_text(), and help().
name
std::string lyra::literal::name protected
Referenced by get_help_text(), get_usage_text(), and parse().
The documentation for this class was generated from the following files:
Lyra/data/single_include/lyra/lyra.hpp
Lyra/include/lyra/literal.hpp