???: lyra::detail::basic_result< void > Class Reference
lyra::detail::basic_result< void > Class Reference
#include <result.hpp>
Public Types
using value_type = typename result_value_base< void >::value_type
using value_type = typename result_value_base< void >::value_type
Public Types inherited from lyra::detail::result_value_base< void >
using value_type = void
using value_type = void
Public Member Functions
basic_result (result_base const &other)
basic_result (result_base const &other)
Public Member Functions inherited from lyra::detail::result_base
result_base const & base () const
result_base const & base () const
std::string errorMessage () const
std::string errorMessage () const
bool is_ok () const
bool is_ok () const
std::string message () const
std::string message () const
operator bool () const
operator bool () const
Static Public Member Functions
static basic_result error (std::string const &message)
static basic_result error (std::string const &message)
static basic_result ok ()
static basic_result ok ()
Additional Inherited Members
Protected Types inherited from lyra::detail::result_base
enum class result_kind { ok , error , ok , error }
enum class result_kind { ok , error , ok , error }
Protected Member Functions inherited from lyra::detail::result_value_base< void >
result_value_base (const result_base &other)
result_value_base (const result_base &other)
result_value_base (result_kind kind, const std::string &message="")
result_value_base (result_kind kind, const std::string &message="")
Protected Member Functions inherited from lyra::detail::result_base
result_base (const result_base &other)
result_base (const result_base &other)
result_base (result_kind kind, const std::string &message="")
result_base (result_kind kind, const std::string &message="")
virtual ~result_base ()=default
virtual ~result_base ()=default
result_base & operator= (const result_base &)=default
result_base & operator= (const result_base &)=default
Member Typedef Documentation
value_type [1/2]
using lyra::detail::basic_result< void >::value_type = typename result_value_base<void>::value_type
value_type [2/2]
using lyra::detail::basic_result< void >::value_type = typename result_value_base<void>::value_type
Constructor & Destructor Documentation
basic_result() [1/2]
lyra::detail::basic_result< void >::basic_result (result_base const & other) inline explicit
basic_result() [2/2]
lyra::detail::basic_result< void >::basic_result (result_base const & other) inline explicit
Member Function Documentation
error() [1/2]
static basic_result lyra::detail::basic_result< void >::error (std::string const & message) inline static
References lyra::detail::basic_result< T >::basic_result(), lyra::detail::result_base::error, and lyra::detail::result_base::message().
Referenced by lyra::opt::validate().
error() [2/2]
static basic_result lyra::detail::basic_result< void >::error (std::string const & message) inline static
References lyra::detail::basic_result< T >::basic_result(), lyra::detail::result_base::error, and lyra::detail::result_base::message().
ok() [1/2]
static basic_result lyra::detail::basic_result< void >::ok () inline static
References lyra::detail::basic_result< T >::basic_result(), and lyra::detail::result_base::ok.
Referenced by lyra::parser::validate(), and lyra::arguments::validate().
ok() [2/2]
static basic_result lyra::detail::basic_result< void >::ok () inline static
References lyra::detail::basic_result< T >::basic_result(), and lyra::detail::result_base::ok.
The documentation for this class was generated from the following files:
Lyra/data/single_include/lyra/lyra.hpp
Lyra/include/lyra/detail/result.hpp