???: lyra::arg Class Reference
lyra::arg Class Reference
#include <arg.hpp>
Public Member Functions
template<typename T >
bound_parser (detail::BoundVal< T > &&val)
template<typename T >
bound_parser (detail::BoundVal< T > &&val)
template<typename T >
bound_parser (detail::BoundVal< T > &&val)
template<typename T >
bound_parser (detail::BoundVal< T > &&val)
template<typename T >
bound_parser (detail::BoundVal< T > &&val, std::string const &hint)
template<typename T >
bound_parser (detail::BoundVal< T > &&val, std::string const &hint)
template<typename T >
bound_parser (detail::BoundVal< T > &&val, std::string const &hint)
template<typename T >
bound_parser (detail::BoundVal< T > &&val, std::string const &hint)
template<typename Lambda >
bound_parser (Lambda const &ref, std::string const &hint, typename std::enable_if< detail::is_invocable< Lambda >::value, ctor_lambda_e >::type=ctor_lambda_e::val)
template<typename Lambda >
bound_parser (Lambda const &ref, std::string const &hint, typename std::enable_if< detail::is_invocable< Lambda >::value, ctor_lambda_e >::type=ctor_lambda_e::val)
template<typename Lambda >
bound_parser (Lambda const &ref, std::string const &hint, typename std::enable_if< detail::is_invocable< Lambda >::value, ctor_lambda_e >::type=ctor_lambda_e::val)
template<typename Lambda >
bound_parser (Lambda const &ref, std::string const &hint, typename std::enable_if< detail::is_invocable< Lambda >::value, ctor_lambda_e >::type=ctor_lambda_e::val)
template<typename Reference >
bound_parser (Reference &ref, std::string const &hint)
template<typename Reference >
bound_parser (Reference &ref, std::string const &hint)
template<typename Reference >
bound_parser (Reference &ref, std::string const &hint)
template<typename Reference >
bound_parser (Reference &ref, std::string const &hint)
bound_parser (std::shared_ptr< detail::BoundRef > const &ref)
bound_parser (std::shared_ptr< detail::BoundRef > const &ref)
bound_parser (std::shared_ptr< detail::BoundRef > const &ref)
bound_parser (std::shared_ptr< detail::BoundRef > const &ref)
bound_parser (std::shared_ptr< detail::BoundRef > const &ref, std::string const &hint)
bound_parser (std::shared_ptr< detail::BoundRef > const &ref, std::string const &hint)
bound_parser (std::shared_ptr< detail::BoundRef > const &ref, std::string const &hint)
bound_parser (std::shared_ptr< detail::BoundRef > const &ref, std::string const &hint)
virtual help_text get_help_text (const option_style &style) const override
virtual help_text get_help_text (const option_style &style) const override
virtual std::string get_usage_text (const option_style &) const override
virtual std::string get_usage_text (const option_style &) const override
parse_result parse (detail::token_iterator const &tokens, const option_style &style) const override
parse_result parse (detail::token_iterator const &tokens, const option_style &style) const override
virtual parse_result parse (detail::token_iterator const &tokens, const option_style &style) const=0
virtual parse_result parse (detail::token_iterator const &tokens, const option_style &style) const=0
virtual parse_result parse (detail::token_iterator const &tokens, const option_style &style) const=0
virtual parse_result parse (detail::token_iterator const &tokens, const option_style &style) const=0
Public Member Functions inherited from lyra::bound_parser< arg >
bound_parser (detail::BoundVal< T > &&val)
bound_parser (detail::BoundVal< T > &&val)
bound_parser (detail::BoundVal< T > &&val, std::string const &hint)
bound_parser (detail::BoundVal< T > &&val, std::string const &hint)
bound_parser (Lambda const &ref, std::string const &hint, typename std::enable_if< detail::is_invocable< Lambda >::value, ctor_lambda_e >::type=ctor_lambda_e::val)
bound_parser (Lambda const &ref, std::string const &hint, typename std::enable_if< detail::is_invocable< Lambda >::value, ctor_lambda_e >::type=ctor_lambda_e::val)
bound_parser (Reference &ref, std::string const &hint)
bound_parser (Reference &ref, std::string const &hint)
detail::parser_cardinality cardinality () const override
detail::parser_cardinality cardinality () const override
arg & cardinality (size_t n)
arg & cardinality (size_t n)
arg & cardinality (size_t n, size_t m)
arg & cardinality (size_t n, size_t m)
arg & choices (const T(&choice_values)[N])
arg & choices (const T(&choice_values)[N])
arg & choices (Lambda const &check_choice)
arg & choices (Lambda const &check_choice)
arg & choices (T val0, Rest... rest)
arg & choices (T val0, Rest... rest)
virtual std::unique_ptr< parser > clone () const override
virtual std::unique_ptr< parser > clone () const override
virtual std::string get_value (size_t i) const override
virtual std::string get_value (size_t i) const override
virtual size_t get_value_count () const override
virtual size_t get_value_count () const override
arg & help (const std::string &text)
arg & help (const std::string &text)
std::string hint () const
std::string hint () const
arg & hint (std::string const &hint)
arg & hint (std::string const &hint)
virtual bool is_named (const std::string &n) const override
virtual bool is_named (const std::string &n) const override
arg & operator() (std::string const &description)
arg & operator() (std::string const &description)
arg & optional ()
arg & optional ()
arg & required (size_t n=1)
arg & required (size_t n=1)
Public Member Functions inherited from lyra::parser
virtual ~parser ()=default
virtual ~parser ()=default
virtual detail::parser_cardinality cardinality () const
virtual detail::parser_cardinality cardinality () const
virtual std::unique_ptr< parser > clone () const
virtual std::unique_ptr< parser > clone () const
std::string get_description_text () const
std::string get_description_text () const
virtual std::string get_description_text (const option_style &) const
virtual std::string get_description_text (const option_style &) const
help_text get_help_text () const
help_text get_help_text () const
virtual help_text get_help_text (const option_style &) const
virtual help_text get_help_text (const option_style &) const
virtual const parser * get_named (const std::string &n) const
virtual const parser * get_named (const std::string &n) const
std::string get_usage_text () const
std::string get_usage_text () const
virtual std::string get_usage_text (const option_style &) const
virtual std::string get_usage_text (const option_style &) const
virtual std::string get_value (size_t i) const
virtual std::string get_value (size_t i) const
virtual size_t get_value_count () const
virtual size_t get_value_count () const
virtual bool is_group () const
virtual bool is_group () const
virtual bool is_named (const std::string &n) const
virtual bool is_named (const std::string &n) const
bool is_optional () const
bool is_optional () const
virtual parse_result parse (detail::token_iterator const &tokens, const option_style &style) const =0
virtual parse_result parse (detail::token_iterator const &tokens, const option_style &style) const =0
virtual result validate () const
virtual result validate () const
Additional Inherited Members
Public Types inherited from lyra::bound_parser< arg >
enum ctor_lambda_e
enum ctor_lambda_e
Public Types inherited from lyra::parser
using help_text = std::vector< help_text_item >
using help_text = std::vector< help_text_item >
Protected Member Functions inherited from lyra::bound_parser< arg >
bound_parser (std::shared_ptr< detail::BoundRef > const &ref)
bound_parser (std::shared_ptr< detail::BoundRef > const &ref)
bound_parser (std::shared_ptr< detail::BoundRef > const &ref, std::string const &hint)
bound_parser (std::shared_ptr< detail::BoundRef > const &ref, std::string const &hint)
Protected Member Functions inherited from lyra::parser
virtual void print_help_text (printer &p, const option_style &style) const
virtual void print_help_text (printer &p, const option_style &style) const
virtual void print_help_text_details (printer &p, const option_style &style) const
virtual void print_help_text_details (printer &p, const option_style &style) const
virtual void print_help_text_summary (printer &p, const option_style &style) const
virtual void print_help_text_summary (printer &p, const option_style &style) const
Protected Attributes inherited from lyra::bound_parser< arg >
detail::parser_cardinality m_cardinality
std::string m_description
std::string m_hint
std::shared_ptr< detail::BoundRef > m_ref
std::shared_ptr< detail::choices_base > value_choices
Member Function Documentation
bound_parser() [1/24]
template<typename T > lyra::bound_parser< Derived >::bound_parser (detail::BoundVal< T > && val) inline explicit
bound_parser() [2/24]
template<typename T > lyra::bound_parser< Derived >::bound_parser (detail::BoundVal< T > && val) inline explicit
bound_parser() [3/24]
template<typename T > lyra::bound_parser< Derived >::bound_parser (detail::BoundVal< T > && val) inline explicit
bound_parser() [4/24]
template<typename T > lyra::bound_parser< Derived >::bound_parser (detail::BoundVal< T > && val) inline explicit
bound_parser() [5/24]
template<typename T > lyra::bound_parser< Derived >::bound_parser (detail::BoundVal< T > && val, std::string const & hint) inline
bound_parser() [6/24]
template<typename T > lyra::bound_parser< Derived >::bound_parser (detail::BoundVal< T > && val, std::string const & hint) inline
bound_parser() [7/24]
template<typename T > lyra::bound_parser< Derived >::bound_parser (detail::BoundVal< T > && val, std::string const & hint) inline
bound_parser() [8/24]
template<typename T > lyra::bound_parser< Derived >::bound_parser (detail::BoundVal< T > && val, std::string const & hint) inline
bound_parser() [9/24]
template<typename Lambda > lyra::bound_parser< Derived >::bound_parser (Lambda const & ref, std::string const & hint, typename std::enable_if< detail::is_invocable< Lambda >::value, ctor_lambda_e >::type = ctor_lambda_e::val)
bound_parser() [10/24]
template<typename Lambda > lyra::bound_parser< Derived >::bound_parser (Lambda const & ref, std::string const & hint, typename std::enable_if< detail::is_invocable< Lambda >::value, ctor_lambda_e >::type = ctor_lambda_e::val)
bound_parser() [11/24]
template<typename Lambda > lyra::bound_parser< Derived >::bound_parser (Lambda const & ref, std::string const & hint, typename std::enable_if< detail::is_invocable< Lambda >::value, ctor_lambda_e >::type = ctor_lambda_e::val)
bound_parser() [12/24]
template<typename Lambda > lyra::bound_parser< Derived >::bound_parser (Lambda const & ref, std::string const & hint, typename std::enable_if< detail::is_invocable< Lambda >::value, ctor_lambda_e >::type = ctor_lambda_e::val)
bound_parser() [13/24]
template<typename Reference > lyra::bound_parser< Derived >::bound_parser (Reference & ref, std::string const & hint)
bound_parser() [14/24]
template<typename Reference > lyra::bound_parser< Derived >::bound_parser (Reference & ref, std::string const & hint)
bound_parser() [15/24]
template<typename Reference > lyra::bound_parser< Derived >::bound_parser (Reference & ref, std::string const & hint)
bound_parser() [16/24]
template<typename Reference > lyra::bound_parser< Derived >::bound_parser (Reference & ref, std::string const & hint)
bound_parser() [17/24]
lyra::bound_parser< Derived >::bound_parser (std::shared_ptr< detail::BoundRef > const & ref) inline explicit
bound_parser() [18/24]
lyra::bound_parser< Derived >::bound_parser (std::shared_ptr< detail::BoundRef > const & ref) inline explicit
bound_parser() [19/24]
lyra::bound_parser< Derived >::bound_parser (std::shared_ptr< detail::BoundRef > const & ref) inline explicit
bound_parser() [20/24]
lyra::bound_parser< Derived >::bound_parser (std::shared_ptr< detail::BoundRef > const & ref) inline explicit
bound_parser() [21/24]
lyra::bound_parser< Derived >::bound_parser (std::shared_ptr< detail::BoundRef > const & ref, std::string const & hint) inline
bound_parser() [22/24]
lyra::bound_parser< Derived >::bound_parser (std::shared_ptr< detail::BoundRef > const & ref, std::string const & hint) inline
bound_parser() [23/24]
lyra::bound_parser< Derived >::bound_parser (std::shared_ptr< detail::BoundRef > const & ref, std::string const & hint) inline
bound_parser() [24/24]
lyra::bound_parser< Derived >::bound_parser (std::shared_ptr< detail::BoundRef > const & ref, std::string const & hint) inline
get_help_text() [1/2]
virtual help_text lyra::arg::get_help_text (const option_style & style) const inline override virtual
Reimplemented from lyra::parser.
References lyra::parser::get_usage_text(), and lyra::bound_parser< arg >::m_description.
get_help_text() [2/2]
virtual help_text lyra::arg::get_help_text (const option_style & style) const inline override virtual
Reimplemented from lyra::parser.
References lyra::parser::get_usage_text(), and lyra::bound_parser< arg >::m_description.
get_usage_text() [1/2]
virtual std::string lyra::arg::get_usage_text (const option_style &) const inline override virtual
Reimplemented from lyra::parser.
References lyra::bound_parser< arg >::cardinality(), and lyra::bound_parser< arg >::m_hint.
get_usage_text() [2/2]
virtual std::string lyra::arg::get_usage_text (const option_style &) const inline override virtual
Reimplemented from lyra::parser.
References lyra::bound_parser< arg >::cardinality(), and lyra::bound_parser< arg >::m_hint.
parse() [1/6]
parse_result lyra::arg::parse (detail::token_iterator const & tokens, const option_style & style) const inline override virtual
Implements lyra::parser.
References lyra::detail::token_iterator::argument(), lyra::parser::get_usage_text(), LYRA_PRINT_DEBUG, LYRA_PRINT_SCOPE, lyra::bound_parser< arg >::m_ref, lyra::matched, lyra::no_match, lyra::detail::basic_result< detail::parse_state >::ok(), lyra::detail::token_iterator::pop(), lyra::parser::validate(), and lyra::bound_parser< arg >::value_choices.
parse() [2/6]
parse_result lyra::arg::parse (detail::token_iterator const & tokens, const option_style & style) const inline override virtual
Implements lyra::parser.
References lyra::detail::token_iterator::argument(), lyra::parser::get_usage_text(), LYRA_PRINT_DEBUG, LYRA_PRINT_SCOPE, lyra::bound_parser< arg >::m_ref, lyra::matched, lyra::no_match, lyra::detail::basic_result< detail::parse_state >::ok(), lyra::detail::token_iterator::pop(), lyra::parser::validate(), and lyra::bound_parser< arg >::value_choices.
parse() [3/6]
virtual parse_result lyra::parser::parse (detail::token_iterator const & tokens, const option_style & style) const virtual
Implements lyra::parser.
parse() [4/6]
virtual parse_result lyra::parser::parse (detail::token_iterator const & tokens, const option_style & style) const virtual
Implements lyra::parser.
parse() [5/6]
virtual parse_result lyra::parser::parse (detail::token_iterator const & tokens, const option_style & style) const virtual
Implements lyra::parser.
parse() [6/6]
virtual parse_result lyra::parser::parse (detail::token_iterator const & tokens, const option_style & style) const virtual
Implements lyra::parser.
The documentation for this class was generated from the following files:
Lyra/data/single_include/lyra/lyra.hpp
Lyra/include/lyra/arg.hpp