Skeletal: MainNamespace::Clocks Class Reference
MainNamespace::Clocks Class Reference
#include <timing.h>
Public Member Functions
~Clocks ()
void addTimer (BaseTimer *timer)
void format (std::string formatstring)
std::string readAll ()
void resume ()
void start ()
void stop ()
Private Attributes
std::string format_
std::list< BaseTimer * > timers_
Detailed Description
Collection of timers measuring the same interval in (possibly) different ways
Constructor & Destructor Documentation
~Clocks()
MainNamespace::Clocks::~Clocks ()
References timers_.
Member Function Documentation
addTimer()
void MainNamespace::Clocks::addTimer (BaseTimer * timer)
References timers_.
Referenced by MainNamespace::Options::Options().
format()
void MainNamespace::Clocks::format (std::string formatstring)
References format_.
Referenced by MainNamespace::Options::Options().
readAll()
std::string MainNamespace::Clocks::readAll ()
References format_, timers_, and lyra::detail::to_string().
Referenced by MainNamespace::stopTiming().
resume()
void MainNamespace::Clocks::resume ()
References timers_.
start()
void MainNamespace::Clocks::start ()
References timers_.
Referenced by MainNamespace::startTiming().
stop()
void MainNamespace::Clocks::stop ()
References timers_.
Member Data Documentation
format_
std::string MainNamespace::Clocks::format_ private
Referenced by format(), and readAll().
timers_
std::list<BaseTimer*> MainNamespace::Clocks::timers_ private
Referenced by ~Clocks(), addTimer(), readAll(), resume(), start(), and stop().
The documentation for this class was generated from the following files:
main/timing.h
main/timing.cpp