Skeletal: lyra::parser Class Reference
lyra::parser Class Reference abstract
#include <parser.hpp>
Classes
struct help_text_item
Public Types
using help_text = std::vector< help_text_item >
using help_text = std::vector< help_text_item >
Public Member Functions
virtual ~parser ()=default
virtual ~parser ()=default
virtual detail::parser_cardinality cardinality () const
virtual detail::parser_cardinality cardinality () const
virtual std::unique_ptr< parser > clone () const
virtual std::unique_ptr< parser > clone () const
std::string get_description_text () const
std::string get_description_text () const
virtual std::string get_description_text (const option_style &) const
virtual std::string get_description_text (const option_style &) const
help_text get_help_text () const
help_text get_help_text () const
virtual help_text get_help_text (const option_style &) const
virtual help_text get_help_text (const option_style &) const
virtual const parser * get_named (const std::string &n) const
virtual const parser * get_named (const std::string &n) const
std::string get_usage_text () const
std::string get_usage_text () const
virtual std::string get_usage_text (const option_style &) const
virtual std::string get_usage_text (const option_style &) const
virtual std::string get_value (size_t i) const
virtual std::string get_value (size_t i) const
virtual size_t get_value_count () const
virtual size_t get_value_count () const
virtual bool is_group () const
virtual bool is_group () const
virtual bool is_named (const std::string &n) const
virtual bool is_named (const std::string &n) const
bool is_optional () const
bool is_optional () const
virtual parse_result parse (detail::token_iterator const &tokens, const option_style &style) const =0
virtual parse_result parse (detail::token_iterator const &tokens, const option_style &style) const =0
virtual result validate () const
virtual result validate () const
Protected Member Functions
virtual void print_help_text (printer &p, const option_style &style) const
virtual void print_help_text (printer &p, const option_style &style) const
virtual void print_help_text_details (printer &p, const option_style &style) const
virtual void print_help_text_details (printer &p, const option_style &style) const
virtual void print_help_text_summary (printer &p, const option_style &style) const
virtual void print_help_text_summary (printer &p, const option_style &style) const
Member Typedef Documentation
help_text [1/2]
using lyra::parser::help_text = std::vector<help_text_item>
help_text [2/2]
using lyra::parser::help_text = std::vector<help_text_item>
Constructor & Destructor Documentation
~parser() [1/2]
virtual lyra::parser::~parser () virtual default
~parser() [2/2]
virtual lyra::parser::~parser () virtual default
Member Function Documentation
cardinality() [1/2]
virtual detail::parser_cardinality lyra::parser::cardinality () const inline virtual
Reimplemented in lyra::bound_parser< Derived >, lyra::bound_parser< arg >, lyra::bound_parser< opt >, lyra::arguments, lyra::group, lyra::literal, lyra::arguments, lyra::group, lyra::literal, lyra::bound_parser< Derived >, lyra::bound_parser< arg >, and lyra::bound_parser< opt >.
Referenced by is_optional().
cardinality() [2/2]
virtual detail::parser_cardinality lyra::parser::cardinality () const inline virtual
Reimplemented in lyra::bound_parser< Derived >, lyra::bound_parser< arg >, lyra::bound_parser< opt >, lyra::arguments, lyra::group, lyra::literal, lyra::arguments, lyra::group, lyra::literal, lyra::bound_parser< Derived >, lyra::bound_parser< arg >, and lyra::bound_parser< opt >.
clone() [1/2]
virtual std::unique_ptr< parser > lyra::parser::clone () const inline virtual
Reimplemented in lyra::bound_parser< Derived >, lyra::bound_parser< arg >, lyra::bound_parser< opt >, lyra::exe_name, lyra::arguments, lyra::group, lyra::cli, lyra::literal, lyra::command, lyra::opt, lyra::help, lyra::arguments, lyra::cli, lyra::command, lyra::exe_name, lyra::group, lyra::help, lyra::literal, lyra::opt, lyra::bound_parser< Derived >, lyra::bound_parser< arg >, and lyra::bound_parser< opt >.
Referenced by lyra::arguments::add_argument().
clone() [2/2]
virtual std::unique_ptr< parser > lyra::parser::clone () const inline virtual
Reimplemented in lyra::bound_parser< Derived >, lyra::bound_parser< arg >, lyra::bound_parser< opt >, lyra::exe_name, lyra::arguments, lyra::group, lyra::cli, lyra::literal, lyra::command, lyra::opt, lyra::help, lyra::arguments, lyra::cli, lyra::command, lyra::exe_name, lyra::group, lyra::help, lyra::literal, lyra::opt, lyra::bound_parser< Derived >, lyra::bound_parser< arg >, and lyra::bound_parser< opt >.
get_description_text() [1/4]
std::string lyra::parser::get_description_text () const inline
Referenced by print_help_text_summary().
get_description_text() [2/4]
std::string lyra::parser::get_description_text () const inline
get_description_text() [3/4]
virtual std::string lyra::parser::get_description_text (const option_style &) const inline virtual
Reimplemented in lyra::literal, lyra::help, lyra::help, lyra::literal, lyra::arguments, and lyra::arguments.
get_description_text() [4/4]
virtual std::string lyra::parser::get_description_text (const option_style &) const inline virtual
Reimplemented in lyra::literal, lyra::help, lyra::help, lyra::literal, lyra::arguments, and lyra::arguments.
get_help_text() [1/4]
help_text lyra::parser::get_help_text () const inline
Referenced by print_help_text_details(), and lyra::command::print_help_text_details().
get_help_text() [2/4]
help_text lyra::parser::get_help_text () const inline
get_help_text() [3/4]
virtual help_text lyra::parser::get_help_text (const option_style &) const inline virtual
Reimplemented in lyra::literal, lyra::literal, lyra::arg, lyra::arguments, lyra::command, lyra::opt, lyra::arg, lyra::arguments, lyra::command, and lyra::opt.
get_help_text() [4/4]
virtual help_text lyra::parser::get_help_text (const option_style &) const inline virtual
Reimplemented in lyra::literal, lyra::literal, lyra::arg, lyra::arguments, lyra::command, lyra::opt, lyra::arg, lyra::arguments, lyra::command, and lyra::opt.
get_named() [1/2]
virtual const parser * lyra::parser::get_named (const std::string & n) const inline virtual
Reimplemented in lyra::arguments, lyra::cli, lyra::cli, lyra::arguments, lyra::cli, and lyra::cli.
References is_named().
Referenced by lyra::arguments::get_named().
get_named() [2/2]
virtual const parser * lyra::parser::get_named (const std::string & n) const inline virtual
Reimplemented in lyra::arguments, lyra::cli, lyra::cli, lyra::arguments, lyra::cli, and lyra::cli.
References is_named().
get_usage_text() [1/4]
std::string lyra::parser::get_usage_text () const inline
Referenced by lyra::arg::get_help_text(), lyra::cli::get_usage_text(), lyra::arg::parse(), lyra::group::parse(), lyra::opt::parse(), lyra::arguments::parse_any(), lyra::arguments::parse_sequence(), and print_help_text_summary().
get_usage_text() [2/4]
std::string lyra::parser::get_usage_text () const inline
get_usage_text() [3/4]
virtual std::string lyra::parser::get_usage_text (const option_style &) const inline virtual
Reimplemented in lyra::arg, lyra::literal, lyra::arg, lyra::literal, lyra::arguments, lyra::cli, lyra::command, lyra::opt, lyra::arguments, lyra::cli, lyra::command, and lyra::opt.
get_usage_text() [4/4]
virtual std::string lyra::parser::get_usage_text (const option_style &) const inline virtual
Reimplemented in lyra::arg, lyra::literal, lyra::arg, lyra::literal, lyra::arguments, lyra::cli, lyra::command, lyra::opt, lyra::arguments, lyra::cli, lyra::command, and lyra::opt.
get_value() [1/2]
virtual std::string lyra::parser::get_value (size_t i) const inline virtual
Reimplemented in lyra::bound_parser< Derived >, lyra::bound_parser< arg >, lyra::bound_parser< opt >, lyra::bound_parser< Derived >, lyra::bound_parser< arg >, and lyra::bound_parser< opt >.
Referenced by lyra::cli::value_result::operator std::string(), lyra::cli::value_result::operator std::vector< T >(), and lyra::cli::value_result::operator T().
get_value() [2/2]
virtual std::string lyra::parser::get_value (size_t i) const inline virtual
Reimplemented in lyra::bound_parser< Derived >, lyra::bound_parser< arg >, lyra::bound_parser< opt >, lyra::bound_parser< Derived >, lyra::bound_parser< arg >, and lyra::bound_parser< opt >.
get_value_count() [1/2]
virtual size_t lyra::parser::get_value_count () const inline virtual
Reimplemented in lyra::bound_parser< Derived >, lyra::bound_parser< arg >, lyra::bound_parser< opt >, lyra::bound_parser< Derived >, lyra::bound_parser< arg >, and lyra::bound_parser< opt >.
Referenced by lyra::cli::value_result::operator std::vector< T >().
get_value_count() [2/2]
virtual size_t lyra::parser::get_value_count () const inline virtual
Reimplemented in lyra::bound_parser< Derived >, lyra::bound_parser< arg >, lyra::bound_parser< opt >, lyra::bound_parser< Derived >, lyra::bound_parser< arg >, and lyra::bound_parser< opt >.
is_group() [1/2]
virtual bool lyra::parser::is_group () const inline virtual
Reimplemented in lyra::group, and lyra::group.
Referenced by lyra::arguments::add_argument().
is_group() [2/2]
virtual bool lyra::parser::is_group () const inline virtual
Reimplemented in lyra::group, and lyra::group.
is_named() [1/2]
virtual bool lyra::parser::is_named (const std::string & n) const inline virtual
Reimplemented in lyra::bound_parser< Derived >, lyra::bound_parser< arg >, lyra::bound_parser< opt >, lyra::opt, lyra::opt, lyra::bound_parser< Derived >, lyra::bound_parser< arg >, and lyra::bound_parser< opt >.
Referenced by get_named().
is_named() [2/2]
virtual bool lyra::parser::is_named (const std::string & n) const inline virtual
Reimplemented in lyra::bound_parser< Derived >, lyra::bound_parser< arg >, lyra::bound_parser< opt >, lyra::opt, lyra::opt, lyra::bound_parser< Derived >, lyra::bound_parser< arg >, and lyra::bound_parser< opt >.
is_optional() [1/2]
bool lyra::parser::is_optional () const inline
References cardinality(), and lyra::detail::parser_cardinality::is_optional().
is_optional() [2/2]
bool lyra::parser::is_optional () const inline
References cardinality(), and lyra::detail::parser_cardinality::is_optional().
parse() [1/2]
virtual parse_result lyra::parser::parse (detail::token_iterator const & tokens, const option_style & style) const pure virtual
Implemented in lyra::exe_name, lyra::literal, lyra::exe_name, lyra::literal, lyra::arg, lyra::arguments, lyra::group, lyra::cli, lyra::cli, lyra::opt, lyra::arg, lyra::arguments, lyra::cli, lyra::cli, lyra::group, lyra::opt, lyra::arg, lyra::arg, lyra::literal, lyra::literal, lyra::opt, lyra::opt, lyra::arg, lyra::arg, lyra::literal, lyra::literal, lyra::opt, and lyra::opt.
Referenced by main().
parse() [2/2]
virtual parse_result lyra::parser::parse (detail::token_iterator const & tokens, const option_style & style) const pure virtual
Implemented in lyra::exe_name, lyra::literal, lyra::exe_name, lyra::literal, lyra::arg, lyra::arguments, lyra::group, lyra::cli, lyra::cli, lyra::opt, lyra::arg, lyra::arguments, lyra::cli, lyra::cli, lyra::group, lyra::opt, lyra::arg, lyra::arg, lyra::literal, lyra::literal, lyra::opt, lyra::opt, lyra::arg, lyra::arg, lyra::literal, lyra::literal, lyra::opt, and lyra::opt.
print_help_text() [1/2]
virtual void lyra::parser::print_help_text (printer & p, const option_style & style) const inline protected virtual
References print_help_text_details(), and print_help_text_summary().
Referenced by lyra::arguments::print_help().
print_help_text() [2/2]
virtual void lyra::parser::print_help_text (printer & p, const option_style & style) const inline protected virtual
References print_help_text_details(), and print_help_text_summary().
print_help_text_details() [1/2]
virtual void lyra::parser::print_help_text_details (printer & p, const option_style & style) const inline protected virtual
Reimplemented in lyra::command, and lyra::command.
References get_help_text(), lyra::printer::heading(), and lyra::printer::option().
Referenced by print_help_text().
print_help_text_details() [2/2]
virtual void lyra::parser::print_help_text_details (printer & p, const option_style & style) const inline protected virtual
Reimplemented in lyra::command, and lyra::command.
References get_help_text(), lyra::printer::heading(), and lyra::printer::option().
print_help_text_summary() [1/2]
virtual void lyra::parser::print_help_text_summary (printer & p, const option_style & style) const inline protected virtual
References get_description_text(), get_usage_text(), lyra::printer::heading(), and lyra::printer::paragraph().
Referenced by print_help_text().
print_help_text_summary() [2/2]
virtual void lyra::parser::print_help_text_summary (printer & p, const option_style & style) const inline protected virtual
References get_description_text(), get_usage_text(), lyra::printer::heading(), and lyra::printer::paragraph().
validate() [1/2]
virtual result lyra::parser::validate () const inline virtual
Reimplemented in lyra::arguments, lyra::opt, lyra::arguments, and lyra::opt.
References lyra::detail::basic_result< void >::ok().
Referenced by lyra::literal::parse(), lyra::arg::parse(), and lyra::opt::validate().
validate() [2/2]
virtual result lyra::parser::validate () const inline virtual
Reimplemented in lyra::arguments, lyra::opt, lyra::arguments, and lyra::opt.
References lyra::detail::basic_result< void >::ok().
The documentation for this class was generated from the following files:
Lyra/data/single_include/lyra/lyra.hpp
Lyra/include/lyra/parser.hpp