Skeletal: lyra::cli Class Reference
lyra::cli Class Reference
#include <cli.hpp>
Classes
struct value_result
Public Member Functions
cli ()=default
cli ()=default
cli (const cli &other)
cli (const cli &other)
cli & add_argument (cli const &other)
cli & add_argument (cli const &other)
cli & add_argument (exe_name const &exe_name)
cli & add_argument (exe_name const &exe_name)
cli & add_argument (group const &p)
cli & add_argument (group const &p)
cli & add_argument (parser const &p)
cli & add_argument (parser const &p)
virtual std::unique_ptr< parser > clone () const override
virtual std::unique_ptr< parser > clone () const override
virtual const parser * get_named (const std::string &n) const override
virtual const parser * get_named (const std::string &n) const override
virtual const parser * get_named (const std::string &n) const override
virtual const parser * get_named (const std::string &n) const override
value_result operator[] (const std::string &n)
value_result operator[] (const std::string &n)
template<typename T >
cli operator| (T const &other) const
template<typename T >
cli operator| (T const &other) const
cli & operator|= (cli const &other)
cli & operator|= (cli const &other)
cli & operator|= (exe_name const &exe_name)
cli & operator|= (exe_name const &exe_name)
cli & operator|= (group const &p)
cli & operator|= (group const &p)
cli & operator|= (parser const &p)
cli & operator|= (parser const &p)
parse_result parse (args const &args) const
parse_result parse (args const &args) const
parse_result parse (args const &args, const option_style &style) const
parse_result parse (args const &args, const option_style &style) const
parse_result parse (args const &args, const parser_customization &customize) const
parse_result parse (args const &args, const parser_customization &customize) const
parse_result parse (detail::token_iterator const &tokens, const option_style &style) const override
parse_result parse (detail::token_iterator const &tokens, const option_style &style) const override
parse_result parse (detail::token_iterator const &tokens, const option_style &style) const override
parse_result parse (detail::token_iterator const &tokens, const option_style &style) const override
cli & style (const option_style &style)
cli & style (const option_style &style)
cli & style (option_style &&style)
cli & style (option_style &&style)
Protected Member Functions
virtual std::string get_usage_text (const option_style &style) const override
virtual std::string get_usage_text (const option_style &style) const override
Protected Member Functions inherited from lyra::arguments
option_style get_option_style () const
option_style get_option_style () const
arguments ()=default
arguments ()=default
arguments (const arguments &other)
arguments (const arguments &other)
arguments (evaluation e)
arguments (evaluation e)
arguments & add_argument (arguments const &other)
arguments & add_argument (arguments const &other)
arguments & add_argument (parser const &p)
arguments & add_argument (parser const &p)
virtual detail::parser_cardinality cardinality () const override
virtual detail::parser_cardinality cardinality () const override
virtual std::unique_ptr< parser > clone () const override
virtual std::unique_ptr< parser > clone () const override
template<typename T >
T & get (size_t i)
template<typename T >
T & get (size_t i)
virtual std::string get_description_text (const option_style &style) const override
virtual std::string get_description_text (const option_style &style) const override
virtual help_text get_help_text (const option_style &style) const override
virtual help_text get_help_text (const option_style &style) const override
virtual const parser * get_named (const std::string &n) const override
virtual const parser * get_named (const std::string &n) const override
virtual std::string get_usage_text (const option_style &style) const override
virtual std::string get_usage_text (const option_style &style) const override
arguments & inclusive ()
arguments & inclusive ()
arguments & operator|= (arguments const &other)
arguments & operator|= (arguments const &other)
arguments & operator|= (parser const &p)
arguments & operator|= (parser const &p)
parse_result parse (detail::token_iterator const &tokens, const option_style &style) const override
parse_result parse (detail::token_iterator const &tokens, const option_style &style) const override
parse_result parse_any (detail::token_iterator const &tokens, const option_style &style) const
parse_result parse_any (detail::token_iterator const &tokens, const option_style &style) const
parse_result parse_sequence (detail::token_iterator const &tokens, const option_style &style) const
parse_result parse_sequence (detail::token_iterator const &tokens, const option_style &style) const
template<typename T >
T & print_help (T &os) const
template<typename T >
T & print_help (T &os) const
arguments & sequential ()
arguments & sequential ()
virtual result validate () const override
virtual result validate () const override
Protected Member Functions inherited from lyra::parser
virtual void print_help_text (printer &p, const option_style &style) const
virtual void print_help_text (printer &p, const option_style &style) const
virtual void print_help_text_details (printer &p, const option_style &style) const
virtual void print_help_text_details (printer &p, const option_style &style) const
virtual void print_help_text_summary (printer &p, const option_style &style) const
virtual void print_help_text_summary (printer &p, const option_style &style) const
virtual ~parser ()=default
virtual ~parser ()=default
virtual detail::parser_cardinality cardinality () const
virtual detail::parser_cardinality cardinality () const
virtual std::unique_ptr< parser > clone () const
virtual std::unique_ptr< parser > clone () const
std::string get_description_text () const
std::string get_description_text () const
virtual std::string get_description_text (const option_style &) const
virtual std::string get_description_text (const option_style &) const
help_text get_help_text () const
help_text get_help_text () const
virtual help_text get_help_text (const option_style &) const
virtual help_text get_help_text (const option_style &) const
virtual const parser * get_named (const std::string &n) const
virtual const parser * get_named (const std::string &n) const
std::string get_usage_text () const
std::string get_usage_text () const
virtual std::string get_usage_text (const option_style &) const
virtual std::string get_usage_text (const option_style &) const
virtual std::string get_value (size_t i) const
virtual std::string get_value (size_t i) const
virtual size_t get_value_count () const
virtual size_t get_value_count () const
virtual bool is_group () const
virtual bool is_group () const
virtual bool is_named (const std::string &n) const
virtual bool is_named (const std::string &n) const
bool is_optional () const
bool is_optional () const
virtual parse_result parse (detail::token_iterator const &tokens, const option_style &style) const =0
virtual parse_result parse (detail::token_iterator const &tokens, const option_style &style) const =0
virtual result validate () const
virtual result validate () const
Protected Attributes
exe_name m_exeName
Protected Attributes inherited from lyra::arguments
evaluation eval_mode = any
std::shared_ptr< option_style > opt_style
std::vector< std::unique_ptr< parser > > parsers
Friends
template<typename T >
T & operator<< (T &os, cli const &c)
template<typename T >
T & operator<< (T &os, cli const &c)
Additional Inherited Members
Protected Types inherited from lyra::arguments
enum evaluation { any = 0 , sequence = 1 , any = 0 , sequence = 1 }
enum evaluation { any = 0 , sequence = 1 , any = 0 , sequence = 1 }
Protected Types inherited from lyra::parser
using help_text = std::vector< help_text_item >
using help_text = std::vector< help_text_item >
Constructor & Destructor Documentation
cli() [1/4]
lyra::cli::cli () default
Referenced by clone(), and operator|().
cli() [2/4]
lyra::cli::cli (const cli & other) inline
cli() [3/4]
lyra::cli::cli () default
cli() [4/4]
lyra::cli::cli (const cli & other)
Member Function Documentation
add_argument() [1/8]
cli & lyra::cli::add_argument (cli const & other) inline
References lyra::arguments::add_argument().
add_argument() [2/8]
cli & lyra::cli::add_argument (cli const & other)
add_argument() [3/8]
cli & lyra::cli::add_argument (exe_name const & exe_name) inline
References m_exeName.
Referenced by lyra::main::add_argument(), main(), lyra::main::operator()(), and operator|=().
add_argument() [4/8]
cli & lyra::cli::add_argument (exe_name const & exe_name)
add_argument() [5/8]
cli & lyra::cli::add_argument (group const & p) inline
References lyra::arguments::add_argument().
add_argument() [6/8]
cli & lyra::cli::add_argument (group const & p)
add_argument() [7/8]
cli & lyra::cli::add_argument (parser const & p) inline
References lyra::arguments::add_argument().
add_argument() [8/8]
cli & lyra::cli::add_argument (parser const & p)
clone() [1/2]
virtual std::unique_ptr< parser > lyra::cli::clone () const inline override virtual
Reimplemented from lyra::arguments.
References cli().
clone() [2/2]
virtual std::unique_ptr< parser > lyra::cli::clone () const inline override virtual
Reimplemented from lyra::arguments.
References cli().
get_named() [1/4]
virtual const parser * lyra::arguments::get_named (const std::string & n) const inline override virtual
Reimplemented from lyra::arguments.
get_named() [2/4]
virtual const parser * lyra::arguments::get_named (const std::string & n) const inline override virtual
Reimplemented from lyra::arguments.
Referenced by operator[]().
get_named() [3/4]
virtual const parser * lyra::arguments::get_named (const std::string & n) const inline override virtual
Reimplemented from lyra::arguments.
get_named() [4/4]
virtual const parser * lyra::arguments::get_named (const std::string & n) const inline override virtual
Reimplemented from lyra::arguments.
get_usage_text() [1/2]
virtual std::string lyra::cli::get_usage_text (const option_style & style) const inline override protected virtual
Reimplemented from lyra::arguments.
References lyra::parser::get_usage_text(), m_exeName, lyra::exe_name::name(), and style().
get_usage_text() [2/2]
virtual std::string lyra::cli::get_usage_text (const option_style & style) const inline override protected virtual
Reimplemented from lyra::arguments.
References lyra::parser::get_usage_text(), m_exeName, lyra::exe_name::name(), and style().
operator[]() [1/2]
cli::value_result lyra::cli::operator[] (const std::string & n) inline
References get_named().
operator[]() [2/2]
value_result lyra::cli::operator[] (const std::string & n)
operator|() [1/2]
template<typename T > cli lyra::cli::operator| (T const & other) const inline
References cli().
operator|() [2/2]
template<typename T > cli lyra::cli::operator| (T const & other) const
operator|=() [1/8]
cli & lyra::cli::operator|= (cli const & other) inline
References add_argument().
operator|=() [2/8]
cli & lyra::cli::operator|= (cli const & other)
operator|=() [3/8]
cli & lyra::cli::operator|= (exe_name const & exe_name) inline
References add_argument().
Referenced by lyra::main::operator|=().
operator|=() [4/8]
cli & lyra::cli::operator|= (exe_name const & exe_name)
operator|=() [5/8]
cli & lyra::cli::operator|= (group const & p) inline
References add_argument().
operator|=() [6/8]
cli & lyra::cli::operator|= (group const & p)
operator|=() [7/8]
cli & lyra::cli::operator|= (parser const & p) inline
References lyra::arguments::add_argument().
operator|=() [8/8]
cli & lyra::cli::operator|= (parser const & p)
parse() [1/10]
parse_result lyra::cli::parse (args const & args) const inline
References lyra::arguments::opt_style, parse(), and lyra::option_style::posix().
Referenced by MainNamespace::Options::Options(), main(), lyra::main::operator()(), parse(), test_style(), and test_val().
parse() [2/10]
parse_result lyra::cli::parse (args const & args) const inline
References lyra::arguments::opt_style, parse(), and lyra::option_style::posix().
parse() [3/10]
parse_result lyra::cli::parse (args const & args, const option_style & style) const inline
References lyra::detail::token_iterator::argument(), lyra::detail::basic_result< detail::parse_state >::error(), lyra::args::exe_name(), lyra::detail::parse_state::have_tokens(), LYRA_PRINT_SCOPE, m_exeName, lyra::matched, lyra::detail::token::name, lyra::no_match, parse(), lyra::detail::parse_state::remainingTokens(), lyra::exe_name::set(), style(), lyra::detail::parse_state::type(), and lyra::detail::result_value_base< T >::value().
parse() [4/10]
parse_result lyra::cli::parse (args const & args, const option_style & style) const
parse() [5/10]
parse_result lyra::cli::parse (args const & args, const parser_customization & customize) const inline
References lyra::parser_customization::option_prefix(), parse(), and lyra::parser_customization::token_delimiters().
parse() [6/10]
parse_result lyra::cli::parse (args const & args, const parser_customization & customize) const inline
References lyra::parser_customization::option_prefix(), parse(), and lyra::parser_customization::token_delimiters().
parse() [7/10]
parse_result lyra::arguments::parse (detail::token_iterator const & tokens, const option_style & style) const inline override virtual
Reimplemented from lyra::arguments.
parse() [8/10]
parse_result lyra::arguments::parse (detail::token_iterator const & tokens, const option_style & style) const inline override virtual
Reimplemented from lyra::arguments.
parse() [9/10]
parse_result lyra::arguments::parse (detail::token_iterator const & tokens, const option_style & style) const inline override virtual
Reimplemented from lyra::arguments.
parse() [10/10]
parse_result lyra::arguments::parse (detail::token_iterator const & tokens, const option_style & style) const inline override virtual
Reimplemented from lyra::arguments.
style() [1/4]
cli & lyra::cli::style (const option_style & style) inline
References lyra::arguments::opt_style, and style().
Referenced by get_usage_text(), main(), parse(), style(), lyra::main::style(), and test_style().
style() [2/4]
cli & lyra::cli::style (const option_style & style)
style() [3/4]
cli & lyra::cli::style (option_style && style) inline
References lyra::arguments::opt_style, and style().
style() [4/4]
cli & lyra::cli::style (option_style && style)
Friends And Related Function Documentation
operator<< [1/2]
template<typename T > T & operator<< (T & os, cli const & c) friend
operator<< [2/2]
template<typename T > T & operator<< (T & os, cli const & c) friend
Member Data Documentation
m_exeName
exe_name lyra::cli::m_exeName mutable protected
Referenced by add_argument(), get_usage_text(), and parse().
The documentation for this class was generated from the following files:
Lyra/data/single_include/lyra/lyra.hpp
Lyra/include/lyra/cli.hpp