Skeletal: MainNamespace::Functions::MeshOffset Class Reference
MainNamespace::Functions::MeshOffset Class Reference abstract
Offset that takes its values from a mesh data.
#include <functions.h>
Public Member Functions
MeshOffset (Reference const *const solution)
Constuctor. Set the trace scaling and the actual exact solution. This class is pure virtual, but these data have to be initialized for every derived class.
virtual void c0Dirichlet (Mesh const &mesh, std::vector< uint > const &indices, bool const dof, real const waveScale, avector *const coefficients) const
Interpolate the Dirichlet trace with continuous, picewise linear functions. The trace is scaled by s^(1/2).
virtual field dirichlet (bool const dof, SpaceVector< real const > const point, real const scale) const =0
Compute an offset for the Dirictlet trace of the current solution.
virtual field dirichlet (SpaceVector< real const > const point, real const scale) const override
Compute the (discrete) (Dirichlet) trace of the function at point.
virtual void l2Neumann (helmholtz3d const *const parameters, Mesh const &mesh, std::vector< uint > const &indices, bool const dof, real const waveScale, real const stiffness, avector *const coefficients) const
Compute the L² projection of the Nemuann trace into piecewise constant functions. The trace is scaled by s^(-1/2).
virtual field neumann (bool const dof, SpaceVector< real const > const point, SpaceVector< real const > const normal, real const scale) const =0
Compute an offset for the Neumann trace of the current solution.
virtual field neumann (SpaceVector< real const > const point, SpaceVector< real const > const normal, real const scale) const override
Compute the (discrete) Neumann trace of the function at point.
virtual field waveNumber () const override
Getter.
Public Member Functions inherited from MainNamespace::Functions::Reference
virtual ~Reference ()
virtual field dirichlet (SpaceVector< real const > const point, real const scale) const =0
Compute the (discrete) (Dirichlet) trace of the function at point.
virtual field neumann (SpaceVector< real const > const point, SpaceVector< real const > const normal, real const scale) const =0
Compute the (discrete) Neumann trace of the function at point.
virtual field waveNumber () const =0
Getter.
Protected Attributes
Reference const * solution_
Pointer to the actual solution generating the offset.
field traceScaling_
sqrt(-i wavenumber) for trace scaling.
Detailed Description
Offset that takes its values from a mesh data.
Constructor & Destructor Documentation
MeshOffset()
MainNamespace::Functions::MeshOffset::MeshOffset (Reference const *const solution)
Constuctor. Set the trace scaling and the actual exact solution. This class is pure virtual, but these data have to be initialized for every derived class.
Parameters
solution The exact solution, needed at least to compute the traces on the non-dof elements.
Member Function Documentation
c0Dirichlet()
void MainNamespace::Functions::MeshOffset::c0Dirichlet (Mesh const & mesh, std::vector< uint > const & indices, bool const dof, real const waveScale, avector *const coefficients) const virtual
Interpolate the Dirichlet trace with continuous, picewise linear functions. The trace is scaled by s^(1/2).
Parameters
mesh Mesh data.
indices Indices of the dofs to fill.
dof Whether the indices correspond to degrees of freedom or data.
waveScale Scaling of the wave number induced by parameters.
[out] coefficients The offset vector to fill.
References dirichlet(), traceScaling_, MainNamespace::Mesh::triangleDofs_, MainNamespace::Mesh::vertex(), and MainNamespace::Mesh::vertexDofs_.
Referenced by MainNamespace::Surface::SingleSurface::makeOffset().
dirichlet() [1/2]
virtual field MainNamespace::Functions::MeshOffset::dirichlet (bool const dof, SpaceVector< real const > const point, real const scale) const pure virtual
Compute an offset for the Dirictlet trace of the current solution.
Parameters
dof Whether the current point is a dof. The offset on dofs may differ from the trace of the actual solution.
point Point where to compute the offset.
scale Scaling for the frequency, due to material parameters.
Implemented in MainNamespace::Functions::ZeroExtension.
Referenced by c0Dirichlet().
dirichlet() [2/2]
field MainNamespace::Functions::MeshOffset::dirichlet (SpaceVector< real const > const point, real const scale) const override virtual
Compute the (discrete) (Dirichlet) trace of the function at point.
Parameters
point Point where the trace is computed.
scale Scaling for the frequency, due to material parameters.
Implements MainNamespace::Functions::Reference.
References MainNamespace::Functions::Reference::dirichlet(), and solution_.
l2Neumann()
void MainNamespace::Functions::MeshOffset::l2Neumann (helmholtz3d const *const parameters, Mesh const & mesh, std::vector< uint > const & indices, bool const dof, real const waveScale, real const stiffness, avector *const coefficients) const virtual
Compute the L² projection of the Nemuann trace into piecewise constant functions. The trace is scaled by s^(-1/2).
Parameters
parameters Helmholtz object with the quadrature parameters.
mesh Mesh description.
indices Indices of the dofs to fill.
dof Whether the indices correspond to degrees of freedom or data.
waveScale Scaling of the wave number induced by parameters.
stiffness Stiffness (for scaling the Neumann trace with respect to the normal trace).
[out] coefficients The offset vector to fill.
References neumann(), MainNamespace::Mesh::normal(), traceScaling_, MainNamespace::Mesh::triangle(), MainNamespace::Mesh::triangleDofs_, MainNamespace::Mesh::vertex(), MainNamespace::Mesh::vertexDofs_, and MainNamespace::Mesh::vertices().
Referenced by MainNamespace::Surface::SingleSurface::makeOffset().
neumann() [1/2]
virtual field MainNamespace::Functions::MeshOffset::neumann (bool const dof, SpaceVector< real const > const point, SpaceVector< real const > const normal, real const scale) const pure virtual
Compute an offset for the Neumann trace of the current solution.
Parameters
dof Whether the current point is a dof. The offset on dofs may differ from the trace of the actual solution.
point Point where to compute the offset.
normal Normal vector at the given point.
scale Scaling for the frequency, due to material parameters.
Implemented in MainNamespace::Functions::ZeroExtension.
Referenced by l2Neumann().
neumann() [2/2]
field MainNamespace::Functions::MeshOffset::neumann (SpaceVector< real const > const point, SpaceVector< real const > const normal, real const scale) const override virtual
Compute the (discrete) Neumann trace of the function at point.
Parameters
point Point where the trace is computed.
normal Normal vector at point.
scale Scaling for the frequency, due to material parameters.
Implements MainNamespace::Functions::Reference.
References MainNamespace::Functions::Reference::neumann(), and solution_.
waveNumber()
virtual field MainNamespace::Functions::MeshOffset::waveNumber () const inline override virtual
Getter.
Returns
The (modulus of the) wave number.
Implements MainNamespace::Functions::Reference.
References solution_, and MainNamespace::Functions::Reference::waveNumber().
Member Data Documentation
solution_
Reference const* MainNamespace::Functions::MeshOffset::solution_ protected
Pointer to the actual solution generating the offset.
Referenced by MainNamespace::Functions::ZeroExtension::dirichlet(), dirichlet(), MainNamespace::Functions::ZeroExtension::neumann(), neumann(), and waveNumber().
traceScaling_
field MainNamespace::Functions::MeshOffset::traceScaling_ protected
sqrt(-i wavenumber) for trace scaling.
Referenced by c0Dirichlet(), and l2Neumann().
The documentation for this class was generated from the following files:
main/functions.h
main/functions.cpp