Skeletal: lyra::arguments Class Reference
lyra::arguments Class Reference
#include <arguments.hpp>
Public Types
enum evaluation { any = 0 , sequence = 1 , any = 0 , sequence = 1 }
enum evaluation { any = 0 , sequence = 1 , any = 0 , sequence = 1 }
Public Types inherited from lyra::parser
using help_text = std::vector< help_text_item >
using help_text = std::vector< help_text_item >
Public Member Functions
arguments ()=default
arguments ()=default
arguments (const arguments &other)
arguments (const arguments &other)
arguments (evaluation e)
arguments (evaluation e)
arguments & add_argument (arguments const &other)
arguments & add_argument (arguments const &other)
arguments & add_argument (parser const &p)
arguments & add_argument (parser const &p)
virtual detail::parser_cardinality cardinality () const override
virtual detail::parser_cardinality cardinality () const override
virtual std::unique_ptr< parser > clone () const override
virtual std::unique_ptr< parser > clone () const override
template<typename T >
T & get (size_t i)
template<typename T >
T & get (size_t i)
virtual std::string get_description_text (const option_style &style) const override
virtual std::string get_description_text (const option_style &style) const override
virtual help_text get_help_text (const option_style &style) const override
virtual help_text get_help_text (const option_style &style) const override
virtual const parser * get_named (const std::string &n) const override
virtual const parser * get_named (const std::string &n) const override
virtual std::string get_usage_text (const option_style &style) const override
virtual std::string get_usage_text (const option_style &style) const override
arguments & inclusive ()
arguments & inclusive ()
arguments & operator|= (arguments const &other)
arguments & operator|= (arguments const &other)
arguments & operator|= (parser const &p)
arguments & operator|= (parser const &p)
parse_result parse (detail::token_iterator const &tokens, const option_style &style) const override
parse_result parse (detail::token_iterator const &tokens, const option_style &style) const override
parse_result parse_any (detail::token_iterator const &tokens, const option_style &style) const
parse_result parse_any (detail::token_iterator const &tokens, const option_style &style) const
parse_result parse_sequence (detail::token_iterator const &tokens, const option_style &style) const
parse_result parse_sequence (detail::token_iterator const &tokens, const option_style &style) const
template<typename T >
T & print_help (T &os) const
template<typename T >
T & print_help (T &os) const
arguments & sequential ()
arguments & sequential ()
virtual result validate () const override
virtual result validate () const override
Public Member Functions inherited from lyra::parser
virtual ~parser ()=default
virtual ~parser ()=default
virtual detail::parser_cardinality cardinality () const
virtual detail::parser_cardinality cardinality () const
virtual std::unique_ptr< parser > clone () const
virtual std::unique_ptr< parser > clone () const
std::string get_description_text () const
std::string get_description_text () const
virtual std::string get_description_text (const option_style &) const
virtual std::string get_description_text (const option_style &) const
help_text get_help_text () const
help_text get_help_text () const
virtual help_text get_help_text (const option_style &) const
virtual help_text get_help_text (const option_style &) const
virtual const parser * get_named (const std::string &n) const
virtual const parser * get_named (const std::string &n) const
std::string get_usage_text () const
std::string get_usage_text () const
virtual std::string get_usage_text (const option_style &) const
virtual std::string get_usage_text (const option_style &) const
virtual std::string get_value (size_t i) const
virtual std::string get_value (size_t i) const
virtual size_t get_value_count () const
virtual size_t get_value_count () const
virtual bool is_group () const
virtual bool is_group () const
virtual bool is_named (const std::string &n) const
virtual bool is_named (const std::string &n) const
bool is_optional () const
bool is_optional () const
virtual parse_result parse (detail::token_iterator const &tokens, const option_style &style) const =0
virtual parse_result parse (detail::token_iterator const &tokens, const option_style &style) const =0
virtual result validate () const
virtual result validate () const
Protected Member Functions
option_style get_option_style () const
option_style get_option_style () const
Protected Member Functions inherited from lyra::parser
virtual void print_help_text (printer &p, const option_style &style) const
virtual void print_help_text (printer &p, const option_style &style) const
virtual void print_help_text_details (printer &p, const option_style &style) const
virtual void print_help_text_details (printer &p, const option_style &style) const
virtual void print_help_text_summary (printer &p, const option_style &style) const
virtual void print_help_text_summary (printer &p, const option_style &style) const
Protected Attributes
evaluation eval_mode = any
std::shared_ptr< option_style > opt_style
std::vector< std::unique_ptr< parser > > parsers
Friends
template<typename T , typename U >
std::enable_if< std::is_base_of< arguments, typenamedetail::remove_cvref< T >::type >::value, T & >::type operator| (T &&self, U const &other)
template<typename T , typename U >
std::enable_if< std::is_base_of< arguments, typenamedetail::remove_cvref< T >::type >::value, T & >::type operator| (T &&self, U const &other)
template<typename T , typename U >
std::enable_if< std::is_base_of< arguments, typenamedetail::remove_cvref< T >::type >::value, T & >::type operator| (T &self, U const &other)
template<typename T , typename U >
std::enable_if< std::is_base_of< arguments, typenamedetail::remove_cvref< T >::type >::value, T & >::type operator| (T &self, U const &other)
Member Enumeration Documentation
evaluation [1/2]
enum lyra::arguments::evaluation
Enumerator
any
sequence
any
sequence
evaluation [2/2]
enum lyra::arguments::evaluation
Enumerator
any
sequence
any
sequence
Constructor & Destructor Documentation
arguments() [1/6]
lyra::arguments::arguments () default
arguments() [2/6]
lyra::arguments::arguments (evaluation e) inline
arguments() [3/6]
lyra::arguments::arguments (const arguments & other) inline
References parsers.
arguments() [4/6]
lyra::arguments::arguments () default
arguments() [5/6]
lyra::arguments::arguments (evaluation e) inline
arguments() [6/6]
lyra::arguments::arguments (const arguments & other)
Member Function Documentation
add_argument() [1/4]
arguments & lyra::arguments::add_argument (arguments const & other) inline
References clone(), lyra::parser::is_group(), and parsers.
add_argument() [2/4]
arguments & lyra::arguments::add_argument (arguments const & other)
add_argument() [3/4]
arguments & lyra::arguments::add_argument (parser const & p) inline
References lyra::parser::clone(), and parsers.
Referenced by lyra::command::command(), lyra::cli::add_argument(), main(), operator|=(), and lyra::cli::operator|=().
add_argument() [4/4]
arguments & lyra::arguments::add_argument (parser const & p)
cardinality() [1/2]
virtual detail::parser_cardinality lyra::arguments::cardinality () const inline override virtual
Reimplemented from lyra::parser.
Reimplemented in lyra::group, and lyra::group.
cardinality() [2/2]
virtual detail::parser_cardinality lyra::arguments::cardinality () const inline override virtual
Reimplemented from lyra::parser.
Reimplemented in lyra::group, and lyra::group.
clone() [1/2]
virtual std::unique_ptr< parser > lyra::arguments::clone () const inline override virtual
Reimplemented from lyra::parser.
Reimplemented in lyra::group, lyra::cli, lyra::command, lyra::cli, lyra::command, and lyra::group.
Referenced by add_argument().
clone() [2/2]
virtual std::unique_ptr< parser > lyra::arguments::clone () const inline override virtual
Reimplemented from lyra::parser.
Reimplemented in lyra::group, lyra::cli, lyra::command, lyra::cli, lyra::command, and lyra::group.
get() [1/2]
template<typename T > T & lyra::arguments::get (size_t i)
References parsers.
get() [2/2]
template<typename T > T & lyra::arguments::get (size_t i)
get_description_text() [1/2]
virtual std::string lyra::arguments::get_description_text (const option_style & style) const inline override virtual
Reimplemented from lyra::parser.
References parsers.
get_description_text() [2/2]
virtual std::string lyra::arguments::get_description_text (const option_style & style) const inline override virtual
Reimplemented from lyra::parser.
References parsers.
get_help_text() [1/2]
virtual help_text lyra::arguments::get_help_text (const option_style & style) const inline override virtual
Reimplemented from lyra::parser.
Reimplemented in lyra::command, and lyra::command.
References parsers.
get_help_text() [2/2]
virtual help_text lyra::arguments::get_help_text (const option_style & style) const inline override virtual
Reimplemented from lyra::parser.
Reimplemented in lyra::command, and lyra::command.
References parsers.
get_named() [1/2]
virtual const parser * lyra::arguments::get_named (const std::string & n) const inline override virtual
Reimplemented from lyra::parser.
Reimplemented in lyra::cli, lyra::cli, lyra::cli, and lyra::cli.
References lyra::parser::get_named(), and parsers.
get_named() [2/2]
virtual const parser * lyra::arguments::get_named (const std::string & n) const inline override virtual
Reimplemented from lyra::parser.
Reimplemented in lyra::cli, lyra::cli, lyra::cli, and lyra::cli.
References lyra::parser::get_named(), and parsers.
get_option_style() [1/2]
option_style lyra::arguments::get_option_style () const inline protected
References opt_style, and lyra::option_style::posix().
Referenced by print_help().
get_option_style() [2/2]
option_style lyra::arguments::get_option_style () const inline protected
References opt_style, and lyra::option_style::posix().
get_usage_text() [1/2]
virtual std::string lyra::arguments::get_usage_text (const option_style & style) const inline override virtual
Reimplemented from lyra::parser.
Reimplemented in lyra::cli, lyra::command, lyra::cli, and lyra::command.
References parsers.
get_usage_text() [2/2]
virtual std::string lyra::arguments::get_usage_text (const option_style & style) const inline override virtual
Reimplemented from lyra::parser.
Reimplemented in lyra::cli, lyra::command, lyra::cli, and lyra::command.
References parsers.
inclusive() [1/2]
arguments & lyra::arguments::inclusive () inline
References any, and eval_mode.
inclusive() [2/2]
arguments & lyra::arguments::inclusive ()
operator|=() [1/4]
arguments & lyra::arguments::operator|= (arguments const & other) inline
References add_argument().
operator|=() [2/4]
arguments & lyra::arguments::operator|= (arguments const & other)
operator|=() [3/4]
arguments & lyra::arguments::operator|= (parser const & p) inline
References add_argument().
operator|=() [4/4]
arguments & lyra::arguments::operator|= (parser const & p)
parse() [1/2]
parse_result lyra::arguments::parse (detail::token_iterator const & tokens, const option_style & style) const inline override virtual
Implements lyra::parser.
Reimplemented in lyra::group, lyra::cli, lyra::cli, lyra::cli, lyra::cli, and lyra::group.
References any, lyra::detail::basic_result< detail::parse_state >::error(), eval_mode, lyra::no_match, parse_any(), parse_sequence(), and sequence.
Referenced by lyra::group::parse().
parse() [2/2]
parse_result lyra::arguments::parse (detail::token_iterator const & tokens, const option_style & style) const inline override virtual
Implements lyra::parser.
Reimplemented in lyra::cli, lyra::cli, lyra::cli, lyra::cli, and lyra::group.
References any, lyra::detail::basic_result< detail::parse_state >::error(), eval_mode, lyra::no_match, parse_any(), parse_sequence(), and sequence.
parse_any() [1/2]
parse_result lyra::arguments::parse_any (detail::token_iterator const & tokens, const option_style & style) const inline
References lyra::detail::token_iterator::argument(), MainNamespace::count(), lyra::detail::basic_result< detail::parse_state >::error(), lyra::parser::get_usage_text(), LYRA_PRINT_DEBUG, LYRA_PRINT_SCOPE, lyra::matched, lyra::detail::token::name, lyra::no_match, lyra::detail::basic_result< detail::parse_state >::ok(), parsers, and lyra::short_circuit_all.
Referenced by parse().
parse_any() [2/2]
parse_result lyra::arguments::parse_any (detail::token_iterator const & tokens, const option_style & style) const inline
References lyra::detail::token_iterator::argument(), MainNamespace::count(), lyra::detail::basic_result< detail::parse_state >::error(), lyra::parser::get_usage_text(), LYRA_PRINT_DEBUG, LYRA_PRINT_SCOPE, lyra::matched, lyra::detail::token::name, lyra::no_match, lyra::detail::basic_result< detail::parse_state >::ok(), parsers, and lyra::short_circuit_all.
parse_sequence() [1/2]
parse_result lyra::arguments::parse_sequence (detail::token_iterator const & tokens, const option_style & style) const inline
References lyra::detail::token_iterator::argument(), MainNamespace::count(), lyra::detail::basic_result< detail::parse_state >::error(), lyra::parser::get_usage_text(), LYRA_PRINT_DEBUG, LYRA_PRINT_SCOPE, lyra::matched, lyra::detail::token::name, lyra::no_match, lyra::detail::basic_result< detail::parse_state >::ok(), parsers, and lyra::short_circuit_all.
Referenced by parse().
parse_sequence() [2/2]
parse_result lyra::arguments::parse_sequence (detail::token_iterator const & tokens, const option_style & style) const inline
References lyra::detail::token_iterator::argument(), MainNamespace::count(), lyra::detail::basic_result< detail::parse_state >::error(), lyra::parser::get_usage_text(), LYRA_PRINT_DEBUG, LYRA_PRINT_SCOPE, lyra::matched, lyra::detail::token::name, lyra::no_match, lyra::detail::basic_result< detail::parse_state >::ok(), parsers, and lyra::short_circuit_all.
print_help() [1/2]
template<typename T > T & lyra::arguments::print_help (T & os) const inline
References get_option_style(), lyra::make_printer(), and lyra::parser::print_help_text().
Referenced by lyra::operator<<().
print_help() [2/2]
template<typename T > T & lyra::arguments::print_help (T & os) const inline
References get_option_style(), lyra::make_printer(), and lyra::parser::print_help_text().
sequential() [1/2]
arguments & lyra::arguments::sequential () inline
References eval_mode, and sequence.
Referenced by lyra::command::command(), and main().
sequential() [2/2]
arguments & lyra::arguments::sequential ()
validate() [1/2]
virtual result lyra::arguments::validate () const inline override virtual
Reimplemented from lyra::parser.
References lyra::detail::basic_result< void >::ok(), and parsers.
validate() [2/2]
virtual result lyra::arguments::validate () const inline override virtual
Reimplemented from lyra::parser.
References lyra::detail::basic_result< void >::ok(), and parsers.
Friends And Related Function Documentation
operator| [1/4]
template<typename T , typename U > std::enable_if< std::is_base_of< arguments, typenamedetail::remove_cvref< T >::type >::value, T & >::type operator| (T && self, U const & other) friend
operator| [2/4]
template<typename T , typename U > std::enable_if< std::is_base_of< arguments, typenamedetail::remove_cvref< T >::type >::value, T & >::type operator| (T && self, U const & other) friend
operator| [3/4]
template<typename T , typename U > std::enable_if< std::is_base_of< arguments, typenamedetail::remove_cvref< T >::type >::value, T & >::type operator| (T & self, U const & other) friend
operator| [4/4]
template<typename T , typename U > std::enable_if< std::is_base_of< arguments, typenamedetail::remove_cvref< T >::type >::value, T & >::type operator| (T & self, U const & other) friend
Member Data Documentation
eval_mode
evaluation lyra::arguments::eval_mode = any protected
Referenced by inclusive(), parse(), and sequential().
opt_style
std::shared_ptr< option_style > lyra::arguments::opt_style protected
Referenced by get_option_style(), lyra::cli::parse(), and lyra::cli::style().
parsers
std::vector< std::unique_ptr< parser > > lyra::arguments::parsers protected
Referenced by arguments(), add_argument(), get(), get_description_text(), get_help_text(), lyra::command::get_help_text(), get_named(), get_usage_text(), lyra::command::get_usage_text(), parse_any(), parse_sequence(), lyra::command::print_help_text_details(), and validate().
The documentation for this class was generated from the following files:
Lyra/data/single_include/lyra/lyra.hpp
Lyra/include/lyra/arguments.hpp