???: lyra::exe_name Class Reference
lyra::exe_name Class Reference
#include <exe_name.hpp>
Public Member Functions
exe_name ()
exe_name ()
template<typename LambdaT >
exe_name (LambdaT const &lambda)
template<typename LambdaT >
exe_name (LambdaT const &lambda)
exe_name (std::string &ref)
exe_name (std::string &ref)
virtual std::unique_ptr< parser > clone () const override
virtual std::unique_ptr< parser > clone () const override
std::string name () const
std::string name () const
virtual parse_result parse (detail::token_iterator const &tokens, const option_style &) const override
virtual parse_result parse (detail::token_iterator const &tokens, const option_style &) const override
parser_result set (std::string const &newName)
parser_result set (std::string const &newName)
Public Member Functions inherited from lyra::parser
virtual ~parser ()=default
virtual ~parser ()=default
virtual detail::parser_cardinality cardinality () const
virtual detail::parser_cardinality cardinality () const
virtual std::unique_ptr< parser > clone () const
virtual std::unique_ptr< parser > clone () const
std::string get_description_text () const
std::string get_description_text () const
virtual std::string get_description_text (const option_style &) const
virtual std::string get_description_text (const option_style &) const
help_text get_help_text () const
help_text get_help_text () const
virtual help_text get_help_text (const option_style &) const
virtual help_text get_help_text (const option_style &) const
virtual const parser * get_named (const std::string &n) const
virtual const parser * get_named (const std::string &n) const
std::string get_usage_text () const
std::string get_usage_text () const
virtual std::string get_usage_text (const option_style &) const
virtual std::string get_usage_text (const option_style &) const
virtual std::string get_value (size_t i) const
virtual std::string get_value (size_t i) const
virtual size_t get_value_count () const
virtual size_t get_value_count () const
virtual bool is_group () const
virtual bool is_group () const
virtual bool is_named (const std::string &n) const
virtual bool is_named (const std::string &n) const
bool is_optional () const
bool is_optional () const
virtual parse_result parse (detail::token_iterator const &tokens, const option_style &style) const =0
virtual parse_result parse (detail::token_iterator const &tokens, const option_style &style) const =0
virtual result validate () const
virtual result validate () const
Private Attributes
std::shared_ptr< std::string > m_name
std::shared_ptr< detail::BoundValueRefBase > m_ref
Additional Inherited Members
Public Types inherited from lyra::parser
using help_text = std::vector< help_text_item >
using help_text = std::vector< help_text_item >
Protected Member Functions inherited from lyra::parser
virtual void print_help_text (printer &p, const option_style &style) const
virtual void print_help_text (printer &p, const option_style &style) const
virtual void print_help_text_details (printer &p, const option_style &style) const
virtual void print_help_text_details (printer &p, const option_style &style) const
virtual void print_help_text_summary (printer &p, const option_style &style) const
virtual void print_help_text_summary (printer &p, const option_style &style) const
Constructor & Destructor Documentation
exe_name() [1/6]
lyra::exe_name::exe_name () inline
exe_name() [2/6]
lyra::exe_name::exe_name (std::string & ref) inline explicit
References m_ref.
exe_name() [3/6]
template<typename LambdaT > lyra::exe_name::exe_name (LambdaT const & lambda) explicit
References m_ref.
exe_name() [4/6]
lyra::exe_name::exe_name () inline
exe_name() [5/6]
lyra::exe_name::exe_name (std::string & ref) explicit
exe_name() [6/6]
template<typename LambdaT > lyra::exe_name::exe_name (LambdaT const & lambda) explicit
Member Function Documentation
clone() [1/2]
virtual std::unique_ptr< parser > lyra::exe_name::clone () const inline override virtual
Reimplemented from lyra::parser.
clone() [2/2]
virtual std::unique_ptr< parser > lyra::exe_name::clone () const inline override virtual
Reimplemented from lyra::parser.
name() [1/2]
std::string lyra::exe_name::name () const inline
References m_name.
Referenced by lyra::cli::get_usage_text().
name() [2/2]
std::string lyra::exe_name::name () const
parse() [1/2]
virtual parse_result lyra::exe_name::parse (detail::token_iterator const & tokens, const option_style &) const inline override virtual
Implements lyra::parser.
References lyra::no_match, and lyra::detail::basic_result< detail::parse_state >::ok().
parse() [2/2]
virtual parse_result lyra::exe_name::parse (detail::token_iterator const & tokens, const option_style &) const inline override virtual
Implements lyra::parser.
References lyra::no_match, and lyra::detail::basic_result< detail::parse_state >::ok().
set() [1/2]
parser_result lyra::exe_name::set (std::string const & newName) inline
References m_name, m_ref, lyra::matched, and lyra::detail::basic_result< T >::ok().
Referenced by lyra::cli::parse().
set() [2/2]
parser_result lyra::exe_name::set (std::string const & newName)
Member Data Documentation
m_name
std::shared_ptr< std::string > lyra::exe_name::m_name private
Referenced by name(), and set().
m_ref
std::shared_ptr< detail::BoundValueRefBase > lyra::exe_name::m_ref private
Referenced by exe_name(), and set().
The documentation for this class was generated from the following files:
Lyra/data/single_include/lyra/lyra.hpp
Lyra/include/lyra/exe_name.hpp