Skeletal: lyra::detail::result_base Class Reference
lyra::detail::result_base Class Reference
#include <result.hpp>
Public Member Functions
result_base const & base () const
result_base const & base () const
std::string errorMessage () const
std::string errorMessage () const
bool is_ok () const
bool is_ok () const
std::string message () const
std::string message () const
operator bool () const
operator bool () const
Protected Types
enum class result_kind { ok , error , ok , error }
enum class result_kind { ok , error , ok , error }
Protected Member Functions
result_base (const result_base &other)
result_base (const result_base &other)
result_base (result_kind kind, const std::string &message="")
result_base (result_kind kind, const std::string &message="")
virtual ~result_base ()=default
virtual ~result_base ()=default
result_base & operator= (const result_base &)=default
result_base & operator= (const result_base &)=default
Private Attributes
result_kind kind_
std::string message_
Member Enumeration Documentation
result_kind [1/2]
enum class lyra::detail::result_base::result_kind strong protected
Enumerator
ok
error
ok
error
result_kind [2/2]
enum class lyra::detail::result_base::result_kind strong protected
Enumerator
ok
error
ok
error
Constructor & Destructor Documentation
result_base() [1/4]
lyra::detail::result_base::result_base (result_kind kind, const std::string & message = "") inline explicit protected
result_base() [2/4]
lyra::detail::result_base::result_base (const result_base & other) inline explicit protected
~result_base() [1/2]
virtual lyra::detail::result_base::~result_base () protected virtual default
result_base() [3/4]
lyra::detail::result_base::result_base (result_kind kind, const std::string & message = "") inline explicit protected
result_base() [4/4]
lyra::detail::result_base::result_base (const result_base & other) inline explicit protected
~result_base() [2/2]
virtual lyra::detail::result_base::~result_base () protected virtual default
Member Function Documentation
base() [1/2]
result_base const & lyra::detail::result_base::base () const inline
base() [2/2]
result_base const & lyra::detail::result_base::base () const inline
errorMessage() [1/2]
std::string lyra::detail::result_base::errorMessage () const inline
References message().
errorMessage() [2/2]
std::string lyra::detail::result_base::errorMessage () const inline
References message().
is_ok() [1/2]
bool lyra::detail::result_base::is_ok () const inline
References kind_, and ok.
Referenced by operator bool().
is_ok() [2/2]
bool lyra::detail::result_base::is_ok () const inline
References kind_, and ok.
message() [1/2]
std::string lyra::detail::result_base::message () const inline
References message_.
Referenced by lyra::detail::basic_result< void >::error(), lyra::detail::basic_result< T >::error(), errorMessage(), main(), and test_val().
message() [2/2]
std::string lyra::detail::result_base::message () const inline
References message_.
operator bool() [1/2]
lyra::detail::result_base::operator bool () const inline explicit
References is_ok().
operator bool() [2/2]
lyra::detail::result_base::operator bool () const inline explicit
References is_ok().
operator=() [1/2]
result_base & lyra::detail::result_base::operator= (const result_base &) protected default
Referenced by lyra::detail::result_value_base< T >::operator=().
operator=() [2/2]
result_base & lyra::detail::result_base::operator= (const result_base &) protected default
Member Data Documentation
kind_
result_kind lyra::detail::result_base::kind_ private
Referenced by is_ok().
message_
std::string lyra::detail::result_base::message_ private
Referenced by message().
The documentation for this class was generated from the following files:
Lyra/data/single_include/lyra/lyra.hpp
Lyra/include/lyra/detail/result.hpp