???: MainNamespace::Functions::Reference Class Reference
MainNamespace::Functions::Reference Class Reference abstract
Virtual class that specifies the reference traces for testing.
#include <functions.h>
Public Member Functions
virtual ~Reference ()
virtual field dirichlet (SpaceVector< real const > const point, real const scale) const =0
Compute the (discrete) (Dirichlet) trace of the function at point.
virtual field neumann (SpaceVector< real const > const point, SpaceVector< real const > const normal, real const scale) const =0
Compute the (discrete) Neumann trace of the function at point.
virtual field waveNumber () const =0
Getter.
Detailed Description
Virtual class that specifies the reference traces for testing.
Todo:
spacetime?
Constructor & Destructor Documentation
~Reference()
virtual MainNamespace::Functions::Reference::~Reference () inline virtual
Member Function Documentation
dirichlet()
virtual field MainNamespace::Functions::Reference::dirichlet (SpaceVector< real const > const point, real const scale) const pure virtual
Compute the (discrete) (Dirichlet) trace of the function at point.
Parameters
point Point where the trace is computed.
scale Scaling for the frequency, due to material parameters.
Implemented in MainNamespace::Functions::PlaneWave, and MainNamespace::Functions::MeshOffset.
Referenced by MainNamespace::Functions::ZeroExtension::dirichlet(), and MainNamespace::Functions::MeshOffset::dirichlet().
neumann()
virtual field MainNamespace::Functions::Reference::neumann (SpaceVector< real const > const point, SpaceVector< real const > const normal, real const scale) const pure virtual
Compute the (discrete) Neumann trace of the function at point.
Parameters
point Point where the trace is computed.
normal Normal vector at point.
scale Scaling for the frequency, due to material parameters.
Implemented in MainNamespace::Functions::PlaneWave, and MainNamespace::Functions::MeshOffset.
Referenced by MainNamespace::Functions::ZeroExtension::neumann(), and MainNamespace::Functions::MeshOffset::neumann().
waveNumber()
virtual field MainNamespace::Functions::Reference::waveNumber () const pure virtual
Getter.
Returns
The (modulus of the) wave number.
Implemented in MainNamespace::Functions::PlaneWave, and MainNamespace::Functions::MeshOffset.
Referenced by MainNamespace::Functions::MeshOffset::waveNumber().
The documentation for this class was generated from the following file:
main/functions.h