Skeletal: MainNamespace::Surface::MultiSurface Class Reference
MainNamespace::Surface::MultiSurface Class Reference
Representation of a boundary.
#include <multisurface.h>
Public Types
using Children = std::vector< SingleSurface >
Public Member Functions
MultiSurface (std::string const meshFileName)
Contructor. Parse a mesh file in gmsh format and build the global mesh.
~MultiSurface ()
Destructor.
size_t dirichletBasisSize () const
Getter.
size_t neumannBasisSize () const
Getter.
size_t problemSize () const
Get the dimension of the space of Cauchy space (i.e., Dirichlet and Neumann together).
std::pair< double, double > properties () const
Print surface properties.
Result solve (AdmissibilityParameters const admissibilityParameters, Functions::MeshOffset &offset)
Compute the right-hand side, the operators, then solve the linear system.
size_t triangles () const
Getter.
size_t vertices () const
Getter.
Private Member Functions
void apply (field const scaling, avector const *const source, avector *const destination) const
Apply the Calderon operator C to source, but only on components for the trial space.
ErrorVector error (avector *const solution, Functions::MeshOffset const &reference) const
Compute the error in several ways.
void fillZeros (avector const *const source, avector *const destination) const
void filterBasis (avector const *const source, avector *const destination) const
surface3d * geometry ()
surface3d const * geometry () const
size_t interpolationNodes () const
Getter.
Mesh & mesh ()
Mesh const & mesh () const
size_t quadratureNodes () const
Getter.
field waveNumber () const
Getter.
void waveNumber (field const kappa)
Private Attributes
Children children_
List of subdomains.
MeshReader gmshInterface_
Interface to gmsh.
helmholtz3d * metric_ = nullptr
Data structure needed to generate metric data (e.g. mass matrix).
Detailed Description
Representation of a boundary.
Holds the boundary mesh and the associated mass matrices, as well as a list of SingleSurface "children", i.e., subsets of the boundary mesh which are the border of subdomains, and therefore closed manifolds.
Through its children it holds (a discretization of) the calderon operator C and therefore the calderon bilinear form c. This object and its children hold all the information needed to solve a boundary problem in variational form "Find y such that c(x,y) = rhs_(x) for all x in the chosen basis". It also knows which basis elements are unkonwns and which are given boundary data.
When solving the problem boundary data are treated with an offset function (offset_). This generate a right hand side (rhs_) and leaves homogeneous boundary conditions.
Member Typedef Documentation
Children
using MainNamespace::Surface::MultiSurface::Children = std::vector<SingleSurface>
Constructor & Destructor Documentation
MultiSurface()
MainNamespace::Surface::MultiSurface::MultiSurface (std::string const meshFileName)
Contructor. Parse a mesh file in gmsh format and build the global mesh.
Parameters
meshFileName Filename of the mesh to load.
References children_, MainNamespace::Logger::deindent(), geometry(), MainNamespace::Surface::getFromFile(), gmshInterface_, MainNamespace::Logger::green, MainNamespace::Logger::indent(), MainNamespace::interpolationPoints(), MainNamespace::Surface::kdensity, MainNamespace::Surface::kstiffness, MainNamespace::Logger::log(), MainNamespace::Mesh::membership_, mesh(), metric_, and MainNamespace::quadraturePoints().
~MultiSurface()
MainNamespace::Surface::MultiSurface::~MultiSurface ()
Destructor.
References MainNamespace::maybeFree(), and metric_.
Member Function Documentation
apply()
void MainNamespace::Surface::MultiSurface::apply (field const scaling, avector const *const source, avector *const destination) const private
Apply the Calderon operator C to source, but only on components for the trial space.
Parameters
scaling Multiplicative factor to apply.
source Input for the operator.
[out] destination destination + scaling * C (source).
References children_.
Referenced by solve().
dirichletBasisSize()
size_t MainNamespace::Surface::MultiSurface::dirichletBasisSize () const inline
Getter.
Returns
The size of the Dirichlet trial space.
References mesh(), and MainNamespace::Mesh::vertexDofs_.
Referenced by problemSize().
error()
ErrorVector MainNamespace::Surface::MultiSurface::error (avector *const solution, Functions::MeshOffset const & reference) const private
Compute the error in several ways.
Todo:
fix doc. The (D) and (N) versions are computed also including the components that should be 0, the others only on the unknown part.
Returns
The following error norms (in order): energy; max; max(D); max(N); l2; l2(D); l2(N).
Todo:
relative error.
Parameters
solution Discrete solution vector.
reference Exact solution (reference).
References children_, gmshInterface_, MainNamespace::Logger::log(), MainNamespace::Logger::magenta, metric_, MainNamespace::reference(), MainNamespace::MeshReader::saveView(), and MainNamespace::MeshReader::solution.
Referenced by solve().
fillZeros()
void MainNamespace::Surface::MultiSurface::fillZeros (avector const *const source, avector *const destination) const inline private
Fill destination with the elements of source or 0.
Fill the elements of destination corresponding to a base element with the appropriate element in source, set the others to 0. Use nonZero_ to determine if an index corresponds to a base element.
Parameters
source vector with the components not corresponding to a basis element removed.
destination vector with the components not corresponding to a basis element set to 0.
References problemSize(), triangles(), and vertices().
filterBasis()
void MainNamespace::Surface::MultiSurface::filterBasis (avector const *const source, avector *const destination) const inline private
Copy the rest to destination.Remove the components of source not part of the basis of the trial space.
Parameters
source Source vector of length triangles() + .@param[out] destination Filtered vector of length problemSize(). Must be already allocated.
References problemSize(), triangles(), and vertices().
geometry() [1/2]
surface3d * MainNamespace::Surface::MultiSurface::geometry () inline private
References mesh(), and MainNamespace::Mesh::mesh_.
Referenced by MultiSurface(), properties(), triangles(), and vertices().
geometry() [2/2]
surface3d const * MainNamespace::Surface::MultiSurface::geometry () const inline private
References mesh(), and MainNamespace::Mesh::mesh_.
interpolationNodes()
size_t MainNamespace::Surface::MultiSurface::interpolationNodes () const inline private
Getter.
Returns
The number of interpolation nodes.
Todo:
per dimensor or total?.
References metric_.
mesh() [1/2]
Mesh & MainNamespace::Surface::MultiSurface::mesh () inline private
References gmshInterface_, and MainNamespace::MeshReader::mesh().
Referenced by MultiSurface(), dirichletBasisSize(), geometry(), and neumannBasisSize().
mesh() [2/2]
Mesh const & MainNamespace::Surface::MultiSurface::mesh () const inline private
References gmshInterface_, and MainNamespace::MeshReader::mesh().
neumannBasisSize()
size_t MainNamespace::Surface::MultiSurface::neumannBasisSize () const inline
Getter.
Returns
The size of the Neumann trial space.
References mesh(), and MainNamespace::Mesh::triangleDofs_.
Referenced by problemSize().
problemSize()
size_t MainNamespace::Surface::MultiSurface::problemSize () const inline
Get the dimension of the space of Cauchy space (i.e., Dirichlet and Neumann together).
Returns
The size of the Cauchy trial space.
References dirichletBasisSize(), and neumannBasisSize().
Referenced by fillZeros(), filterBasis(), solve(), and testProblem().
properties()
std::pair< double, double > MainNamespace::Surface::MultiSurface::properties () const
Print surface properties.
Returns
Mesh size (widest element) and ratio between minimum and maximum size.
References children_, geometry(), MainNamespace::Logger::log(), triangles(), and vertices().
Referenced by testProblem().
quadratureNodes()
size_t MainNamespace::Surface::MultiSurface::quadratureNodes () const inline private
Getter.
Returns
The number of quadrature nodes.
Todo:
per dimensor or total?.
References metric_.
solve()
Result MainNamespace::Surface::MultiSurface::solve (AdmissibilityParameters const admissibilityParameters, Functions::MeshOffset & offset)
Compute the right-hand side, the operators, then solve the linear system.
Returns
The number of iterations, and the error with respect to the reference, computed in different ways.
Parameters
admissibilityParameters Admissibility parameters to build the operators.
offset Offset function, and information about the reference solution.
References apply(), MainNamespace::Surface::SingleSurface::buildOperator(), children_, MainNamespace::Surface::doGmres(), error(), MainNamespace::AdmissibilityParameters::eta1, MainNamespace::AdmissibilityParameters::eta2, MainNamespace::AdmissibilityParameters::eta3, MainNamespace::Surface::forwardChildren(), MainNamespace::Surface::forwardChildrenC(), gmshInterface_, MainNamespace::Surface::SingleSurface::makeMultiRhs(), MainNamespace::Surface::SingleSurface::makeOffset(), MainNamespace::Surface::SingleSurface::makeSingleRhs(), metric_, problemSize(), MainNamespace::MeshReader::rhs, MainNamespace::MeshReader::saveView(), waveNumber(), and MainNamespace::AdmissibilityParameters::waveNumber.
Referenced by testProblem().
triangles()
size_t MainNamespace::Surface::MultiSurface::triangles () const inline
Getter.
Returns
Number of triangles in the mesh.
References geometry().
Referenced by fillZeros(), filterBasis(), and properties().
vertices()
size_t MainNamespace::Surface::MultiSurface::vertices () const inline
Getter.
Returns
Number of vertices in the mesh.
References geometry().
Referenced by fillZeros(), filterBasis(), and properties().
waveNumber() [1/2]
field MainNamespace::Surface::MultiSurface::waveNumber () const inline private
Getter.
Returns
The wave number.
References metric_.
Referenced by solve().
waveNumber() [2/2]
void MainNamespace::Surface::MultiSurface::waveNumber (field const kappa) inline private
References metric_.
Member Data Documentation
children_
Children MainNamespace::Surface::MultiSurface::children_ private
List of subdomains.
Referenced by MultiSurface(), apply(), error(), properties(), and solve().
gmshInterface_
MeshReader MainNamespace::Surface::MultiSurface::gmshInterface_ mutable private
Interface to gmsh.
Referenced by MultiSurface(), error(), mesh(), and solve().
metric_
helmholtz3d* MainNamespace::Surface::MultiSurface::metric_ = nullptr private
Data structure needed to generate metric data (e.g. mass matrix).
Referenced by MultiSurface(), ~MultiSurface(), error(), interpolationNodes(), quadratureNodes(), solve(), and waveNumber().
The documentation for this class was generated from the following files:
main/multisurface.h
main/multisurface.cpp