Skeletal: lyra::detail::token_iterator Class Reference
lyra::detail::token_iterator Class Reference
#include <tokens.hpp>
Public Member Functions
template<typename Span >
token_iterator (Span const &args, const option_style &opt_style)
template<typename Span >
token_iterator (Span const &args, const option_style &opt_style)
token argument () const
token argument () const
bool has_long_option_prefix () const noexcept
bool has_long_option_prefix () const noexcept
bool has_option_prefix () const noexcept
bool has_option_prefix () const noexcept
bool has_short_option_prefix () const noexcept
bool has_short_option_prefix () const noexcept
bool has_value_delimiter () const noexcept
bool has_value_delimiter () const noexcept
operator bool () const noexcept
operator bool () const noexcept
token option () const
token option () const
token_iterator & pop (const token &, const token &)
token_iterator & pop (const token &, const token &)
token_iterator & pop (const token &arg_or_opt)
token_iterator & pop (const token &arg_or_opt)
token value () const
token value () const
Static Public Member Functions
static bool is_prefixed (const std::string &prefix, std::size_t size, const std::string &s)
static bool is_prefixed (const std::string &prefix, std::size_t size, const std::string &s)
Private Member Functions
bool is_opt_prefix (char c) const noexcept
bool is_opt_prefix (char c) const noexcept
bool is_prefix_char (const std::string &prefix, std::size_t size, std::string::value_type c) const noexcept
bool is_prefix_char (const std::string &prefix, std::size_t size, std::string::value_type c) const noexcept
std::string prefix_value (const std::string &prefix, std::size_t size) const
std::string prefix_value (const std::string &prefix, std::size_t size) const
Private Attributes
std::vector< std::string >::const_iterator args_e
std::vector< std::string >::const_iterator args_i
std::string::size_type args_i_sub
const option_style & style
Constructor & Destructor Documentation
token_iterator() [1/2]
template<typename Span > lyra::detail::token_iterator::token_iterator (Span const & args, const option_style & opt_style) inline explicit
token_iterator() [2/2]
template<typename Span > lyra::detail::token_iterator::token_iterator (Span const & args, const option_style & opt_style) inline explicit
Member Function Documentation
argument() [1/2]
token lyra::detail::token_iterator::argument () const inline
References args_i, and lyra::detail::argument.
Referenced by lyra::cli::parse(), lyra::literal::parse(), lyra::arg::parse(), lyra::group::parse(), lyra::arguments::parse_any(), and lyra::arguments::parse_sequence().
argument() [2/2]
token lyra::detail::token_iterator::argument () const inline
References args_i, and lyra::detail::argument.
has_long_option_prefix() [1/2]
bool lyra::detail::token_iterator::has_long_option_prefix () const inline noexcept
References args_e, args_i, is_prefixed(), lyra::option_style::long_option_prefix, lyra::option_style::long_option_size, and style.
Referenced by has_option_prefix(), option(), and value().
has_long_option_prefix() [2/2]
bool lyra::detail::token_iterator::has_long_option_prefix () const inline noexcept
References args_e, args_i, is_prefixed(), lyra::option_style::long_option_prefix, lyra::option_style::long_option_size, and style.
has_option_prefix() [1/2]
bool lyra::detail::token_iterator::has_option_prefix () const inline noexcept
References has_long_option_prefix(), and has_short_option_prefix().
Referenced by value().
has_option_prefix() [2/2]
bool lyra::detail::token_iterator::has_option_prefix () const inline noexcept
References has_long_option_prefix(), and has_short_option_prefix().
has_short_option_prefix() [1/2]
bool lyra::detail::token_iterator::has_short_option_prefix () const inline noexcept
References args_e, args_i, is_prefixed(), lyra::option_style::short_option_prefix, lyra::option_style::short_option_size, and style.
Referenced by has_option_prefix(), option(), pop(), and value().
has_short_option_prefix() [2/2]
bool lyra::detail::token_iterator::has_short_option_prefix () const inline noexcept
References args_e, args_i, is_prefixed(), lyra::option_style::short_option_prefix, lyra::option_style::short_option_size, and style.
has_value_delimiter() [1/2]
bool lyra::detail::token_iterator::has_value_delimiter () const inline noexcept
References args_e, args_i, style, and lyra::option_style::value_delimiters.
Referenced by option(), pop(), and value().
has_value_delimiter() [2/2]
bool lyra::detail::token_iterator::has_value_delimiter () const inline noexcept
References args_e, args_i, style, and lyra::option_style::value_delimiters.
is_opt_prefix() [1/2]
bool lyra::detail::token_iterator::is_opt_prefix (char c) const inline private noexcept
References is_prefix_char(), lyra::option_style::long_option_prefix, lyra::option_style::long_option_size, lyra::option_style::short_option_prefix, lyra::option_style::short_option_size, and style.
is_opt_prefix() [2/2]
bool lyra::detail::token_iterator::is_opt_prefix (char c) const inline private noexcept
References is_prefix_char(), lyra::option_style::long_option_prefix, lyra::option_style::long_option_size, lyra::option_style::short_option_prefix, lyra::option_style::short_option_size, and style.
is_prefix_char() [1/2]
bool lyra::detail::token_iterator::is_prefix_char (const std::string & prefix, std::size_t size, std::string::value_type c) const inline private noexcept
References MainNamespace::size().
Referenced by is_opt_prefix().
is_prefix_char() [2/2]
bool lyra::detail::token_iterator::is_prefix_char (const std::string & prefix, std::size_t size, std::string::value_type c) const inline private noexcept
References MainNamespace::size().
is_prefixed() [1/2]
static bool lyra::detail::token_iterator::is_prefixed (const std::string & prefix, std::size_t size, const std::string & s) inline static
References MainNamespace::size().
Referenced by has_long_option_prefix(), has_short_option_prefix(), and lyra::opt::normalise_opt().
is_prefixed() [2/2]
static bool lyra::detail::token_iterator::is_prefixed (const std::string & prefix, std::size_t size, const std::string & s) inline static
References MainNamespace::size().
operator bool() [1/2]
lyra::detail::token_iterator::operator bool () const inline explicit noexcept
References args_e, and args_i.
operator bool() [2/2]
lyra::detail::token_iterator::operator bool () const inline explicit noexcept
References args_e, and args_i.
option() [1/2]
token lyra::detail::token_iterator::option () const inline
References args_i, args_i_sub, has_long_option_prefix(), has_short_option_prefix(), has_value_delimiter(), lyra::detail::option, prefix_value(), lyra::option_style::short_option_prefix, lyra::option_style::short_option_size, style, and lyra::option_style::value_delimiters.
Referenced by lyra::opt::parse().
option() [2/2]
token lyra::detail::token_iterator::option () const inline
References args_i, args_i_sub, has_long_option_prefix(), has_short_option_prefix(), has_value_delimiter(), lyra::detail::option, prefix_value(), lyra::option_style::short_option_prefix, lyra::option_style::short_option_size, style, and lyra::option_style::value_delimiters.
pop() [1/4]
token_iterator & lyra::detail::token_iterator::pop (const token & , const token &) inline
References args_i, args_i_sub, has_short_option_prefix(), has_value_delimiter(), lyra::option_style::short_option_size, and style.
pop() [2/4]
token_iterator & lyra::detail::token_iterator::pop (const token & , const token &) inline
References args_i, args_i_sub, has_short_option_prefix(), has_value_delimiter(), lyra::option_style::short_option_size, and style.
pop() [3/4]
token_iterator & lyra::detail::token_iterator::pop (const token & arg_or_opt) inline
References args_i, args_i_sub, has_short_option_prefix(), lyra::detail::option, lyra::option_style::short_option_size, style, and lyra::detail::token::type.
Referenced by lyra::literal::parse(), and lyra::arg::parse().
pop() [4/4]
token_iterator & lyra::detail::token_iterator::pop (const token & arg_or_opt) inline
References args_i, args_i_sub, has_short_option_prefix(), lyra::detail::option, lyra::option_style::short_option_size, and style.
prefix_value() [1/2]
std::string lyra::detail::token_iterator::prefix_value (const std::string & prefix, std::size_t size) const inline private
References MainNamespace::size().
Referenced by option().
prefix_value() [2/2]
std::string lyra::detail::token_iterator::prefix_value (const std::string & prefix, std::size_t size) const inline private
References MainNamespace::size().
value() [1/2]
token lyra::detail::token_iterator::value () const inline
References args_e, args_i, args_i_sub, lyra::detail::argument, has_long_option_prefix(), has_option_prefix(), has_short_option_prefix(), has_value_delimiter(), style, and lyra::option_style::value_delimiters.
value() [2/2]
token lyra::detail::token_iterator::value () const inline
References args_e, args_i, args_i_sub, lyra::detail::argument, has_long_option_prefix(), has_option_prefix(), has_short_option_prefix(), has_value_delimiter(), style, and lyra::option_style::value_delimiters.
Member Data Documentation
args_e
std::vector< std::string >::const_iterator lyra::detail::token_iterator::args_e private
Referenced by has_long_option_prefix(), has_short_option_prefix(), has_value_delimiter(), operator bool(), and value().
args_i
std::vector< std::string >::const_iterator lyra::detail::token_iterator::args_i private
Referenced by argument(), has_long_option_prefix(), has_short_option_prefix(), has_value_delimiter(), operator bool(), option(), pop(), and value().
args_i_sub
std::string::size_type lyra::detail::token_iterator::args_i_sub private
Referenced by option(), pop(), and value().
style
const option_style & lyra::detail::token_iterator::style private
Referenced by has_long_option_prefix(), has_short_option_prefix(), has_value_delimiter(), is_opt_prefix(), option(), pop(), and value().
The documentation for this class was generated from the following files:
Lyra/data/single_include/lyra/lyra.hpp
Lyra/include/lyra/detail/tokens.hpp