Skeletal: MainNamespace::Functions::PlaneWave Class Reference
MainNamespace::Functions::PlaneWave Class Reference
Plane wave reference.
#include <functions.h>
Public Member Functions
PlaneWave ()=delete
PlaneWave (SpaceVector< double const > const frequency, field const waveNumber)
Construct a reference plane wave.
virtual field dirichlet (SpaceVector< real const > const point, real const scale) const override
Compute the (discrete) (Dirichlet) trace of the function at point.
virtual field neumann (SpaceVector< real const > const point, SpaceVector< real const > const normal, real const scale) const override
Compute the (discrete) Neumann trace of the function at point.
virtual field waveNumber () const override
Getter.
Public Member Functions inherited from MainNamespace::Functions::Reference
virtual ~Reference ()
virtual field dirichlet (SpaceVector< real const > const point, real const scale) const =0
Compute the (discrete) (Dirichlet) trace of the function at point.
virtual field neumann (SpaceVector< real const > const point, SpaceVector< real const > const normal, real const scale) const =0
Compute the (discrete) Neumann trace of the function at point.
virtual field waveNumber () const =0
Getter.
Private Attributes
SpaceVector< field > frequency_
Normalized wave direction. Its norm is waveNumber_.
field waveNumber_
Detailed Description
Plane wave reference.
Constructor & Destructor Documentation
PlaneWave() [1/2]
MainNamespace::Functions::PlaneWave::PlaneWave () delete
PlaneWave() [2/2]
MainNamespace::Functions::PlaneWave::PlaneWave (SpaceVector< double const > const frequency, field const waveNumber)
Construct a reference plane wave.
Parameters
frequency Wave direction (will be normalized).
waveNumber Wave number (modulus).
References frequency_, MainNamespace::Logger::log(), MainNamespace::spaceDimension, waveNumber(), and waveNumber_.
Member Function Documentation
dirichlet()
field MainNamespace::Functions::PlaneWave::dirichlet (SpaceVector< real const > const point, real const scale) const override virtual
Compute the (discrete) (Dirichlet) trace of the function at point.
Parameters
point Point where the trace is computed.
scale Scaling for the frequency, due to material parameters.
Implements MainNamespace::Functions::Reference.
References frequency_, and MainNamespace::spaceDimension.
neumann()
field MainNamespace::Functions::PlaneWave::neumann (SpaceVector< real const > const point, SpaceVector< real const > const normal, real const scale) const override virtual
Compute the (discrete) Neumann trace of the function at point.
Parameters
point Point where the trace is computed.
normal Normal vector at point.
scale Scaling for the frequency, due to material parameters.
Implements MainNamespace::Functions::Reference.
References direction, frequency_, and MainNamespace::spaceDimension.
waveNumber()
virtual field MainNamespace::Functions::PlaneWave::waveNumber () const inline override virtual
Getter.
Returns
The (modulus of the) wave number.
Implements MainNamespace::Functions::Reference.
References waveNumber_.
Referenced by PlaneWave().
Member Data Documentation
frequency_
SpaceVector<field> MainNamespace::Functions::PlaneWave::frequency_ private
Normalized wave direction. Its norm is waveNumber_.
Referenced by PlaneWave(), dirichlet(), and neumann().
waveNumber_
field MainNamespace::Functions::PlaneWave::waveNumber_ private
Referenced by PlaneWave(), and waveNumber().
The documentation for this class was generated from the following files:
main/functions.h
main/functions.cpp