Skeletal: MainNamespace::CFunctions Namespace Reference
MainNamespace::CFunctions Namespace Reference
Functions
void freeCPointer (amatrix *object)
void freeCPointer (avector *object)
void freeCPointer (cluster *object)
void freeCPointer (clustergeometry *object)
void freeCPointer (dblock *object)
void freeCPointer (dcluster *object)
void freeCPointer (dclusteroperator *object)
void freeCPointer (dh2matrix *object)
void freeCPointer (diradmdata *object)
void freeCPointer (double *object)
void freeCPointer (helmholtz3d *object)
void freeCPointer (leveldir *object)
void freeCPointer (reporter *object)
void freeCPointer (sparsematrix *object)
void freeCPointer (stopwatch *object)
void freeCPointer (surface3d *object)
Function Documentation
freeCPointer() [1/16]
void MainNamespace::CFunctions::freeCPointer (amatrix * object) inline
Referenced by MainNamespace::maybeFree(), and MainNamespace::Surface::SingleSurface::setupCluster().
freeCPointer() [2/16]
void MainNamespace::CFunctions::freeCPointer (avector * object) inline
freeCPointer() [3/16]
void MainNamespace::CFunctions::freeCPointer (cluster * object) inline
freeCPointer() [4/16]
void MainNamespace::CFunctions::freeCPointer (clustergeometry * object) inline
freeCPointer() [5/16]
void MainNamespace::CFunctions::freeCPointer (dblock * object) inline
freeCPointer() [6/16]
void MainNamespace::CFunctions::freeCPointer (dcluster * object) inline
freeCPointer() [7/16]
void MainNamespace::CFunctions::freeCPointer (dclusteroperator * object) inline
freeCPointer() [8/16]
void MainNamespace::CFunctions::freeCPointer (dh2matrix * object) inline
freeCPointer() [9/16]
void MainNamespace::CFunctions::freeCPointer (diradmdata * object) inline
References del_diradmdata().
freeCPointer() [10/16]
void MainNamespace::CFunctions::freeCPointer (double * object) inline
freeCPointer() [11/16]
void MainNamespace::CFunctions::freeCPointer (helmholtz3d * object) inline
freeCPointer() [12/16]
void MainNamespace::CFunctions::freeCPointer (leveldir * object) inline
freeCPointer() [13/16]
void MainNamespace::CFunctions::freeCPointer (reporter * object) inline
freeCPointer() [14/16]
void MainNamespace::CFunctions::freeCPointer (sparsematrix * object) inline
freeCPointer() [15/16]
void MainNamespace::CFunctions::freeCPointer (stopwatch * object) inline
freeCPointer() [16/16]
void MainNamespace::CFunctions::freeCPointer (surface3d * object) inline