Skeletal: MainNamespace::Logger Namespace Reference
MainNamespace::Logger Namespace Reference
Namespaces
namespace anonymous_namespace{logger.cpp}
namespace anonymous_namespace{logger.h}
Classes
class FilePointerDevice
Logger for a file stored on the filesystem. Log to a given file. Lack of color support is assumed. The file is open during construction and closed at destruction time, after flushing the stream. No check that the file open operation was succesul is performed.
class OutputDevice
class StdStreamDevice
Logger for a standard stream. Log to a given FILE pointer, writing log messages immediately. Color and lack of seek are assumed. The stream is flushed but the file is not closed at destruction time. No check that the file is still open at any point is performed. It is recommended to use this only for stdout or stderr.
Enumerations
enum class Color {
red , green , yellow , blue ,
magenta , cyan , reset
}
enum class Level : int { min = -1 - getUnderlying(LevelPrivate::output) }
Functions
void addLogDevice (std::shared_ptr< OutputDevice > device, Level const logLevel)
Add a logging device.
void addLogFile (char const *const filename, Level const logLevel)
Add a logger for a given file. The logs are appended to it.
void addLogStderr (Level const logLevel)
Add a logger for stderr.
void addLogStdout (Level const logLevel)
Add a logger for stdout.
char const * colorString (Color color)
void deindent ()
Decrease indentation level in the logger.
void forwardLog (Color const color, Level const severity, bool const newline, char const *const format,...)
void indent ()
Increase indentation level in the logger.
template<class... Args>
void log (char const *const format, Args... args)
Equivalent to log(Level::Warning, format, args)
template<class... Args>
void log (Color const color, Level const severity, bool const newline, char const *const format, Args... args)
template<class... Args>
void log (Color const color, Level const severity, char const *const format, Args... args)
Equivalent to log(color, severity, format, false, args)
template<class... Args>
void log (Level const severity, char const *const format, Args... args)
Equivalent to log(Color:reset, severity, format, args)
Variables
constexpr char const * colorStrings [getUnderlying(Color::reset)+1] = {"\x1b[31m", "\x1b[32m", "\x1b[33m", "\x1b[34m", "\x1b[35m", "\x1b[36m", "\x1b[0m"}
constexpr bool logEnabled = true
Build the message to print and forward it to the loggers.
Detailed Description
Helper functions to display log messages based on the severity.
Unsetting the preprocessor variable _Logging makes all the logging functions inline empty functions, which should then be optimized away at compile time (unless inlining is disabled).
Enumeration Type Documentation
Color
enum class MainNamespace::Logger::Color strong
Enumerator
red
List of colors accepted by log functions.
ANSI_COLOR_RED
green
ANSI_COLOR_GREEN.
yellow
ANSI_COLOR_YELLOW.
blue
ANSI_COLOR_BLUE.
magenta
ANSI_COLOR_MAGENTA.
cyan
ANSI_COLOR_CYAN.
reset
ANSI_COLOR_RESET.
Level
enum class MainNamespace::Logger::Level : int strong
Possible log levels; negative values are errors, positive are informations, 0 means "output".
Enumerator
min
don't use it as a message severity level; use it as the log level to see everything
Function Documentation
addLogDevice()
void MainNamespace::Logger::addLogDevice (std::shared_ptr< OutputDevice > device, Level const logLevel)
Add a logging device.
Parameters
device New device to add.
logLevel Logging level of the device.
References log(), MainNamespace::Logger::anonymous_namespace{logger.cpp}::logs_, and red.
Referenced by addLogFile(), addLogStderr(), and addLogStdout().
addLogFile()
void MainNamespace::Logger::addLogFile (char const *const filename, Level const logLevel)
Add a logger for a given file. The logs are appended to it.
Parameters
filename Name of the file to open.
logLevel Logging level of the device.
References addLogDevice().
addLogStderr()
void MainNamespace::Logger::addLogStderr (Level const logLevel)
Add a logger for stderr.
Parameters
logLevel Logging level of the device.
References addLogDevice().
addLogStdout()
void MainNamespace::Logger::addLogStdout (Level const logLevel)
Add a logger for stdout.
Parameters
logLevel Logging level of the device.
References addLogDevice().
Referenced by main().
colorString()
char const * MainNamespace::Logger::colorString (Color color) inline
References colorStrings, and MainNamespace::getUnderlying().
Referenced by MainNamespace::Logger::StdStreamDevice::print().
deindent()
void MainNamespace::Logger::deindent ()
Decrease indentation level in the logger.
References MainNamespace::Logger::anonymous_namespace{logger.cpp}::logs_.
Referenced by MainNamespace::Surface::MultiSurface::MultiSurface(), MainNamespace::Surface::getFromFile(), main(), and testProblem().
forwardLog()
void MainNamespace::Logger::forwardLog (Color const color, Level const severity, bool const newline, char const *const format, ...)
Parameters
color As in OutputDevice::print.
severity As in OutputDevice::print.
newline Whether to add a new line. Intended as a mean to counteract the spurious indentation spaces when continuing on the same line. Might have more advantages as well.
format As in printf.
... As in printf.
References MainNamespace::Logger::anonymous_namespace{logger.cpp}::logs_.
Referenced by log().
indent()
void MainNamespace::Logger::indent ()
Increase indentation level in the logger.
References MainNamespace::Logger::anonymous_namespace{logger.cpp}::logs_.
Referenced by MainNamespace::Surface::MultiSurface::MultiSurface(), MainNamespace::Surface::SingleSurface::buildOperator(), MainNamespace::Surface::getFromFile(), main(), lyra::ostream_printer::option(), lyra::ostream_printer::paragraph(), and testProblem().
log() [1/4]
template<class... Args> void MainNamespace::Logger::log (char const *const format, Args... args) inline
Equivalent to log(Level::Warning, format, args)
References forwardLog(), reset, and MainNamespace::warning().
log() [2/4]
template<class... Args> void MainNamespace::Logger::log (Color const color, Level const severity, bool const newline, char const *const format, Args... args) inline
Log a message.
Parameters
color Color of the log, if the device supports it.
severity Log severity.
newline Whether to add a new line. Intended as a mean to counteract the spurious indentation spaces when continuing on the same line. Might have more advantages as well.
format Format, as in printf
args Additional arguments, according to the rules of printf.
References forwardLog().
Referenced by MainNamespace::Surface::MultiSurface::MultiSurface(), MainNamespace::Options::Options(), MainNamespace::Functions::PlaneWave::PlaneWave(), MainNamespace::Surface::SingleSurface::SingleSurface(), MainNamespace::MeshReader::~MeshReader(), MainNamespace::Options::~Options(), addLogDevice(), MainNamespace::DH2MatrixWrapper::build(), MainNamespace::buildImplicitClusterBasis(), MainNamespace::buildOperator(), MainNamespace::buildSurface(), MainNamespace::Surface::SingleSurface::check(), MainNamespace::compressRowColumnFar(), MainNamespace::Surface::SingleSurface::computeDifferenceNorm(), MainNamespace::Surface::doGmres(), MainNamespace::Surface::energyNorm(), MainNamespace::Surface::MultiSurface::error(), MainNamespace::getElements(), MainNamespace::Surface::getFromFile(), main(), MainNamespace::makeDirections(), MainNamespace::Surface::SingleSurface::makeMultiRhs(), MainNamespace::Surface::SingleSurface::makeSingleRhs(), MainNamespace::Surface::makeTmpApply(), MainNamespace::operatorSpaces(), MainNamespace::outputFile(), MainNamespace::MeshReader::parseMesh(), MainNamespace::parseNodesPhysical(), MainNamespace::parsePhysicalName(), MainNamespace::Surface::MultiSurface::properties(), MainNamespace::Surface::SingleSurface::properties(), MainNamespace::reorderElements(), MainNamespace::Options::report(), MainNamespace::reportClusterCompression(), MainNamespace::reportParallelization(), MainNamespace::MeshReader::saveView(), MainNamespace::Surface::SingleSurface::setupCluster(), MainNamespace::splitTriangles(), testProblem(), and MainNamespace::Mesh::writeMesh().
log() [3/4]
template<class... Args> void MainNamespace::Logger::log (Color const color, Level const severity, char const *const format, Args... args) inline
Equivalent to log(color, severity, format, false, args)
References forwardLog().
log() [4/4]
template<class... Args> void MainNamespace::Logger::log (Level const severity, char const *const format, Args... args) inline
Equivalent to log(Color:reset, severity, format, args)
References forwardLog(), and reset.
Variable Documentation
colorStrings
constexpr char const* MainNamespace::Logger::colorStrings[getUnderlying(Color::reset)+1] = {"\x1b[31m", "\x1b[32m", "\x1b[33m", "\x1b[34m", "\x1b[35m", "\x1b[36m", "\x1b[0m"} constexpr
Referenced by colorString().
logEnabled
constexpr bool MainNamespace::Logger::logEnabled = true constexpr
Build the message to print and forward it to the loggers.
Compile-time constant indicating whether logging support was enabled.