???: lyra Namespace Reference
lyra Namespace Reference
Namespaces
namespace detail
Classes
class arg
class args
class arguments
class bound_parser
class cli
class command
class composable_parser
struct default_parser_customization
class exe_name
class group
class help
class literal
class main
class opt
struct option_style
class ostream_printer
class parse_result
class parser
struct parser_customization
class printer
Typedefs
using cli_parser = cli
using parser_result = detail::basic_result< parser_result_type >
using result = detail::basic_result< void >
Enumerations
enum class parser_result_type {
matched , no_match , short_circuit_all , matched ,
no_match , short_circuit_all
}
enum class parser_result_type {
matched , no_match , short_circuit_all , matched ,
no_match , short_circuit_all
}
Functions
template<typename T , typename U >
std::unique_ptr< parser > make_clone (const U *source)
std::unique_ptr< printer > make_printer (std::ostream &os_)
template<typename T >
T & operator<< (T &os, arguments const &a)
template<typename T >
T & operator<< (T &os, cli const &c)
template<typename DerivedT , typename T >
cli operator| (composable_parser< DerivedT > const &thing, T const &other)
std::string to_string (parser_result_type v)
detail::BoundVal< std::string > val (const char *v)
template<typename T >
detail::BoundVal< T > val (T &&v)
Typedef Documentation
cli_parser
typedef cli lyra::cli_parser
parser_result
typedef detail::basic_result< parser_result_type > lyra::parser_result
result
typedef detail::basic_result< void > lyra::result
Enumeration Type Documentation
parser_result_type [1/2]
enum class lyra::parser_result_type strong
Enumerator
matched
no_match
short_circuit_all
matched
no_match
short_circuit_all
parser_result_type [2/2]
enum class lyra::parser_result_type strong
Enumerator
matched
no_match
short_circuit_all
matched
no_match
short_circuit_all
Function Documentation
make_clone()
template<typename T , typename U > std::unique_ptr< parser > lyra::make_clone (const U * source)
make_printer()
std::unique_ptr< printer > lyra::make_printer (std::ostream & os_) inline
Referenced by lyra::arguments::print_help().
operator<<() [1/2]
template<typename T > T & lyra::operator<< (T & os, arguments const & a)
References lyra::arguments::print_help().
operator<<() [2/2]
template<typename T > T & lyra::operator<< (T & os, cli const & c)
operator|()
template<typename DerivedT , typename T > cli lyra::operator| (composable_parser< DerivedT > const & thing, T const & other)
to_string()
std::string lyra::to_string (parser_result_type v) inline
References matched, no_match, and short_circuit_all.
val() [1/2]
detail::BoundVal< std::string > lyra::val (const char * v) inline
val() [2/2]
template<typename T > detail::BoundVal< T > lyra::val (T && v)
Referenced by lyra::bound_parser< Derived >::bound_parser(), lyra::opt::opt(), lyra::detail::result_value_base< T >::result_value_base(), lyra::detail::choices_set< T >::contains_value(), lyra::detail::choices_check< Lambda >::contains_value(), lyra::detail::basic_result< T >::error(), main(), lyra::detail::basic_result< T >::ok(), lyra::main::operator()(), and lyra::detail::choices_set< T >::to_string().