???: lyra::detail::choices_set< T > Struct Template Reference
lyra::detail::choices_set< T > Struct Template Reference
#include <choices.hpp>
Public Member Functions
choices_set (const std::vector< T > &vals)
choices_set (const std::vector< T > &vals)
template<typename... Vals>
choices_set (Vals... vals)
template<typename... Vals>
choices_set (Vals... vals)
parser_result contains_value (std::string const &val) const override
parser_result contains_value (std::string const &val) const override
std::string to_string () const
std::string to_string () const
Public Member Functions inherited from lyra::detail::choices_base
virtual ~choices_base ()=default
virtual ~choices_base ()=default
virtual parser_result contains_value (std::string const &val) const =0
virtual parser_result contains_value (std::string const &val) const =0
Public Attributes
std::vector< T > values
Protected Member Functions
choices_set (std::initializer_list< T > const &vals)
choices_set (std::initializer_list< T > const &vals)
Constructor & Destructor Documentation
choices_set() [1/6]
template<typename T > template<typename... Vals> lyra::detail::choices_set< T >::choices_set (Vals... vals) inline explicit
choices_set() [2/6]
template<typename T > lyra::detail::choices_set< T >::choices_set (const std::vector< T > & vals) inline explicit
choices_set() [3/6]
template<typename T > lyra::detail::choices_set< T >::choices_set (std::initializer_list< T > const & vals) inline explicit protected
choices_set() [4/6]
template<typename T > template<typename... Vals> lyra::detail::choices_set< T >::choices_set (Vals... vals) inline explicit
choices_set() [5/6]
template<typename T > lyra::detail::choices_set< T >::choices_set (const std::vector< T > & vals) inline explicit
choices_set() [6/6]
template<typename T > lyra::detail::choices_set< T >::choices_set (std::initializer_list< T > const & vals) inline explicit protected
Member Function Documentation
contains_value() [1/2]
template<typename T > parser_result lyra::detail::choices_set< T >::contains_value (std::string const & val) const inline override virtual
Implements lyra::detail::choices_base.
References lyra::detail::basic_result< T >::error(), lyra::matched, lyra::no_match, lyra::detail::basic_result< T >::ok(), lyra::detail::parse_string(), lyra::detail::choices_set< T >::to_string(), lyra::val(), and lyra::detail::choices_set< T >::values.
contains_value() [2/2]
template<typename T > parser_result lyra::detail::choices_set< T >::contains_value (std::string const & val) const inline override virtual
Implements lyra::detail::choices_base.
References lyra::detail::basic_result< T >::error(), lyra::matched, lyra::no_match, lyra::detail::basic_result< T >::ok(), lyra::detail::parse_string(), lyra::detail::choices_set< T >::to_string(), lyra::val(), and lyra::detail::choices_set< T >::values.
to_string() [1/2]
template<typename T > std::string lyra::detail::choices_set< T >::to_string () const inline
References lyra::detail::to_string(), lyra::val(), and lyra::detail::choices_set< T >::values.
Referenced by lyra::detail::choices_set< T >::contains_value().
to_string() [2/2]
template<typename T > std::string lyra::detail::choices_set< T >::to_string () const inline
References lyra::detail::to_string(), lyra::val(), and lyra::detail::choices_set< T >::values.
Member Data Documentation
values
template<typename T > std::vector< T > lyra::detail::choices_set< T >::values
Referenced by lyra::detail::choices_set< T >::contains_value(), and lyra::detail::choices_set< T >::to_string().
The documentation for this struct was generated from the following files:
Lyra/data/single_include/lyra/lyra.hpp
Lyra/include/lyra/detail/choices.hpp