Skeletal: lyra::detail::choices_check< Lambda > Struct Template Reference
lyra::detail::choices_check< Lambda > Struct Template Reference
#include <choices.hpp>
Public Types
using value_type = typename unary_lambda_traits< Lambda >::ArgType
using value_type = typename unary_lambda_traits< Lambda >::ArgType
Public Member Functions
choices_check (Lambda const &checker_function)
choices_check (Lambda const &checker_function)
parser_result contains_value (std::string const &val) const override
parser_result contains_value (std::string const &val) const override
Public Member Functions inherited from lyra::detail::choices_base
virtual ~choices_base ()=default
virtual ~choices_base ()=default
virtual parser_result contains_value (std::string const &val) const =0
virtual parser_result contains_value (std::string const &val) const =0
Public Attributes
Lambda checker
Member Typedef Documentation
value_type [1/2]
template<typename Lambda > using lyra::detail::choices_check< Lambda >::value_type = typename unary_lambda_traits<Lambda>::ArgType
value_type [2/2]
template<typename Lambda > using lyra::detail::choices_check< Lambda >::value_type = typename unary_lambda_traits<Lambda>::ArgType
Constructor & Destructor Documentation
choices_check() [1/2]
template<typename Lambda > lyra::detail::choices_check< Lambda >::choices_check (Lambda const & checker_function) inline explicit
choices_check() [2/2]
template<typename Lambda > lyra::detail::choices_check< Lambda >::choices_check (Lambda const & checker_function) inline explicit
Member Function Documentation
contains_value() [1/2]
template<typename Lambda > parser_result lyra::detail::choices_check< Lambda >::contains_value (std::string const & val) const inline override virtual
Implements lyra::detail::choices_base.
References lyra::detail::choices_check< Lambda >::checker, lyra::detail::basic_result< T >::error(), lyra::matched, lyra::no_match, lyra::detail::basic_result< T >::ok(), lyra::detail::parse_string(), and lyra::val().
contains_value() [2/2]
template<typename Lambda > parser_result lyra::detail::choices_check< Lambda >::contains_value (std::string const & val) const inline override virtual
Implements lyra::detail::choices_base.
References lyra::detail::choices_check< Lambda >::checker, lyra::detail::basic_result< T >::error(), lyra::matched, lyra::no_match, lyra::detail::basic_result< T >::ok(), lyra::detail::parse_string(), and lyra::val().
Member Data Documentation
checker
template<typename Lambda > Lambda lyra::detail::choices_check< Lambda >::checker
Referenced by lyra::detail::choices_check< Lambda >::contains_value().
The documentation for this struct was generated from the following files:
Lyra/data/single_include/lyra/lyra.hpp
Lyra/include/lyra/detail/choices.hpp