Skeletal: lyra::detail::parser_cardinality Struct Reference
lyra::detail::parser_cardinality Struct Reference
#include <parser.hpp>
Public Member Functions
parser_cardinality ()=default
parser_cardinality ()=default
parser_cardinality (size_t a, size_t b)
parser_cardinality (size_t a, size_t b)
void bounded (size_t n, size_t m)
void bounded (size_t n, size_t m)
void counted (size_t n)
void counted (size_t n)
bool is_bounded () const
bool is_bounded () const
bool is_optional () const
bool is_optional () const
bool is_required () const
bool is_required () const
bool is_unbounded () const
bool is_unbounded () const
void optional ()
void optional ()
void required (size_t n=1)
void required (size_t n=1)
Public Attributes
size_t maximum = 0
size_t minimum = 0
Constructor & Destructor Documentation
parser_cardinality() [1/4]
lyra::detail::parser_cardinality::parser_cardinality () default
parser_cardinality() [2/4]
lyra::detail::parser_cardinality::parser_cardinality (size_t a, size_t b) inline
parser_cardinality() [3/4]
lyra::detail::parser_cardinality::parser_cardinality () default
parser_cardinality() [4/4]
lyra::detail::parser_cardinality::parser_cardinality (size_t a, size_t b) inline
Member Function Documentation
bounded() [1/2]
void lyra::detail::parser_cardinality::bounded (size_t n, size_t m) inline
References maximum, and minimum.
Referenced by lyra::group::cardinality().
bounded() [2/2]
void lyra::detail::parser_cardinality::bounded (size_t n, size_t m) inline
References maximum, and minimum.
counted() [1/2]
void lyra::detail::parser_cardinality::counted (size_t n) inline
References maximum, and minimum.
Referenced by lyra::group::cardinality().
counted() [2/2]
void lyra::detail::parser_cardinality::counted (size_t n) inline
References maximum, and minimum.
is_bounded() [1/2]
bool lyra::detail::parser_cardinality::is_bounded () const inline
References is_unbounded().
is_bounded() [2/2]
bool lyra::detail::parser_cardinality::is_bounded () const inline
References is_unbounded().
is_optional() [1/2]
bool lyra::detail::parser_cardinality::is_optional () const inline
References minimum.
Referenced by lyra::parser::is_optional().
is_optional() [2/2]
bool lyra::detail::parser_cardinality::is_optional () const inline
References minimum.
is_required() [1/2]
bool lyra::detail::parser_cardinality::is_required () const inline
References minimum.
is_required() [2/2]
bool lyra::detail::parser_cardinality::is_required () const inline
References minimum.
is_unbounded() [1/2]
bool lyra::detail::parser_cardinality::is_unbounded () const inline
References maximum.
Referenced by is_bounded().
is_unbounded() [2/2]
bool lyra::detail::parser_cardinality::is_unbounded () const inline
References maximum.
optional() [1/2]
void lyra::detail::parser_cardinality::optional () inline
References maximum, and minimum.
Referenced by lyra::group::optional().
optional() [2/2]
void lyra::detail::parser_cardinality::optional () inline
References maximum, and minimum.
required() [1/2]
void lyra::detail::parser_cardinality::required (size_t n = 1) inline
References maximum, and minimum.
Referenced by lyra::group::required().
required() [2/2]
void lyra::detail::parser_cardinality::required (size_t n = 1) inline
References maximum, and minimum.
Member Data Documentation
maximum
size_t lyra::detail::parser_cardinality::maximum = 0
Referenced by bounded(), counted(), is_unbounded(), optional(), and required().
minimum
size_t lyra::detail::parser_cardinality::minimum = 0
Referenced by bounded(), counted(), is_optional(), is_required(), optional(), and required().
The documentation for this struct was generated from the following files:
Lyra/data/single_include/lyra/lyra.hpp
Lyra/include/lyra/parser.hpp