Skeletal: lyra::detail::BoundValueRef< std::vector< T > > Struct Template Reference
lyra::detail::BoundValueRef< std::vector< T > > Struct Template Reference
#include <bound.hpp>
Public Member Functions
BoundValueRef (std::vector< T > &ref)
BoundValueRef (std::vector< T > &ref)
virtual std::string get_value (size_t i) const override
virtual std::string get_value (size_t i) const override
virtual size_t get_value_count () const override
virtual size_t get_value_count () const override
auto isContainer () const -> bool override
auto isContainer () const -> bool override
auto setValue (std::string const &arg) -> parser_result override
auto setValue (std::string const &arg) -> parser_result override
virtual auto setValue (std::string const &arg) -> parser_result=0
virtual auto setValue (std::string const &arg) -> parser_result=0
Public Member Functions inherited from lyra::detail::BoundRef
virtual ~BoundRef ()=default
virtual ~BoundRef ()=default
virtual std::string get_value (size_t) const
virtual std::string get_value (size_t) const
virtual size_t get_value_count () const
virtual size_t get_value_count () const
virtual auto isContainer () const -> bool
virtual auto isContainer () const -> bool
virtual auto isFlag () const -> bool
virtual auto isFlag () const -> bool
Public Member Functions inherited from lyra::detail::NonCopyable
NonCopyable ()=default
NonCopyable ()=default
NonCopyable (NonCopyable &&)=delete
NonCopyable (NonCopyable &&)=delete
NonCopyable (NonCopyable const &)=delete
NonCopyable (NonCopyable const &)=delete
NonCopyable & operator= (NonCopyable &&)=delete
NonCopyable & operator= (NonCopyable &&)=delete
NonCopyable & operator= (NonCopyable const &)=delete
NonCopyable & operator= (NonCopyable const &)=delete
Public Attributes
std::vector< T > & m_ref
Constructor & Destructor Documentation
BoundValueRef() [1/2]
template<typename T > lyra::detail::BoundValueRef< std::vector< T > >::BoundValueRef (std::vector< T > & ref) inline explicit
BoundValueRef() [2/2]
template<typename T > lyra::detail::BoundValueRef< std::vector< T > >::BoundValueRef (std::vector< T > & ref) inline explicit
Member Function Documentation
get_value() [1/2]
template<typename T > virtual std::string lyra::detail::BoundValueRef< std::vector< T > >::get_value (size_t i) const inline override virtual
Reimplemented from lyra::detail::BoundRef.
References lyra::detail::BoundValueRef< T >::m_ref, and lyra::detail::to_string().
get_value() [2/2]
template<typename T > virtual std::string lyra::detail::BoundValueRef< std::vector< T > >::get_value (size_t i) const inline override virtual
Reimplemented from lyra::detail::BoundRef.
References lyra::detail::BoundValueRef< T >::m_ref, and lyra::detail::to_string().
get_value_count() [1/2]
template<typename T > virtual size_t lyra::detail::BoundValueRef< std::vector< T > >::get_value_count () const inline override virtual
Reimplemented from lyra::detail::BoundRef.
References lyra::detail::BoundValueRef< T >::m_ref.
get_value_count() [2/2]
template<typename T > virtual size_t lyra::detail::BoundValueRef< std::vector< T > >::get_value_count () const inline override virtual
Reimplemented from lyra::detail::BoundRef.
References lyra::detail::BoundValueRef< T >::m_ref.
isContainer() [1/2]
template<typename T > auto lyra::detail::BoundValueRef< std::vector< T > >::isContainer () const -> bool inline override virtual
Reimplemented from lyra::detail::BoundRef.
isContainer() [2/2]
template<typename T > auto lyra::detail::BoundValueRef< std::vector< T > >::isContainer () const -> bool inline override virtual
Reimplemented from lyra::detail::BoundRef.
setValue() [1/2]
template<typename T > auto lyra::detail::BoundValueRef< std::vector< T > >::setValue (std::string const & arg) -> parser_result inline override virtual
Implements lyra::detail::BoundValueRefBase.
References lyra::detail::BoundValueRef< T >::m_ref, and lyra::detail::parse_string().
setValue() [2/2]
template<typename T > auto lyra::detail::BoundValueRef< std::vector< T > >::setValue (std::string const & arg) -> parser_result inline override virtual
Implements lyra::detail::BoundValueRefBase.
References lyra::detail::BoundValueRef< T >::m_ref, and lyra::detail::parse_string().
Member Data Documentation
m_ref
template<typename T > std::vector< T > & lyra::detail::BoundValueRef< std::vector< T > >::m_ref
The documentation for this struct was generated from the following files:
Lyra/data/single_include/lyra/lyra.hpp
Lyra/include/lyra/detail/bound.hpp