Skeletal: MainNamespace::Options Struct Reference
MainNamespace::Options Struct Reference
#include <options.h>
Public Member Functions
Options (bool const deferInit=false)
Options (int argc, char **argv)
~Options ()
AdmissibilityParameters admissibilityParameters () const
AdmissibilityParameters admissibilityParameters (AdmissibilityParameters const admissibilityParameters_p)
AdmissibilityParameters admissibilityParameters (double const eta1, double const eta2, double const eta3, double const wavek, double const waveki)
size_t clusterResolution () const
size_t clusterResolution (size_t clusterResolution_p)
bool compression () const
bool compression (bool const)
real eps () const
real eps (real eps_p)
real epsKrylov () const
real epsKrylov (real epsKrylov_p)
void fillDefaults ()
Called by the constructor by default.
bool interactive () const
bool interactive (bool interactive_p)
size_t interpolationPoints () const
size_t interpolationPoints (size_t interpolationPoints_p)
std::string meshFile () const
std::string outputDirectory () const
size_t quadraturePoints () const
size_t quadraturePoints (size_t quadraturePoints_p)
bool reference () const
bool reference (bool const reference_p)
void report () const
bool saveError () const
bool saveError (bool saveError_p)
bool saveMesh () const
bool saveMesh (bool saveMesh_p)
bool saveOffset () const
bool saveOffset (bool saveOffset_p)
bool saveRhs () const
bool saveRhs (bool saveRhs_p)
bool saveSolution () const
bool saveSolution (bool saveSolution_p)
field waveNumber () const
Public Attributes
AdmissibilityParameters admissibilityParameters_ {.eta1 = 0, .eta2 = 0, .eta3 = 0, .waveNumber = 0}
size_t clusterResolution_ = 0
bool compression_ = true
real eps_ = 0
real epsKrylov_ = 0
bool interactive_ = false
size_t interpolationPoints_ = 0
std::string meshFile_ = ""
std::string outputDirectory_ = ""
reporter * progressBar_ = nullptr
size_t quadraturePoints_ = 0
bool reference_ = false
Reference matrix.
bool saveError_ = false
bool saveMesh_ = false
bool saveOffset_ = false
bool saveRhs_ = false
bool saveSolution_ = false
Clocks timer_
Detailed Description
Wrapper for Lyra, with the correct variables for this project
See the parser options for a description of the variables
Constructor & Destructor Documentation
Options() [1/2]
MainNamespace::Options::Options (int argc, char ** argv)
Todo:
also get environment here.
References MainNamespace::Clocks::addTimer(), admissibilityParameters_, clusterResolution_, MainNamespace::createProgressBar(), eps_, epsKrylov_, MainNamespace::AdmissibilityParameters::eta1, MainNamespace::AdmissibilityParameters::eta2, MainNamespace::AdmissibilityParameters::eta3, fillDefaults(), MainNamespace::Clocks::format(), MainNamespace::globalOptions(), interactive_, interpolationPoints_, MainNamespace::Logger::log(), meshFile_, outputDirectory_, lyra::cli::parse(), progressBar_, quadraturePoints_, MainNamespace::Logger::red, reference_, saveError_, saveMesh_, saveOffset_, saveRhs_, saveSolution_, timer_, MainNamespace::warning(), and MainNamespace::AdmissibilityParameters::waveNumber.
Options() [2/2]
MainNamespace::Options::Options (bool const deferInit = false)
References MainNamespace::Clocks::addTimer(), MainNamespace::createProgressBar(), fillDefaults(), MainNamespace::Clocks::format(), MainNamespace::globalOptions(), progressBar_, and timer_.
~Options()
MainNamespace::Options::~Options ()
References MainNamespace::globalOptions(), MainNamespace::Logger::log(), MainNamespace::maybeFree(), progressBar_, MainNamespace::Logger::red, and MainNamespace::warning().
Member Function Documentation
admissibilityParameters() [1/3]
AdmissibilityParameters MainNamespace::Options::admissibilityParameters () const inline
References admissibilityParameters_.
Referenced by admissibilityParameters(), main(), and waveNumber().
admissibilityParameters() [2/3]
AdmissibilityParameters MainNamespace::Options::admissibilityParameters (AdmissibilityParameters const admissibilityParameters_p) inline
References admissibilityParameters(), and admissibilityParameters_.
admissibilityParameters() [3/3]
AdmissibilityParameters MainNamespace::Options::admissibilityParameters (double const eta1, double const eta2, double const eta3, double const wavek, double const waveki)
References admissibilityParameters_, MainNamespace::AdmissibilityParameters::eta1, MainNamespace::AdmissibilityParameters::eta2, MainNamespace::AdmissibilityParameters::eta3, and MainNamespace::AdmissibilityParameters::waveNumber.
clusterResolution() [1/2]
size_t MainNamespace::Options::clusterResolution () const inline
References clusterResolution_.
Referenced by clusterResolution(), and fillDefaults().
clusterResolution() [2/2]
size_t MainNamespace::Options::clusterResolution (size_t clusterResolution_p) inline
References clusterResolution(), and clusterResolution_.
compression() [1/2]
bool MainNamespace::Options::compression () const inline
References compression_.
Referenced by MainNamespace::compression(), and compression().
compression() [2/2]
bool MainNamespace::Options::compression (bool const compression_p)
References compression(), and compression_.
eps() [1/2]
real MainNamespace::Options::eps () const inline
References eps_.
Referenced by MainNamespace::eps(), eps(), and fillDefaults().
eps() [2/2]
real MainNamespace::Options::eps (real eps_p) inline
References eps(), and eps_.
epsKrylov() [1/2]
real MainNamespace::Options::epsKrylov () const inline
References epsKrylov_.
Referenced by MainNamespace::epsKrylov(), epsKrylov(), and fillDefaults().
epsKrylov() [2/2]
real MainNamespace::Options::epsKrylov (real epsKrylov_p) inline
References epsKrylov(), and epsKrylov_.
fillDefaults()
void MainNamespace::Options::fillDefaults ()
Called by the constructor by default.
References admissibilityParameters_, clusterResolution(), eps(), epsKrylov(), MainNamespace::AdmissibilityParameters::eta1, MainNamespace::AdmissibilityParameters::eta2, MainNamespace::AdmissibilityParameters::eta3, interactive_, interpolationPoints(), quadraturePoints(), and MainNamespace::AdmissibilityParameters::waveNumber.
Referenced by Options().
interactive() [1/2]
bool MainNamespace::Options::interactive () const inline
References interactive_.
Referenced by MainNamespace::interactive(), and interactive().
interactive() [2/2]
bool MainNamespace::Options::interactive (bool interactive_p) inline
References interactive(), and interactive_.
interpolationPoints() [1/2]
size_t MainNamespace::Options::interpolationPoints () const inline
References interpolationPoints_.
Referenced by fillDefaults(), MainNamespace::interpolationPoints(), and interpolationPoints().
interpolationPoints() [2/2]
size_t MainNamespace::Options::interpolationPoints (size_t interpolationPoints_p) inline
References interpolationPoints(), and interpolationPoints_.
meshFile()
std::string MainNamespace::Options::meshFile () const inline
References meshFile_.
Referenced by main(), and MainNamespace::meshFile().
outputDirectory()
std::string MainNamespace::Options::outputDirectory () const inline
References outputDirectory_.
Referenced by MainNamespace::outputDirectory().
quadraturePoints() [1/2]
size_t MainNamespace::Options::quadraturePoints () const inline
References quadraturePoints_.
Referenced by fillDefaults(), MainNamespace::quadraturePoints(), and quadraturePoints().
quadraturePoints() [2/2]
size_t MainNamespace::Options::quadraturePoints (size_t quadraturePoints_p) inline
References quadraturePoints(), and quadraturePoints_.
reference() [1/2]
bool MainNamespace::Options::reference () const inline
References reference_.
Referenced by MainNamespace::reference(), and reference().
reference() [2/2]
bool MainNamespace::Options::reference (bool const reference_p) inline
References reference(), and reference_.
report()
void MainNamespace::Options::report () const
References clusterResolution_, compression_, MainNamespace::Logger::green, interactive_, interpolationPoints_, MainNamespace::Logger::log(), meshFile_, and quadraturePoints_.
saveError() [1/2]
bool MainNamespace::Options::saveError () const inline
References saveError_.
Referenced by MainNamespace::saveError(), and saveError().
saveError() [2/2]
bool MainNamespace::Options::saveError (bool saveError_p) inline
References saveError(), and saveError_.
saveMesh() [1/2]
bool MainNamespace::Options::saveMesh () const inline
References saveMesh_.
Referenced by MainNamespace::saveMesh(), and saveMesh().
saveMesh() [2/2]
bool MainNamespace::Options::saveMesh (bool saveMesh_p) inline
References saveMesh(), and saveMesh_.
saveOffset() [1/2]
bool MainNamespace::Options::saveOffset () const inline
References saveOffset_.
Referenced by MainNamespace::saveOffset(), and saveOffset().
saveOffset() [2/2]
bool MainNamespace::Options::saveOffset (bool saveOffset_p) inline
References saveOffset(), and saveOffset_.
saveRhs() [1/2]
bool MainNamespace::Options::saveRhs () const inline
References saveRhs_.
Referenced by MainNamespace::saveRhs(), and saveRhs().
saveRhs() [2/2]
bool MainNamespace::Options::saveRhs (bool saveRhs_p) inline
References saveRhs(), and saveRhs_.
saveSolution() [1/2]
bool MainNamespace::Options::saveSolution () const inline
References saveSolution_.
Referenced by MainNamespace::saveSolution(), and saveSolution().
saveSolution() [2/2]
bool MainNamespace::Options::saveSolution (bool saveSolution_p) inline
References saveSolution(), and saveSolution_.
waveNumber()
field MainNamespace::Options::waveNumber () const inline
References admissibilityParameters(), and MainNamespace::AdmissibilityParameters::waveNumber.
Referenced by main().
Member Data Documentation
admissibilityParameters_
AdmissibilityParameters MainNamespace::Options::admissibilityParameters_ {.eta1 = 0, .eta2 = 0, .eta3 = 0, .waveNumber = 0}
Referenced by Options(), admissibilityParameters(), and fillDefaults().
clusterResolution_
size_t MainNamespace::Options::clusterResolution_ = 0
Cluster resolution
Referenced by Options(), MainNamespace::clusterResolution(), clusterResolution(), and report().
compression_
bool MainNamespace::Options::compression_ = true
Compression strategy
Referenced by compression(), and report().
eps_
real MainNamespace::Options::eps_ = 0
Referenced by Options(), and eps().
epsKrylov_
real MainNamespace::Options::epsKrylov_ = 0
Referenced by Options(), and epsKrylov().
interactive_
bool MainNamespace::Options::interactive_ = false
Referenced by Options(), fillDefaults(), interactive(), and report().
interpolationPoints_
size_t MainNamespace::Options::interpolationPoints_ = 0
Referenced by Options(), interpolationPoints(), and report().
meshFile_
std::string MainNamespace::Options::meshFile_ = ""
Referenced by Options(), meshFile(), and report().
outputDirectory_
std::string MainNamespace::Options::outputDirectory_ = ""
Referenced by Options(), and outputDirectory().
progressBar_
reporter* MainNamespace::Options::progressBar_ = nullptr
Referenced by Options(), ~Options(), and MainNamespace::progressBar().
quadraturePoints_
size_t MainNamespace::Options::quadraturePoints_ = 0
Referenced by Options(), quadraturePoints(), and report().
reference_
bool MainNamespace::Options::reference_ = false
Reference matrix.
Referenced by Options(), and reference().
saveError_
bool MainNamespace::Options::saveError_ = false
Referenced by Options(), and saveError().
saveMesh_
bool MainNamespace::Options::saveMesh_ = false
Referenced by Options(), and saveMesh().
saveOffset_
bool MainNamespace::Options::saveOffset_ = false
Referenced by Options(), and saveOffset().
saveRhs_
bool MainNamespace::Options::saveRhs_ = false
Referenced by Options(), and saveRhs().
saveSolution_
bool MainNamespace::Options::saveSolution_ = false
Referenced by Options(), and saveSolution().
timer_
Clocks MainNamespace::Options::timer_
Referenced by Options(), MainNamespace::startTiming(), and MainNamespace::stopTiming().
The documentation for this struct was generated from the following files:
main/options.h
main/options.cpp