Skeletal: lyra::cli::value_result Struct Reference
lyra::cli::value_result Struct Reference
#include <cli.hpp>
Public Member Functions
value_result (const parser *p)
value_result (const parser *p)
operator std::string () const
operator std::string () const
template<typename T >
operator std::vector< T > () const
template<typename T >
operator std::vector< T > () const
template<typename T , typename std::enable_if< detail::is_convertible_from_string< typename detail::remove_cvref< T >::type >::value >::type * = nullptr>
operator T () const
template<typename T , typename std::enable_if< detail::is_convertible_from_string< typename detail::remove_cvref< T >::type >::value >::type * = nullptr>
operator T () const
Private Attributes
const parser * parser_ref = nullptr
Constructor & Destructor Documentation
value_result() [1/2]
lyra::cli::value_result::value_result (const parser * p) inline explicit
value_result() [2/2]
lyra::cli::value_result::value_result (const parser * p) inline explicit
Member Function Documentation
operator std::string() [1/2]
lyra::cli::value_result::operator std::string () const inline
References lyra::parser::get_value(), and parser_ref.
operator std::string() [2/2]
lyra::cli::value_result::operator std::string () const inline
References lyra::parser::get_value(), and parser_ref.
operator std::vector< T >() [1/2]
template<typename T > lyra::cli::value_result::operator std::vector< T > () const inline
References lyra::detail::from_string(), lyra::parser::get_value(), lyra::parser::get_value_count(), and parser_ref.
operator std::vector< T >() [2/2]
template<typename T > lyra::cli::value_result::operator std::vector< T > () const inline
References lyra::detail::from_string(), lyra::parser::get_value(), lyra::parser::get_value_count(), and parser_ref.
operator T() [1/2]
template<typename T , typename std::enable_if< detail::is_convertible_from_string< typename detail::remove_cvref< T >::type >::value >::type * = nullptr> lyra::cli::value_result::operator T () const inline
References lyra::detail::from_string(), lyra::parser::get_value(), and parser_ref.
operator T() [2/2]
template<typename T , typename std::enable_if< detail::is_convertible_from_string< typename detail::remove_cvref< T >::type >::value >::type * = nullptr> lyra::cli::value_result::operator T () const inline
References lyra::detail::from_string(), lyra::parser::get_value(), and parser_ref.
Member Data Documentation
parser_ref
const parser * lyra::cli::value_result::parser_ref = nullptr private
Referenced by operator std::string(), operator std::vector< T >(), and operator T().
The documentation for this struct was generated from the following files:
Lyra/data/single_include/lyra/lyra.hpp
Lyra/include/lyra/cli.hpp