???: MainNamespace::Mesh Struct Reference
MainNamespace::Mesh Struct Reference
#include <meshreader.h>
Public Types
using Membership = short int
Data type for membership information. Currently int, as it can indicate orientation.
using MembershipVector = std::vector< Membership >
Vector of membership information.
using SurfaceList = std::map< std::string, MembershipVector >
List of surfaces (as pairs (name, membership)).
using SurfaceMembership = std::vector< MembershipVector >
Vector of surfaces, each constisting of membership (and orientation) information.
Public Member Functions
Mesh ()
Mesh (Mesh &&)
Mesh (Mesh const &)=delete
~Mesh ()
SpaceVector< double const > normal (size_t const triangleIdx) const
Get the normal to a triangle.
Mesh & operator= (Mesh &&)
std::array< size_t, 3 > triangle (size_t const triangleIdx) const
Get a triangle.
size_t triangles () const
Getter.
SpaceVector< double const > vertex (size_t const vertexIdx) const
Get a vertex.
size_t vertices () const
Getter.
void writeMesh ()
Write a mesh in a custom format, at a custom location. Format: one line with number of vertices, triangles, vertexDofs, triangleDofs; then vertices (coordinates), then triangles (vertex indices triplets).
Public Attributes
SurfaceMembership membership_
Vectors of surfaces with dof membership.
surface3d * mesh_ = nullptr
H2Lib mesh data structure.
size_t triangleDofs_ = 0
Number of triangles which are actually degrees of freedom and not known data.
size_t vertexDofs_ = 0
Number of vertices which are actually degrees of freedom and not known data.
Member Typedef Documentation
Membership
using MainNamespace::Mesh::Membership = short int
Data type for membership information. Currently int, as it can indicate orientation.
MembershipVector
using MainNamespace::Mesh::MembershipVector = std::vector<Membership>
Vector of membership information.
SurfaceList
using MainNamespace::Mesh::SurfaceList = std::map<std::string, MembershipVector>
List of surfaces (as pairs (name, membership)).
SurfaceMembership
using MainNamespace::Mesh::SurfaceMembership = std::vector<MembershipVector>
Vector of surfaces, each constisting of membership (and orientation) information.
Constructor & Destructor Documentation
Mesh() [1/3]
MainNamespace::Mesh::Mesh ()
~Mesh()
MainNamespace::Mesh::~Mesh ()
Mesh() [2/3]
MainNamespace::Mesh::Mesh (Mesh const &) delete
Mesh() [3/3]
MainNamespace::Mesh::Mesh (Mesh && other)
References mesh_.
Member Function Documentation
normal()
SpaceVector< real const > MainNamespace::Mesh::normal (size_t const triangleIdx) const
Get the normal to a triangle.
Returns
The coefficients in the standard basis as an array of double.
Parameters
triangleIdx Triangle index.
References mesh_.
Referenced by MainNamespace::Functions::MeshOffset::l2Neumann().
operator=()
Mesh & MainNamespace::Mesh::operator= (Mesh && other)
References membership_, mesh_, triangleDofs_, and vertexDofs_.
triangle()
std::array< size_t, 3 > MainNamespace::Mesh::triangle (size_t const triangleIdx) const
Get a triangle.
Returns
The indices of the vertices as an array of size_t.
Parameters
triangleIdx Triangle index.
References mesh_.
Referenced by MainNamespace::Functions::MeshOffset::l2Neumann(), and writeMesh().
triangles()
size_t MainNamespace::Mesh::triangles () const
Getter.
Returns
The number of triangles.
References mesh_.
Referenced by MainNamespace::Surface::SingleSurface::SingleSurface(), MainNamespace::Surface::getFromFile(), MainNamespace::MeshReader::parseMesh(), MainNamespace::MeshReader::saveView(), MainNamespace::Surface::SingleSurface::triangles(), and writeMesh().
vertex()
SpaceVector< real const > MainNamespace::Mesh::vertex (size_t const vertexIdx) const
Get a vertex.
Returns
The coordinates as an array of double.
Parameters
vertexIdx Vertex index.
References mesh_.
Referenced by MainNamespace::Functions::MeshOffset::c0Dirichlet(), MainNamespace::Functions::MeshOffset::l2Neumann(), and writeMesh().
vertices()
size_t MainNamespace::Mesh::vertices () const
Getter.
Returns
The number of vertices.
References mesh_.
Referenced by MainNamespace::Surface::SingleSurface::SingleSurface(), MainNamespace::Surface::getFromFile(), MainNamespace::Functions::MeshOffset::l2Neumann(), MainNamespace::MeshReader::parseMesh(), MainNamespace::MeshReader::saveView(), MainNamespace::Surface::SingleSurface::vertices(), and writeMesh().
writeMesh()
void MainNamespace::Mesh::writeMesh ()
Write a mesh in a custom format, at a custom location. Format: one line with number of vertices, triangles, vertexDofs, triangleDofs; then vertices (coordinates), then triangles (vertex indices triplets).
References MainNamespace::Logger::green, MainNamespace::Logger::log(), mesh_, MainNamespace::meshFile(), MainNamespace::Logger::red, MainNamespace::saveMesh(), triangle(), triangleDofs_, triangles(), vertex(), vertexDofs_, vertices(), MainNamespace::warning(), and MainNamespace::Logger::yellow.
Member Data Documentation
membership_
SurfaceMembership MainNamespace::Mesh::membership_
Vectors of surfaces with dof membership.
Referenced by MainNamespace::Surface::MultiSurface::MultiSurface(), MainNamespace::Surface::SingleSurface::SingleSurface(), operator=(), MainNamespace::MeshReader::parseMesh(), and MainNamespace::reorderElements().
mesh_
surface3d* MainNamespace::Mesh::mesh_ = nullptr
H2Lib mesh data structure.
Referenced by Mesh(), MainNamespace::Surface::SingleSurface::SingleSurface(), MainNamespace::Surface::MultiSurface::geometry(), MainNamespace::Surface::getFromFile(), normal(), operator=(), MainNamespace::MeshReader::parseMesh(), triangle(), triangles(), vertex(), vertices(), and writeMesh().
triangleDofs_
size_t MainNamespace::Mesh::triangleDofs_ = 0
Number of triangles which are actually degrees of freedom and not known data.
Referenced by MainNamespace::Surface::SingleSurface::SingleSurface(), MainNamespace::Functions::MeshOffset::c0Dirichlet(), MainNamespace::Surface::getFromFile(), MainNamespace::Functions::MeshOffset::l2Neumann(), MainNamespace::Surface::MultiSurface::neumannBasisSize(), operator=(), MainNamespace::reorderElements(), MainNamespace::MeshReader::saveView(), MainNamespace::Surface::SingleSurface::triangleDofs(), and writeMesh().
vertexDofs_
size_t MainNamespace::Mesh::vertexDofs_ = 0
Number of vertices which are actually degrees of freedom and not known data.
Referenced by MainNamespace::Surface::SingleSurface::SingleSurface(), MainNamespace::Functions::MeshOffset::c0Dirichlet(), MainNamespace::Surface::MultiSurface::dirichletBasisSize(), MainNamespace::Surface::getFromFile(), MainNamespace::Functions::MeshOffset::l2Neumann(), operator=(), MainNamespace::reorderElements(), MainNamespace::MeshReader::saveView(), MainNamespace::Surface::SingleSurface::vertexDofs(), and writeMesh().
The documentation for this struct was generated from the following files:
main/meshreader.h
main/meshreader.cpp